### ISSUE TITLE
xml crash gml_Polygon/srsDimension

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#10]
OVSRV6
C:\ProjDir\Jip\BAG-Tools_issueGH10\cfg\BAG20_Xml2FSS.dms

crash bij ctrl+D op
 /xml/ligplaats/ParsedXML/Objecten_ligplaats/gml_Polygon/srsDimension

In 8.6.3

**Comment by MaartenHilferink** [comment]
cannot reproduce, possible duplicate of (fixed) https://github.com/ObjectVision/GeoDMS/issues/7

**Comment by MaartenHilferink** [comment]
note that categorical values unification error is given at the following calculation rule:

eq(
convert(SubItem(parse_xml(...), "Objecten_ligplaats/gml_Polygon/gml_posList/Parent_rel"),   
, subitem(parse_xml(...), "Objecten_ligplaats/gms_Polygon"
)
,id(SubItem(parse_xml(...), "Objecten_ligplaats/gml_Polygon/gml_posList")


This looks like a useful IntegrityCheck, but the Id(posList) valeus should be casted too to gms_Polygon values.

**Comment by jipclaassens** [comment]
Op het genoemde item crasht geodms 8.6.3 nu idd niet meer.
Maar op een niveau dieper wel nog: 
ctrl+D op
/xml/ligplaats/ParsedXML/Objecten_ligplaats/gml_Polygon/gml_posList/srsDimension
