### ISSUE TITLE
DetailPages: add source description

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#100]

**Comment by eoudejans** [comment]
Implemented, see screenshot.
![source_descr_example_impl](https://user-images.githubusercontent.com/96182097/213207493-65edd5de-fc9a-4825-a92e-fb21b4cad5ac.png)

**Comment by MaartenHilferink** [comment]
Remaining issues: 
- another icon for the 5th button in the DetailPage Toolbar
- clarify the 5-state toggle of SourceDescr (configured, read, write, alll, hide).

**Comment by jipclaassens** [comment]
If a task is moved to done, please close it. Or it isn't done?
