### ISSUE TITLE
Edit palette window in Qt

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#102]

**Comment by eoudejans** [comment]
Required implementation of DMS_RegisterStateChangeNotification callback.

**Comment by MaartenHilferink** [comment]
EditPaletteView can be created from 
- QtGUI User action (TreeView->Popup action)
- initiated from DataView action (LayerControl 0> Popup action)

**Comment by jipclaassens** [comment]
If a task is moved to done, please close it. Or it isn't done?
