### ISSUE TITLE
Shape as background map not drawing if initially zoomed in.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#110]
If a shape background layer is configured via 

`unit<dpoint> AfricanACEA: Format = "ESRI:102022", DialogData = "SourceData/ReadSpatialData/Africa_countries_AEA/inFile/ISO";`

And you open a layer that is only a part of the total background map, zooming out won't show the entire background layer.

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\geodms_africa_cusa2_issueGH110\cfg\Africa.dms`
(was: `C:\ProjDir\Jip\geodms_africa_cusa2_issue110\cfg\Africa.dms`)

To see only a part:
`/SourceData/Roads/Read_src_shps/Algeria/inFile/geometry_bp`

And this one shows the whole background map:
`/SourceData/ReadSpatialData/Corridors/inFile/geometry`

**Comment by MaartenHilferink** [comment]
"Path does not exist"

**Comment by MaartenHilferink** [comment]
C:\ProjDir\Jip\geodms_africa_cusa2_issueGH110\cfg\Africa.dms

**Comment by eoudejans** [comment]
@MaartenHilferink assuming both projections are valid, I would use proj to reproject one to the other. Furthermore, the former seems more explicit in the EPSG codes that define for instance the prime meridian ie. PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]] 
vs
PRIMEM["Greenwich",0]

**Comment by jipclaassens** [comment]
Cannot reproduce:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/ff27b189-7c10-47b5-b372-d73b2ab18a89)

**Comment by jipclaassens** [comment]
Dit effect ?
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/384752f7-8015-472b-88cf-6fc4b31f2338)

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5ae95721-0aac-4d9c-83d4-ba7473f96ba6)
As if it was designed this way.

**Comment by jipclaassens** [comment]
WorldClipRect of LayerSet is by design determined by only the non-topographic (aka background) layers. While drawing, all objects of the layers are clipped by the drawing clip region intersected with the clip region of the layerset.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/98aa81b1-dc07-4b1a-80f2-7a18ae5c5c65)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/33c1b44c-7ee3-46be-86ab-b97b02a705a9)
