### ISSUE TITLE
The euro sign € as fieldname doesnt work in Arithmetic functions in 8.6.5 compared to 7.414

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#114]
in 7.414 the The euro sign € was replaced with an underscore.
In 8.6.5 it isn''t replaced (The euro sign € is visble) but you are not able to do Arithmetic functions with it (for example plus)

**Comment by mtbeek32** [comment]
I tried the following example:

<pre>
unit&lt;uint32&gt; csv
: StorageName     = "%projdir%/data/euro.csv"
, StorageType     = "gdal.vect"
, StorageReadOnly = "True"
{
   attribute&lt;uint32&gt; EuroAtt;
   attribute&lt;uint32&gt; €Att;
}
attribute&lt;uint32&gt; EuroPlusEuro (csv) := csv/EuroAtt + csv/€Att;
</pre>

The euro.csv files looks as follows:
<pre>
EuroAtt;€Att
0;1
</pre>

This works fine to me, can you give an example where this does not work?

**Comment by basvanbemmel** [comment]
It is solved by converting the dms-file from ANSI to UTF8 (covert to UTF-8) in Notepad++8.4.9
It wasnt a problem in 7.414 as these special characters were coverted to underscores.


This was the orginal error (for log-purposes)
<HTML><HEAD></HEAD>
<BODY bgColor=#ddd2d0><H2><A 
href="dms:dp.general:/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32">EG_K_uint32 
</A></H2>
<TABLE>
<TBODY>
<TR>
<TD><A href="dms:edit!FullName">FullName </A></TD>
<TD>/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32 
</TD></TR>
<TR>
<TD>FailState </TD>
<TD>MetaInfo Failed </TD></TR>
<TR>
<TD>FailReason </TD>
<TD>Unknown identifier 'Eigd_Koop_tot_�250_000'<BR><A 
href="dms:dp.general:/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32">/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32 
</A><BR><BR>Context:<BR><BR>1. while in DMS_TreeItem_IncInterestCount( 
/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32: 
AbstrDataItem ) </TD></TR>
<TR>
<TD>ValuesType </TD>
<TD>UInt32 </TD></TR>
<TR>
<TD colSpan=2>
<HR>
</TD></TR>
<TR bgColor=#ffffe0>
<TD><A href="dms:Edit Definition">CalculationRule </A></TD>
<TD>(Eigd_Koop_tot_�250_000 + Eigd_Koop_�250_000_tot_�350_000 + 
Eigd_Koop_boven_�350_000 + <A 
href="dms:dp.general:/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/Eigd_Koop_onbekend">Eigd_Koop_onbekend 
</A>)[uint32] </TD></TR></TBODY></TABLE></BODY></HTML>


[EG_K_uint32 ](dms:dp.general:/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32)
[FullName ](dms:edit!FullName) /PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32  
FailState  MetaInfo Failed  
FailReason  Unknown identifier 'Eigd_Koop_tot_�250_000'
[/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32 ](dms:dp.general:/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32)

Context:

1. while in DMS_TreeItem_IncInterestCount( /PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/EG_K_uint32: AbstrDataItem )  
ValuesType  UInt32  

--------------------------------------------------------------------------------
 
[CalculationRule ](dms:Edit Definition) (Eigd_Koop_tot_�250_000 + Eigd_Koop_�250_000_tot_�350_000 + Eigd_Koop_boven_�350_000 + [Eigd_Koop_onbekend ](dms:dp.general:/PrivData/Impl/Plancapaciteit_2022/Utrecht/Read_Utrecht_gpkg/Eigd_Koop_onbekend))[uint32]
