### ISSUE TITLE
NameSpace conflict arrow operator

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#117]
OVSRV6:
C:\ProjDir\Jip\geodms_africa_cusa2_issueGH117\cfg\Africa.dms
/Analysis/Praia_Dakar_Abidjan/Network/Network_Flooded/UnchangedLinkSet/org_rel
deze heeft values unit Analysis/Praia_Dakar_Abidjan/Network/Network_Original/LinkSet 

en als domain unit       Analysis/Praia_Dakar_Abidjan/Network/Network_Flooded/UnchangedLinkSet

En de values unit zou ook in flooded moeten zijn.

Deze impedance verwijst namelijk naar de verkeerde, Original ipv Flooded:
/Analysis/Praia_Dakar_Abidjan/Network/Network_Flooded/UnchangedLinkSet/Impedance

**Comment by jipclaassens** [comment]
> Vergelijkbaar dit issue:
> 
> ![image](https://user-images.githubusercontent.com/48675272/227161246-0a6e04c2-97a0-407c-9a6a-4568c8014be6.png)
> 
> De onderste geometry heeft een geconfigureerde value type van rdc, terwijl het resultaat van de rekenregel rdc_mm is. GeoDMS geeft hier nu geen error op.

Martin heeft hiervan een unit test gemaakt

**Comment by mtbeek32** [comment]
unit tst voor voorbeeld 3 beschikbaar via:
repository: https://github.com/ObjectVision/GeoDMS-Test
config: unit/operator/cfg/select_with_attr_by_org_rel.dms
request item: /selectie/geometry

item is endogeoneous and explicitly configured, resulting in unclear status

**Comment by jipclaassens** [comment]
Another case:

`/NetworkSetup/ConfigurationPerRegio/all/PrivateTransport/Bike/NetwerkSpec_ebike/UnchangedLinkSet/impedance_congested`
should point to NetwerkSpec_ebike but goes to NetwerkSpec

OVSRV6:
`C:\GeoDMS\ProjDir\Jip\NetworkModel_PBL\cfg\main.dms`

**Comment by MaartenHilferink** [comment]
v8.9.0 O.P. issue fixed:
![image](https://user-images.githubusercontent.com/2284361/228019070-d4be57c7-f9ab-478a-9fa7-02c3de9d91f4.png)
