### ISSUE TITLE
€Att in treeview is prestend as ?Att

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#119]

**Comment by eoudejans** [comment]
Confirmed that the € sign is available in the droidsans (droidsans.ttf) font.

**Comment by eoudejans** [comment]
When no range is provided when loading a font using imgui, latin character set range is set as default. This caused the glyphs outside the latin character set to be discarded.

**Comment by eoudejans** [comment]
Fixed starting from commit https://github.com/ObjectVision/GeoDMS/commit/a5543b9bafe5517ef27cdd8b508e1fedff74fb0b
![uft8_character_support_in_gui](https://user-images.githubusercontent.com/96182097/217555483-ceadc82b-86c4-4072-a66d-8d4bee9584e8.png)
