### ISSUE TITLE
meer tiles in tiledunit geeft verschil, en daarmee ook tussen tiled en untiled

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#12]
```
unit<spoint> monolith :=
	range(
		 gridset(
			 rdc_meter
			,point(-gridsize, gridsize, rdc_meter)
			,point(y_max, x_min, rdc_meter)
			,spoint
		)
		,point(0s, 0s)
		,point(nr_rows, nr_cols)
	),	DialogData = "rdc_meter";
	
// unit<spoint> tiled := TiledUnit(point(1024s, 1280s, monolith)); //25m
unit<spoint> tiled := TiledUnit(point(768s, 768s, monolith)); //100m
	
// unit<spoint> domain := tiled
unit<spoint> domain := monolith
```

poly2grid(geometry,domain) op item: /geography/RegioIndelingen/Gemeente2019_single/Per_AdminDomain

geeft bij tiled 1024x1280 tiles: Nr Values: 66,473,224
geeft bij tiled 768x768 tiles: Nr Values: 66,473,223
geeft bij untiled: Nr Values: 66,473,223

OVSRV6:
C:\ProjDir\Jip\RSLight2021_ontwikkel_3_regressietest_compacted_GH12\Runs\casus.dms

statistics op:
/geography/RegioIndelingen/Gemeente2019_single/Per_AdminDomain

aan en uitzetten van tiling varianten hier:
/geography/perGridsize/size_25m/Domain

**Comment by MaartenHilferink** [comment]
Request for feedback: what is the issue ?
