### ISSUE TITLE
Read grid/vect dataset as unit, with automatic value type for griddata and (if available) for geometry create values unit based on EPSG automatically

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#121]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January  9, 2023</sup>
indien beschikbaar
en evt gelijk conversie naar epsg die je in dialogdata invult</div>

**Comment by mtbeek32** [comment]
Import data with GUI, explorative

**Comment by jipclaassens** [comment]
related? #506

**Comment by eoudejans** [comment]
What should the syntax be for an automatically generated value type?

unit<*> netherlands_borders : StorageType="gdal.vect", StorageName = "Netherlands.shp";

**Comment by eoudejans** [comment]
> related? #506

Weakly related in the sense that more available metainfo should be used, like projection information.

**Comment by jipclaassens** [comment]
> What should the syntax be for an automatically generated value type?
> 
> unit<*> netherlands_borders : StorageType="gdal.vect", StorageName = "Netherlands.shp";

For vector data, this is already implemented. Not yet for grid data.

To make it more consistent, the same way a grid dataset could be configured, like below. Which then gets the ESPG code from the tif-file, and automatically generates an attribute (.e.g., grid_data) with, for example, value type float32.

```
unit<uint32> Netherland_grid : StorageName = "Netherlands.tif";
```

**Comment by eoudejans** [comment]
Thanks for clarifying. Next step is to create a unit test for both vector- and raster datasets with both native and gdal StorageManagers and configure both storages using this simplified syntax as mentioned above. This will initially lead to failed items, which can then be implemented one by one.

**Comment by jipclaassens** [comment]
Test case:

Repo -> HEAD:
`https://github.com/ObjectVision/FileChecker`

First run:
`/WriteFilesCSV`

Then, CTRL+D on:
`/Results`

It shows for all .tif's in the folder whether they are completely zero or null. But this tool needs to have a value type for the read-in tif file. 

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8b3116c0-f6fb-4c39-82e3-b96f5263e10a)

Here you see the same tif files (which are originally uint32) read in as float64, uint32, and uint8. It gives different results

**Comment by eoudejans** [comment]
Implemented automatically generation of GridData attribute with correct value type if GridData is not explicitly defined by the user.

**Comment by eoudejans** [comment]
Note that the issue remains, as it's caused by a numerical overflow check during aggregation:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/cbe1dc1c-8280-4e9f-b470-5723b039589b)

**Comment by eoudejans** [comment]
Furthermore, the assumption made on the tiffs datatypes in the filechecker repo should be reconsidered as all tiffs have 4 bands, each band of type UInt8. Which is assumed to be interpreted as 4-band interleaved read UInt32 type.

**Comment by eoudejans** [comment]
Spatial reference unit is now automatically created using gdal.vect if:
- geometry is missing, but the dataset has geometry field

See:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/fda65999-20a8-437f-9a5d-8f959a62aa52)

**Comment by eoudejans** [comment]
SpatialReference now internally sets the **SpatialReference** property.

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/400dbe3c-9065-4271-b9aa-ec64308b7808)
