### ISSUE TITLE
Export kaart functionaliteiten

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#126]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January  9, 2023</sup>
check hoe het nu precies werkt
- zoomlevel
- extents

---------------

@bas: bij volgende werkbezoek met Martin eens kijken naar de ExportSettings functionaliteit en "Export the viewport data to bitmaps files.." knop ? Zoomlevels reproduceren: zie mantis issue 253.

--------------

Het is vrij simpel eigenlijk ik wil een export kunnen maken van de mapview (dus meerdere lagen over elkaar eventueel, bijvoorbeeld vector over een grid) inclusief legenda. Op een hoge resolutie (dus geen printscreen 72 of 96 dpi resolutie wat bij de copy visible content gebeurd). In feite zou dit een soort van basisfunctionaliteit moeten zijn, maar dit raakt ook aan de discussie wat jullie ambitie is om er een meer totaal-GIS-pakket van te maken (waarin kartografie ook een plaats heeft). Ik zou eerst snel nagaan hoeveel werk dit überhaupt gaat kosten. 2 a 3 dagen ok maar geen weken lijkt mij.

------------

@basvanbemmel1 kun je hier een usecase van geven?</div>

**Comment by mtbeek32** [comment]
Zie: https://github.com/ObjectVision/GeoDMS/wiki/Export-viewports

**Comment by jipclaassens** [comment]
#163 #132

**Comment by jipclaassens** [comment]
hoe dit te doen laat Martin zien aan Bas wanneer hij bij Object Vsion is

**Comment by eoudejans** [comment]
Wanneer Bas dit nodig heeft trek hij bij Martin aan de bel
