### ISSUE TITLE
Export primary data (export option with right mouse click at item)

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#128]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/115

<div type='discussions-op-text'>

<sup>Originally posted by **basvanbemmel** February  3, 2023</sup>
It's now possible (8.6.5) to export shp without configuration.
Adding gpkg is advisable (without configuratio) as also gpkg is more the deafult to read vector data.</div>

**Comment by eoudejans** [comment]
Comment martin: in export met checkboxen aangeven of tabellen/attributen wel of niet meer worden geexporteerd

**Comment by eoudejans** [comment]
connect operator gives list of what polygon overlaps with what polygon.
Question: can this also be done in gui to visually zoom in on overlapping geometries within one layer

**Comment by eoudejans** [comment]
in export met checkboxen aangeven of tabellen/attributen wel of niet meer worden geexporteerd

**Comment by eoudejans** [comment]
Also export metainfo

**Comment by jipclaassens** [comment]
If a task is moved to done, please close it. Or it isn't done?
