### ISSUE TITLE
selecteren van overlappende polygonen in featurelayer in GUI 

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#129]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/48

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January  9, 2023</sup>
nu klikken op polygonen met overlap werkt niet altijd lekker

Maarten Hilferink [28 Feb 2022 at 16:59](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#comment-621cf1559039f019d52da368)
inversion of drawing order

[Reply](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#)
Maarten Hilferink [28 Feb 2022 at 16:58](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#comment-621cf11b79db997539a27104)
temp transparency van overlappend polygoon vanuit layer control

[Reply](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#)
Maarten Hilferink [28 Feb 2022 at 16:56](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#comment-621cf0b333c84f76a6ddea7c)
meerdere values van over elkaar liggende polygonen in dezelfde layer tonen als mini-tabel in de layer control.

[Reply](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#)
Maarten Hilferink [28 Feb 2022 at 16:55](https://trello.com/c/Qv6XQ3QW/54-iets-van-functionaliteit-om-overlappende-polygonen-te-kunnen-onderzoeken-zien-wat-eronder-ligt#comment-621cf0832da9176d4acc48f9) (edited)
alle values van verschillende layers in controls tonen (muv topografische lagen, inactief of WMS)</div>

**Comment by eoudejans** [comment]
in export met checkboxen aangeven of tabellen/attributen wel of niet meer worden geexporteerd

**Comment by mtbeek32** [comment]
Menu option to select overlapping polygons in one layer.

**Comment by MaartenHilferink** [comment]
PolygonLayer::SelectPoint kan een LayerInfoControl per gevonden polygoon in de LayerControl zetten. Per value is dan aanvullende value-info benaderbaar door er op te dubbelklikken.

**Comment by MaartenHilferink** [comment]
Wie heeft een testcase om meedere polygonen selectie mee te kunnen testen ?

**Comment by jipclaassens** [comment]
Bag zuidas zonder status selectie

**Comment by jipclaassens** [comment]
@basvanbemmel maakt een kleine test case

**Comment by jipclaassens** [comment]
@jipclaassens laat maarten een case zien

**Comment by jipclaassens** [comment]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\Issue_129\issue_129.dms`

`/overlappende_panden/geometry`

**Comment by MaartenHilferink** [comment]
When selecting by point in a polygonlayer with the shift or control key, and showing selected-only rows in a related table view, one gets:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/b5883401-0936-49fb-ac6f-91c27119f21a)

**Comment by eoudejans** [comment]
Related to #295
