### ISSUE TITLE
explicitsupplier rekent niet uit, bij doorlink zonder expliciet geconfigureerde items

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#13]
Zonder de te genereren items expliciet te configureren, geeft de generate parameter direct 'Ready' aan, zonder iets uit te rekenen. Configureer je ze wel, dan werkt t wel.

**Werkt niet:**
```
unit<uint32> TomTom_Network_fss_select := TomTom_Network_gpkg
, StorageName = "%SourceDataProjDir%/Infrastructure/TomTom/NW2021_SP_streets.fss";

parameter<string> generate_relevant_items := 'Ready', ExplicitSuppliers = "TomTom_Network_fss_select/Geometry";
```

**Werkt wel:**
```
unit<uint32> TomTom_Network_fss_select := TomTom_Network_gpkg
, StorageName = "%SourceDataProjDir%/Infrastructure/TomTom/NW2021_SP_streets.fss"
{
	attribute<BaseProjection>     Geometry (arc) := TomTom_Network_gpkg/Geometry;
}

parameter<string> generate_relevant_items := 'Ready', ExplicitSuppliers = "TomTom_Network_fss_select/Geometry";
```
OVSRV6:
```C:\ProjDir\Jip\NetworkModel_EU_GH13\cfg\main.dms```
```/SourceData/Infrastructure/TomTom/generate_relevant_items```

**Comment by MaartenHilferink** [comment]
Cannot reproduce:

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ab67b215-bd86-4d54-ac59-faec4d9b6d4d)

**Comment by jipclaassens** [comment]
Now you can try it again on OVSRV6
