### ISSUE TITLE
Zoom levels snap to wms layer

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#131]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January  9, 2023</sup>
Zoom niveuas snappen naar wms laag</div>

**Comment by MaartenHilferink** [comment]
Background layers in main ViewPort look more pretty now with readable labels. Remaining issue: Overview Port in UpperRight remains   toe be snapped whenever possible.
