### ISSUE TITLE
save desktops to file, uitgeklede functionaliteit

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#132]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January  9, 2023</sup>
Erik Oudejans [7 Nov 2022 at 17:56](https://trello.com/c/E8E9lcMn/101-save-desktops-to-file-uitgeklede-functionaliteit#comment-636938d3e2898a03d60203b2) (edited)
SetContents DataView
SHV_DataViewCreate -> kan ook weggeschreven context mee krijgen</div>

**Comment by MaartenHilferink** [comment]
Block reason: wait for imGUI beta

**Comment by jipclaassens** [comment]
wordt geimplementeerd met #163
