### ISSUE TITLE
distance and area Measurements in GUI

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#133]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January  9, 2023</sup>
iets met selectie tool om afstand te kunnen met in de GUI.
oppervlak, omtrek, afstand, etc.

Aansluiten bij standaard GIS tools.</div>

**Comment by eoudejans** [comment]
Also support latitude longitude or more exotic projections?

**Comment by MaartenHilferink** [comment]
Block reason: wait for EPSG related SpatialReference integration of axis order, and scale

**Comment by jipclaassens** [comment]
Block: wait for IMgui

**Comment by MaartenHilferink** [comment]
Select Circle, Rectangle en polygon tools zullen Coordinate notification channel gaan gebruiken voor weergave van relevante area en distance of perimeter.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e58ff1b6-883c-4c27-842c-55e7aafba542)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/83e4f5b2-403f-4829-b760-e31fea708348)

**Comment by MaartenHilferink** [comment]
Met lat long gaat er nog iets niet helemaal goed 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9072aba1-6744-4c31-bb93-32e6b2c797f4)

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/04c6db83-b06b-4d11-b436-6299c76a5633)

**Comment by MaartenHilferink** [comment]
The degree in radians issue is now fixed:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/5cac50c9-acc7-478e-bff3-4bff246e9384)

**Comment by MaartenHilferink** [comment]
And perimeter and Area for a selection polygon:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e7d3c2bc-4b4c-4921-9a41-e66beeda1a9f)

**Comment by MaartenHilferink** [comment]
Meer Mercator Measures:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/23c0e65d-031c-4fee-8337-15cd71edc867)
