### ISSUE TITLE
select via mapview resulteert in crash

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#14]
map view van /SourceData/Infrastructure/Infra_Unchecked/Connectiveness/NodeSet/PartNr
dan helemaal inzoomen naar een node, en dan met de maptools 'Select objects in the active layer by drawing a rectangle' op een enkele node. Dit resulteert na enkele seconden in een crash.

OVSRV6:
C:\ProjDir\Jip\NetworkModel_EU_GH14\cfg\main.dms

/SourceData/Infrastructure/Infra_Unchecked/Connectiveness/NodeSet/PartNr

**Comment by MaartenHilferink** [comment]
reproduced !
