### ISSUE TITLE
Polygon visualisation : don's show arcs if too small

### ISSUE THREAD

**Issue by jan-perl** [ObjectVision/GeoDMS#141]
I tried to swtch off arcs in polygon plots. Wiki doesn't tell if this is possible.
I tried:

parameter<int16>  PenWidth      := 0s          , DialogType = "PenWidth";
parameter<meter>  PenWorldWidth := Percentage13K/PenWorldWidth, DialogType = "PenWorldWidth";

What I really would like is a setting in the polygon visualisation: if the PenWorldWidth becomes less than say 1/000 of a pixel, then do not show it. Then, on detailed scales, arcs are shown, and on large scales the arcs do not show instead of the data.

**Comment by jipclaassens** [comment]
duplicate of #642
