### ISSUE TITLE
please describe syntax of properties

### ISSUE THREAD

**Issue by jan-perl** [ObjectVision/GeoDMS#145]
https://github.com/ObjectVision/GeoDMS/wiki/Property
does not decribe the syntax

I have seen properties with constant values, arrays and strings.
However, one apparenty cannot use variables.
Unless an = sign is used, but I ony found this from a code repository in VestaMais

I could not find a good description in the wiki for the code fragment below.
https://github.com/jan-perl/EPcheck/blob/main/cfg/EPcheck.dms
where an = sign is used inside the StorageName  property.

Please describe this in 
https://github.com/ObjectVision/GeoDMS/wiki/Property

and give an example (e.g. something like the one below).

       parameter<string> bagsrcfil := iif( config1/alleen_Ameland,"%ProjDir%/data/BAG_Ameland_20230101/BAG_Ameland_20230101.gpkg",
	          "%ProjDir%/data/bag_snapshot_20221001/snapshot_20221001.gpkg");

	container bag_snapshot_result: 
  StorageName     = "=bagsrcfil" // Path to shapefile (2D spatial dataset + N attributes)
, StorageType     = "gdal.vect"
, StorageReadOnly = "True"
, SyncMode        = "allTables"
, DialogData      = "geography/rdc";

**Comment by mtbeek32** [comment]
the use of = in properties means an [indirect expression](https://github.com/ObjectVision/GeoDMS/wiki/Indirect-expression) can be used to generate the result of the property, e.g. based on the contents of other items.

Most properties support this, except for boolean properties and properties with a set of allowed tokens, like DialogData.

**Comment by jipclaassens** [comment]
Examples are now available at the bottom of the properties page.
