### ISSUE TITLE
Cannot determine Layer item  

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#15]
export naar csv met gdalwrite.vect geeft 

<HTML><HEAD></HEAD>
<BODY bgColor=#ddd2d0>
<TABLE>
<TBODY><TR>
<TD>FailState </TD>
<TD>Primary Data Derivation Failed </TD></TR>
<TR>
<TD>FailReason </TD>
<TD>Cannot determine Layer item<BR></TD></TR></TBODY></TABLE></BODY></HTML>

OVSRV8:
C:\ProjDir\Jip\RVNL_GH15\Runs\casus.dms

ctrl+D op
/CaseIndicatoren/Export/Verharding/Result

v8.6.3

**Comment by MaartenHilferink** [comment]
Config: 

		attribute<float32> Result (impl/ProvincieTotaal) := = 'union_data(impl/ProvincieTotaal, '+AsItemList('Provincies/'+impl/Provincie/name)+', Y2050/Verharding/Per_NL/fractie)'
		, StorageName = "='%LocalDataProjDir%/Indicatoren/'+casus_name+'/Verharding.csv'", StorageType = "gdalwrite.vect";

workaround:

		container x: StorageName = "='%LocalDataProjDir%/Indicatoren/'+casus_name+'/Verharding.csv'", StorageType = "gdalwrite.vect"
		{
				attribute<float32> Result (impl/ProvincieTotaal) := = 'union_data(impl/ProvincieTotaal, '+AsItemList('Provincies/'+impl/Provincie/name)+', Y2050/Verharding/Per_NL/fractie)';
		}

feature request: make the above config

**Comment by MaartenHilferink** [comment]
Fixed in 8.6.3
