### ISSUE TITLE
issues with zooming in/out to WMS level

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#151]
GeoDMS 8.7.1

Repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration: operator\cfg\microtst.dms
Request item: /BackGroundLayer/district/hoek in Map View

1) Zoom out with - button, zooms out but not to WMS level 
2) Zoom in with + button does not zoom at all
3) Zoom in/out with mouse does not zoom to WMS level

**Comment by MaartenHilferink** [comment]
Workaround: use the '+' and '-'keys; they work as indended. I'll connect the ZoomIn and ZoomOut tool commands to the same event handlers in v8.7.1

**Comment by MaartenHilferink** [comment]
MouseClick with ZoomIn or ZoomOut tools activated and MouseScroll now work as '+', and '-', except that they leave invariant the location indicated by the mouse pointer location.
