### ISSUE TITLE
Explain Value does not seem to work for values read from data source

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#154]
Reproduce:

Repository: _https://github.com/ObjectVision/GeoDMS-Test_ 
Configuration: _operator/cfg/operator.dms_
Request item: _Relational/UnTiled2UnTiled/union_data/CityNamesSrcWithEntries_ in table and double click a value in the table. 

No Explain Value is shown.

**Comment by MaartenHilferink** [comment]
Not a defect:
Double click on editable text cell starts the edit modus for that cell (similar to F2), which I'd like to keep. 
I'll add an Explain value option to the popup-menu of the Table (for the Cell on which the popup menu was requested).
