### ISSUE TITLE
itemtype in error message

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#155]
The current error message for an incompatible composition type is: 
_ItemType is incompatible with the result of the calculation which is of type DataItem<FPolygon>
/intersect/geometry_rd_

It would be nice to replace the word itemType with the configured values unit.

**Comment by MaartenHilferink** [comment]
in 8.8.2:

void FailItemType(const TreeItem* self, const TreeItem* refItem)
{
	auto msg = mySSPrintF("ItemType %s is incompatible with the result of the calculation which is of type %s"
	,	self->GetDynamicObjClass()->GetName().c_str()
	,	refItem->GetDynamicObjClass()->GetName().c_str()
	);
	self->Fail(msg, FR_Determine);
}
