### ISSUE TITLE
Use Windows System colors for imGUI elemements

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#157]
A user may have selected a color theme that defines default or alternate colors for common gui elements. Better to use them to avoid surprises and misinterpretations:

In general: https://learn.microsoft.com/en-us/dotnet/api/system.drawing.systemcolors?view=net-6.0

For MDI client area, see: https://learn.microsoft.com/en-us/dotnet/api/system.drawing.systemcolors.appworkspace?view=net-6.0#system-drawing-systemcolors-appworkspace

Let's find out how to obtain RGV values for these system colors by the Win32 api.

**Comment by MaartenHilferink** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsyscolor
more specifically:
`GetSysColor(COLOR_APPWORKSPACE)`
Meaning: Background color of multiple document interface (MDI) applications.
**Windows 10 or greater**: This value is not supported.

**Comment by MaartenHilferink** [comment]
Implementation  of this issue is not required for imGUI-beta

**Comment by eoudejans** [comment]
Although technically not much work to implement, this will make GeoDMS more Windows bound.
Brief search for similar functionality for MacOS and Linux returned no usable results.

**Comment by MaartenHilferink** [comment]
no longer needed
