### ISSUE TITLE
unclear error in select_afew function

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#158]
repository: https://github.com/ObjectVision/GeoDMS-Test
configuration: other/cfg/select_afew_unclear_error.dms

Activate item: _sel_, error in Detailpage General

Issue: second argument results in a unit, a condition is expected. Error should be that a condition is expected.

**Comment by MaartenHilferink** [comment]
FailState is now:

select_afew Error: condition data-item expected as 2nd argument
