### ISSUE TITLE
Test and document using the GeoDMS on Linux with WINE

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#16]

**Comment by eoudejans** [comment]
Geodms runs on linux fedora using WINE.
GeoDMSGui.exe:
![Screenshot from 2023-01-09 12-35-37](https://user-images.githubusercontent.com/96182097/211301553-4c798897-15af-4d38-b61c-e6d6bb67145f.png)

GeoDMSImGui.exe:
![Screenshot from 2023-01-09 12-48-15](https://user-images.githubusercontent.com/96182097/211301577-095bc3cf-3010-44c4-ba1c-5d8f86afb079.png)

**Comment by eoudejans** [comment]
To run GeoDMSGui.exe on fedora linux using WINE go through the following steps:
1) Install WINE using the package manager
2) Open wine configuration and in Libraries add concrt140 and msvcrt:
![Screenshot from 2023-01-09 12-54-31](https://user-images.githubusercontent.com/96182097/211302338-1d1811cb-5fc8-4c2e-b497-42c341669ddb.png)
3) Download GeoDMS.exe from github
4) Open a terminal and execute GeoDMS.exe using command: wine GeoDMS.exe and follow the installation procedure.  To see the drives mapping wine uses go to Wine configuration and go to Drives.
5) After installation run for instance GeoDMSGui.exe using command: WINEDEBUG=fixme-all wine ./GeoDmsImGui.exe the first definition is needed to suppress wine messages.

GeoDMS should now be up and running. The delphi detailpage component is not supported by WINE. To circumvent this, the user can also use the new GeoDMSImGui.exe. Note that docking windows is not nicely supported as mousedrag event gets lost by WINE, to setup the windows properly, the user can temporarily disable all options in the wine configuration Graphics section:
![Screenshot from 2023-01-09 12-59-44](https://user-images.githubusercontent.com/96182097/211303204-d3c40bfe-4ae0-426e-8afd-cae79b7e560c.png)

**Comment by eoudejans** [comment]
Message that hampers performance significantly, suppressed by using WINEDEBUG=fixme-all wine ... :

![Screenshot from 2023-01-09 11-59-24](https://user-images.githubusercontent.com/96182097/211303568-03e1d1ad-b7da-425a-b6cb-b96ef4d35d09.png)

**Comment by eoudejans** [comment]
To start a terminal on mac follow: https://www.howtogeek.com/682770/how-to-open-the-terminal-on-a-mac/

**Comment by jipclaassens** [comment]
WINE is not relevant anymore with new GUI, so issue #138 is only relevant here.
