### ISSUE TITLE
Cut and Paste Scale, and ROI, similar to coordinates keys: Ctrl-LBUTTON-> EID_COPYCOORD and Ctrl-G ->TB_GotoClipboardLocation ; see also #91

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#162]
Similar to coordinates keys with format "[ X=999.999; Y=999.999]":
- Ctrl-LBUTTON-> EID_COPYCOORD and 
- Ctrl-G ->TB_GotoClipboardLocation ; see also #91 and #132

Such as: Shfit-R for storing "[ X=999.999; Y=999.999]: scale = 999" and Ctrl-R for reapply such Clipboard

**Comment by mtbeek32** [comment]
Suggested key combinations:

- Ctrl-0 Store both XY center point and zoomlevel in clipboard

- Ctrl-1 Apply XY center point on active mapview
- Ctrl-2 Apply zoomlevel on active mapview
- Ctrl-3 Apply both XY center point and zoomlevel on active mapview

- Shift Ctrl-1 Apply XY center point on all mapviews
- Shift Ctrl-2 Apply zoomlevel on all mapviews
- Shift Ctrl-3 Apply both XY center point and zoomlevel on all mapviews

**Comment by MaartenHilferink** [comment]
Implemented, also available from the pop-up menu in any ViewPort.
