### ISSUE TITLE
naamgeving subitems van operatoren, laten aansluiten met nieuwe standaard

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#165]
- [x] Combine
- [x] split_partitioned_union_polygon (nr_orgentity to partition_rel?) #185 
- [x] split_polygon
- [x] connect
- [x] connect_info_(eq)_(ne)

**Comment by MaartenHilferink** [comment]
nr_1 -> first_rel, nr_b nth_rel.

**Comment by MaartenHilferink** [comment]
See also #185

**Comment by MaartenHilferink** [comment]
[] arcs2segm, sequence2points: SequenceNr -> sequence_rel
[] dyna_point, dyna_point_with_ends, dyna_segment, dyna_segment_with_ends: ???
