### ISSUE TITLE
GeoDMS axis order, and projection based domain check

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#166]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **eoudejans** February  8, 2023</sup>
Observation that the GeoAcademy defines col row (xy) in config.ini whereas default GeoDMS uses row col order (yx).
col row (xy) order seems to be more natural to most users and is how most projections are defined (with exception of for instance EPGS:4326, which defines north, east: lat, lon: yx order)
We could choose to follow gdal that always follows the authority (EPGS, ESRI, PROJ etc) projection definition.</div>

**Comment by eoudejans** [comment]
Is partly reason for block of issue #133

**Comment by jipclaassens** [comment]
Beperking backward compatibly:
- nieuwe pointcol/row operatoren, bijv pointx/y
- nieuwe operator: point_@@@(coordinaat 1, coordinaat 2, coordinaat systeem)

Vraag PBL:
- wat doen we met shapefiles inlezen?

**Comment by MaartenHilferink** [comment]
Fixed with implementation path mentioned in #563, addition of point_xy and point_yx functions, and depreciation of point(first, second) and related ambigous syntax, obsolete from GeoDms 15.0.0
