### ISSUE TITLE
Crashing at Azure with 8-serie

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#167]
error crashing in 8.7.1 (not sure if this is the error when crashing)

Log Name:      Application
Source:        Application Error
Date:          3/2/2023 2:37:03 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      geodms-p-0.pblm.local
Description:
Faulting application name: GeoDmsGui.exe, version: 0.0.0.0, time stamp: 0x63eba61c
Faulting module name: Clc2.dll, version: 0.0.0.0, time stamp: 0x63f630c2
Exception code: 0xc0000005
Fault offset: 0x000000000015e9bc
Faulting process id: 0x2e88
Faulting application start time: 0x01d94cdd68f7c5df
Faulting application path: C:\Program Files\ObjectVision\GeoDms8.7.1\GeoDmsGui.exe
Faulting module path: C:\Program Files\ObjectVision\GeoDms8.7.1\Clc2.dll
Report Id: e090f2a7-06b1-4f98-bd2d-1591aac0cee3
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-02T13:37:03.333428500Z" />
    <EventRecordID>87471</EventRecordID>
    <Channel>Application</Channel>
    <Computer>geodms-p-0.pblm.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>GeoDmsGui.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>63eba61c</Data>
    <Data>Clc2.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>63f630c2</Data>
    <Data>c0000005</Data>
    <Data>000000000015e9bc</Data>
    <Data>2e88</Data>
    <Data>01d94cdd68f7c5df</Data>
    <Data>C:\Program Files\ObjectVision\GeoDms8.7.1\GeoDmsGui.exe</Data>
    <Data>C:\Program Files\ObjectVision\GeoDms8.7.1\Clc2.dll</Data>
    <Data>e090f2a7-06b1-4f98-bd2d-1591aac0cee3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

![871](https://user-images.githubusercontent.com/24241780/223157738-4aea96e6-e67e-4cab-8b10-2496ffb9085f.jpg)

**Comment by basvanbemmel** [comment]
Ik had net weer een crash echter geheel niets in alle logs over te vinden helaas

**Comment by basvanbemmel** [comment]
Ik had nu een crash in 8.7.1 met log. Weer met Clc2.dll
Was met een overlay32 hoewel het daar denk ik niet mee te maken heb,




Faulting application name: GeoDmsGui.exe, version: 0.0.0.0, time stamp: 0x63eba61c
Faulting module name: Clc2.dll, version: 0.0.0.0, time stamp: 0x63f630c2
Exception code: 0xc0000005
Fault offset: 0x000000000015e9bc
Faulting process id: 0x2488
Faulting application start time: 0x01d9524e75a7bf9b
Faulting application path: C:\Program Files\ObjectVision\GeoDms8.7.1\GeoDmsGui.exe
Faulting module path: C:\Program Files\ObjectVision\GeoDms8.7.1\Clc2.dll
Report Id: 027e610b-addf-445a-a314-194b5a54041c
Faulting package full name: 
Faulting package-relative application ID: 



[-](https://github.com/ObjectVision/GeoDMS/issues/167#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/ObjectVision/GeoDMS/issues/167#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-03-09T06:23:58.262252400Z" /> 
  <EventRecordID>88156</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>geodms-p-0.pblm.local</Computer> 
  <Security /> 
  </System>
[-](https://github.com/ObjectVision/GeoDMS/issues/167#) <EventData>
  <Data>GeoDmsGui.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>63eba61c</Data> 
  <Data>Clc2.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>63f630c2</Data> 
  <Data>c0000005</Data> 
  <Data>000000000015e9bc</Data> 
  <Data>2488</Data> 
  <Data>01d9524e75a7bf9b</Data> 
  <Data>C:\Program Files\ObjectVision\GeoDms8.7.1\GeoDmsGui.exe</Data> 
  <Data>C:\Program Files\ObjectVision\GeoDms8.7.1\Clc2.dll</Data> 
  <Data>027e610b-addf-445a-a314-194b5a54041c</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by basvanbemmel** [comment]
En ik had er weer een (begint trouwens wel een serieuzer probleem te worden)

Faulting application name: GeoDmsGui.exe, version: 0.0.0.0, time stamp: 0x63eba61c
Faulting module name: Clc2.dll, version: 0.0.0.0, time stamp: 0x63f630c2
Exception code: 0xc0000005
Fault offset: 0x000000000015e9bf
Faulting process id: 0x2be0
Faulting application start time: 0x01d9528f69f3ac64
Faulting application path: C:\Program Files\ObjectVision\GeoDms8.7.1\GeoDmsGui.exe
Faulting module path: C:\Program Files\ObjectVision\GeoDms8.7.1\Clc2.dll
Report Id: 02bb5147-b4a5-469b-ba87-1259a7ae6cdd
Faulting package full name: 
Faulting package-relative application ID:

**Comment by MaartenHilferink** [comment]
Welke configs ? Geheugen ?

**Comment by MaartenHilferink** [comment]
functies die Clc2 doet zijn gerelateerd aan deze code-units.
![image](https://user-images.githubusercontent.com/2284361/224083536-ddaf8685-aa17-43a4-af34-5345df610d66.png)

Dus niet overlay, want die zit in Clc1.dll:
![image](https://user-images.githubusercontent.com/2284361/224083792-4a5ed208-3e91-4201-ac81-45d23e192edb.png)

**Comment by basvanbemmel** [comment]
PD9704: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3_PlanMonitor2023
SD9686: https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL
GeoDMS 8.7.1
run RunAll.cmd (N,Y,N)
Open Casus.dms
Ga naar:
/Planmonitor2023/Analyse/RestrictiesKwetsbareWaarden/RK/BAU/var/RestrictiesKwetsbaarcombine/UnionData

Wijzig bijvoorbeeld de naam van de overlaygrids (/Planmonitor2023/Analyse/RestrictiesKwetsbareWaarden/RK/BAU/var/OverlayGrids)
of wellicht nog beter verwijs naar een ander grid!

Alt R

**Comment by MaartenHilferink** [comment]
RunAll draait; morgen verder met Casus.dms

**Comment by basvanbemmel** [comment]
Ik heb wellicht een reproduceerbaar scenario:

Open (control M):
/Planmonitor2023/Analyse/RestrictiesKwetsbareWaarden/RK/BAU/var/RestrictiesKwetsbaarcombine/UnionData

wijzig regel 23 (RSLight2021_ontwikkel_3_PlanMonitor2023\cfg\RSLight2021\Planmonitor2023\Analyse\Restricties_KwetsbareWaarden.dms)
van
				attribute<uint8> Kwets       (AdminDomain) := KwetsbareWaarden/any/IsKwetsbaar[uint8];
naar
				attribute<uint8> Kwets       (AdminDomain) := /Planmonitor2023/KwetsbareWaarden/Hoofdwatersysteem/IsKwetsbaar[uint8];


AltR
/Planmonitor2023/Analyse/RestrictiesKwetsbareWaarden/RK/BAU/var/RestrictiesKwetsbaarcombine/UnionData

wijzig regel 23:
van
					attribute<uint8> Kwets       (AdminDomain) := /Planmonitor2023/KwetsbareWaarden/Hoofdwatersysteem/IsKwetsbaar[uint8];

naar
			attribute<uint8> Kwets       (AdminDomain) := KwetsbareWaarden/any/IsKwetsbaar[uint8];


AltR
/Planmonitor2023/Analyse/RestrictiesKwetsbareWaarden/RK/BAU/var/RestrictiesKwetsbaarcombine/UnionData


en na 10 seconden crash


Faulting application name: GeoDmsGui.exe, version: 0.0.0.0, time stamp: 0x63eba61c
Faulting module name: Clc2.dll, version: 0.0.0.0, time stamp: 0x63f630c2
Exception code: 0xc0000005
Fault offset: 0x00000000000a950f
Faulting process id: 0x1ec0
Faulting application start time: 0x01d952ad0d1dbe41
Faulting application path: C:\Program Files\ObjectVision\GeoDms8.7.1\GeoDmsGui.exe
Faulting module path: C:\Program Files\ObjectVision\GeoDms8.7.1\Clc2.dll
Report Id: f0304304-0f52-48fb-af88-58cc43452a5e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by MaartenHilferink** [comment]
Probeer al de hele ochtend, wel een deadlock wegens wait op Class count waarvan de bereken thread is verdwenen. Hoe staan jouw MT flags ? Zo ? 
![image](https://user-images.githubusercontent.com/2284361/224298375-e56916e8-4e5f-4096-b084-fef87eacd391.png)

**Comment by basvanbemmel** [comment]
Zie whatsapp

Verstuurd vanaf mijn iPhone

Op 10 mrt. 2023 om 11:55 heeft Maarten Hilferink ***@***.***> het volgende geschreven:

﻿

Probeer al de hele ochtend, wel een deadlock wegens wait op Class count waarvan de bereken thread is verdwenen. Hoe staan jouw MT flags ? Zo ?
[image]<https://user-images.githubusercontent.com/2284361/224298375-e56916e8-4e5f-4096-b084-fef87eacd391.png>

**Comment by basvanbemmel** [comment]
Zie whatsapp

Verstuurd vanaf mijn iPhone

Op 10 mrt. 2023 om 12:09 heeft Bemmel, van Bas ***@***.***> het volgende geschreven:

﻿ Zie whatsapp

Verstuurd vanaf mijn iPhone

Op 10 mrt. 2023 om 11:55 heeft Maarten Hilferink ***@***.***> het volgende geschreven:

﻿

Probeer al de hele ochtend, wel een deadlock wegens wait op Class count waarvan de bereken thread is verdwenen. Hoe staan jouw MT flags ? Zo ?
[image]<https://user-images.githubusercontent.com/2284361/224298375-e56916e8-4e5f-4096-b084-fef87eacd391.png>

**Comment by MaartenHilferink** [comment]
For 8.7.2 the following causes were found and fixed / mitigated
1. BitVector copy/move inconsistency causing memory corruption
2. GDALRasterBlock corruption after Alt-R with MT2: deinitialisation of GDALComponent avoided, causing more memory leaks but avoiding an access violation

Furthermore, any (other) Windows Structured Exception (SE) causing program termination, such as memory access violations, will now trigger a message box with a simple description of the SE before termination.

**Comment by basvanbemmel** [comment]
Het lijkt goed te gaan in 8.7.2 (nog niet eruitgeklapt)
