### ISSUE TITLE
Ramping in ClassPalette editor fails.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#168]
Scenario: open tst\operator\MicroTst.dms
open in MapView: /BackGroundLayer/district/hoek
layercontrol -> right mouse -> Edit Palette.
Maak BrushColor voor klasse met label 4 Geel
Selct rij 0 ... rij 4 en Ramp Colors:

Check Failed Error: clr <= MAX_COLOR
C:\dev\GeoDMS\shv\dll\src\ShvUtils.cpp(523)

**Comment by mtbeek32** [comment]
![image](https://user-images.githubusercontent.com/24246911/223432633-41b5da0f-7fa3-461a-9c80-ac2d330de2a5.png)

In 7.408 the mentioned scenario still works fine.

**Comment by MaartenHilferink** [comment]
![image](https://user-images.githubusercontent.com/2284361/223435345-45a68c43-d935-439b-a3f3-eaf2abb679ee.png)
This error seems to have been introduces when feature symbols were represented differently with brushcolor => LabelBackGround color and not labeltextcolor; will be fixed in8.7.2

**Comment by MaartenHilferink** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/2284361/223441321-f3a561f6-7eda-4dff-a4f9-3fdd388f1bc5.png)
