### ISSUE TITLE
dms.ttf in subfolder fonts

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#169]
A subfolder fonts is introduced in the installation setup.

It would be nice to move the dms.ttf to this folder.

**Comment by eoudejans** [comment]
In an ongoing effort to make GeoDMS OS agnostic, the choice for a separate software resource folder has my preference. Moving the dms.ttf icons font to this newly created fonts folder is a good idea!

**Comment by MaartenHilferink** [comment]
@eoudejans implemented in v8.7 branch; also the repopulation of the .\misc folder with ROBOCOPY has been fixed. Previous versions (8.7.1) have been distributed with many files missing from .\misc

**Comment by MaartenHilferink** [comment]
(the above mentioned commit was intended to be related to #167)
