### ISSUE TITLE
Export .shp from container without geometry attribute, also write the geometry instead of only .dbf

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#170]
Now when you export an attribute as .shp from a container where the geometry is not explicitly configured. It only writes the .dbf and not also the .shp/.shx/.prj. While GeoDMS already knows the corresponding geometry features (as it can draw them). 

See here for example:

```
container store 
{
	attribute<float32> TransportPerformance (domain)   := TP_g, StorageName = "%LocalDataProjDir%/Results/DestMass.tif";
	attribute<float32> Pop_within_limit1_i  (Prep/Orgs):= ../Pop_within_limit1_i, StorageName = "='%LocalDataProjDir%/Results/Pop_within_'+string(TraveltimeLimit_1)+'min.shp'", StorageType = "gdalwrite.vect";
	attribute<float32> Pop_within_limit2_i  (Prep/Orgs):= ../Pop_within_limit2_i, StorageName = "='%LocalDataProjDir%/Results/Pop_within_'+string(TraveltimeLimit_2)+'km.shp'", StorageType = "gdalwrite.vect";
}
```

**Comment by jipclaassens** [comment]
Operator test:
C:\ProjDir\Jip\_Tools\GeoDMS-Test\Operator\cfg\Issue_GH170.dms

map view op /store/export_this_attr

**Comment by eoudejans** [comment]
Issue reproducible.

**Comment by eoudejans** [comment]
At the moment the behavior is as intended. Only items configured inside the storage container or, depending on the StorageManager, its subcontainers will be exported at the moment. @jipclaassens @mtbeek32 @MaartenHilferink should we change this behavior to work as this issue describes?

**Comment by eoudejans** [comment]
From discussion it follows that in the .shp case geometry should be automatically added, however in the .csv case the geometry should not be taken into account. 

This requires added logic to the interest accounting mechanism for the to-be-written dataitems: 

- Conditionally during update metainfo if the dataitem is mapviewable and is candidate for storage, interest should be added for the found geometry. 
- If the user has configured any dataitem to be stored that is geometry (neither numeric nor string), this should be taken as the geometry of the to be written dataset.

**Comment by eoudejans** [comment]
Implemented in latest commit, see resulting layer of described item in issue by @jipclaassens:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/fcf18321-fe53-4971-882e-7ba634ea351b)

**Comment by eoudejans** [comment]
Confirming that the implementation also works with units:

```cpp
unit<uint32> export_unit := read_shp, 
	StorageName = "%LocalDataProjDir%/export_unit.shp", 
	StorageType = "gdalwrite.vect"
{
	attribute<float32> data := something_happens_here/data_x_2;
}
```

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7c8ae1ef-9b6a-40d1-9b08-2681761f24a0)
