### ISSUE TITLE
Access violation in mapview

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#171]
OVSRV6:
C:\ProjDir\Jip\RSLight2021_ontwikkel_3_issueGH171\Runs\casus.dms
v8.7.2

Mapview of /Analysis/Allocatie/StartState_metBAGnieuwbouw/Wonen/Totaal
Then tableview of same item
Then sort values ascending
Go to biggest negative value
Double click on value, it now starts to recalculate
Then map view of same item
Then click the icon of the 'make extents fit the selected item ...' 

Error: access violation in shv.dll

**Comment by MaartenHilferink** [comment]
Possibly related to #167

**Comment by jipclaassens** [comment]
Other error:

Check Failed Error: sm || this->IsPassor()
C:\dev\GeoDMS\tic\dll\src\Unit.cpp(606):

turn of pallette of several of those layers, but not reproducable

**Comment by MaartenHilferink** [comment]
Fixed in v8.8.0, but related issue arises when compacted domain attr in TableView is selected and then "Show Selected only" is requested.
