### ISSUE TITLE
Check Failed Error: res1Writer.IsEndOfChannel(), bij point_in_all_polygons

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#172]
Check Failed Error: res1Writer.IsEndOfChannel()

OVSRV6:
C:\ProjDir\Jip\RSLight2021_ontwikkel_3_issueGH172\Runs\casus.dms
ctrl+D op /BaseData/Verdeling_VSSH/Uitsmeren_WP2_SocialeHuur/Eengezins/grid_centroid_in_all_panden_rel

![image](https://user-images.githubusercontent.com/48675272/224684703-fa2f5636-59ba-47f6-98ee-04c75d2c97b6.png)

**Comment by jipclaassens** [comment]
C:\ProjDir\Jip\RSLight2021_ontwikkel_3_issueGH172\cfg\RSLight2021\basedata.dms

unit<uint32>           grid_centroid_in_all_panden_rel       := point_in_all_polygons(rdc_5m/point, pand_domain/geometry)
			{
				attribute<rdc_5m>         rdc_5m_rel                := first_rel;
				attribute<pand_domain>    pand_rel                  := second_rel;
			}

**Comment by MaartenHilferink** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/2284361/224780221-41a85655-0b7a-428c-b0dd-8994c5e291b3.png)

**Comment by MaartenHilferink** [comment]
Issue was caused by point_in_all_polygons assuming a UInt32 domain for both the points attribute well as the polygon attribute. Now, any type of domain is allowed (except void).
