### ISSUE TITLE
Check Failed Error: conditionItem C:\dev\GeoDMS\clc\dll\src1\Subset.cpp(248):

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#173]
Na updaten code van subset naar select_many() komen veel rode items, InvalidRecursions en deze error. 
Foutmeldingen zouden informatiever moeten zijn om erachter te komen wat er mis gaat.

OVSRV6:
C:\ProjDir\Jip\RSLight2021_ontwikkel_3_issueGH173\Runs\casus.dms

Openklappen van volgend item geeft alle rode items:
/SourceData/Vastgoed/BAG/PerJaar/y2021/Panden/pand/pand_woon_vbo

**Comment by MaartenHilferink** [comment]
In v8.8.0 is de foutmelding:

Cannot find Item vbo_woon_domein/pand_src_rel
/SourceData/Vastgoed/BAG/PerJaar/Y2021/Panden/pand/pand_woon_vbo 

en upstream bij /SourceData/Vastgoed/BAG/PerJaar/Y2021/Panden/pand/vbo_kwetsbaar_domein:
 "Invalid recursion", similar to #174.

**Comment by MaartenHilferink** [comment]
/SourceData/Vastgoed/BAG/PerJaar/Y2021/:

Panden/pand/pand_met_vbo := select_with_attr_by_cond( pand , pand/count_vbo_pand > 0) 
depends on 

Panden/pand/count_vbo_pand := pcount( vbo_domein/pand_src_rel ) 

VBOS/Src/VBO/pand_src_rel := ... with values unit VBOS/pand_src_domein := Panden/Src ????
defined as rlookup(..., Panden/pand/identificatie)

Panden/pand/identificatie := collect_by_cond (select(pand_src/cond), cond, read(pamnd.fss, identificaties) met domein Panden/pand en niet Panden/pand_src
