### ISSUE TITLE
select_many() invalid recursion issues

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#174]
Enabling/disabling the following attribute results in breaking the project due to invalid recursion. 
/SourceData/Vastgoed/BAG/PerJaar/Y2023/VBOS/Src/pand_vbo_rel

Why?

OVSRV6:
C:\ProjDir\Jip\RSLight2021_ontwikkel_3_issueGH174\Runs\casus.dms

**Comment by MaartenHilferink** [comment]
Reproduction: Alt-R on /SourceData/Vastgoed/BAG/PerJaar/Y2023/VBOS/Src/pand_vbo_rel: red because of 'Unknown identifier 'pand_met_vbo_domein/identificatie'
then go to /SourceData/Vastgoed/BAG/PerJaar/Y2023/VBOS/Src/VBO .... 'Invalid recursion'
