### ISSUE TITLE
gdalwrite.vect doesnt work with for_each_nedvat -construct in 8.8.0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#184]
The native dbf storage manager does work with a for_each_nedva  -construct (so without the 't')
but with the extra 't' and gdalwrite.vect I get the error:

STG Error: Storage Exception = '%LocalDataProjDir%/Planmonitor/KaartPlannenWaarKwetsbaar/'+VarName+'/KaartPlannenWaarKwetsbaarOpp.csv': unknown storage type

GeoDMS 8.8.0
PD 9793 (essential to take this version!) https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3_PlanMonitor2023
SD 9686 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL
demands probably a modelrun with Allocatie map with at least one result : RSLight2021_ontwikkel_3_PlanMonitor2023\Allocatie\WLO_Hoog_BAU\StandY2050\Subsector_rel.tif

Open Casus.dms
Go to:
/Planmonitor2023/Uitlevering/PlannenVariant/BAU/KaartPlannenWaarKwetsbaarOpp

**Comment by basvanbemmel** [comment]
container KaartPlannenWaarKwetsbaarOpp       := for_each_nedvat(OverlayKPlannen/name,
			//container KaartPlannenWaarKwetsbaarOpp       := for_each_nedva(OverlayKPlannen/name,
															'sum(((KaartPlannenWaarKwetsbaar==Planmonitor2023/OverlayKPlannen/V/'+OverlayKPlannen/name+')[float32] * AdminDomain/NrHaPerCell),geography/RegioIndelingen/NL/Per_AdminDomain)[ha]',
															geography/RegioIndelingen/NL,
															ha,
															'gdalwrite.vect',
															"= '%LocalDataProjDir%/Planmonitor/KaartPlannenWaarKwetsbaar/'+VarName+'/KaartPlannenWaarKwetsbaarOpp.csv'"
															//"= '%LocalDataProjDir%/Planmonitor/KaartPlannenWaarKwetsbaar/'+VarName+'/KaartPlannenWaarKwetsbaarOpp.dbf'"
															);

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by MaartenHilferink** [comment]
for_each_nedvat(**N**ame, **E**xpr, **D**omainUnit, **V**aluesUnit, storageN**A**me, storage**T**ype).

Probeer eens argumenten 5 en 6 om te draaien !

**Comment by mtbeek32** [comment]
see also: https://github.com/ObjectVision/GeoDMS/wiki/For_each

**Comment by eoudejans** [comment]
Confirming that swapping arguments solves the issue.

**Comment by eoudejans** [comment]
Closing, assuming issue is resolved.
