### ISSUE TITLE
Apply new naming standard to family of geometric functions

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#185]
For example: the split_partitioned_union_polygon operator generates a nr_OrgEntity

**Comment by MaartenHilferink** [comment]
@jipclaassens Can you elaborate and propose new names ? In casu, for example, 'partition_rel', but for split_polygon: 'polygon_rel', etc.

**Comment by MaartenHilferink** [comment]
Duplicate of #165
