### ISSUE TITLE
export-from-table after group-by, results in a correct domain but in incorrect data

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#188]
steps to reproduce:

repository: https://github.com/ObjectVision/GeoDMS-Test
file: tst\Unit\Other\cfg\table_groupby_export.dms

- request item: /src/div3 in table 
- activate the Group By tool and 
- export the data with the first tool: Copy to Clipboard as semicolon delimited text

**Comment by MaartenHilferink** [comment]
`TableControl::TableCopy` and `TableControl::Export` both call `void TableControl::SaveTo(OutStreamBuff* buffPtr) const
which seems to behave differently than `for(rowNr: tableViewRange) DataItemColumn::GetText(tc->GetRecNo(rowNr)``
