### ISSUE TITLE
Crash value info pointset

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#193]
OVSRV6, v 8.8.1-8.90:
`C:\ProjDir\Jip\geodms_africa_cusa2_issueGH192\cfg\Africa.dms`

Mapview first:
`/Analysis/Abidjan_Ouagadougou/Floods`

Then: 
`/Analysis/Abidjan_Ouagadougou/Indicators/TransportPerformance/Limit_90min_120kmEucl/Pop_within_limit1_i`

Click a point, so you can see the value in the legend.

Then open:
`/Analysis/Abidjan_Ouagadougou/Indicators/TransportPerformance/Limit_90min_120kmEucl/Pop_within_limit2_i`

Then a crash with windows pop OS structured exception.

**Comment by MaartenHilferink** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/2284361/228028435-b8b91ca6-f817-4b61-8102-ca8bca718ab4.png)
