### ISSUE TITLE
GeoDMS version operator not showing version as it should

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#194]
![image](https://user-images.githubusercontent.com/48675272/228180062-29c488fa-2680-4dbd-b7e1-e7d52936c6ea.png)

`parameter<string> GeoDMSVersion            := string(GeoDMSVersion());`

For version 8.9.0, it gives back 8.09.

**Comment by mtbeek32** [comment]
I would suggest three new functions, resulting in uint32 values:
- GeoDMSMajorVersion
- GeoDMSMinorVersion
- GeoDMSPatchVersion

**Comment by MaartenHilferink** [comment]
Implemented: 
- GeoDmsMajorVersionNumber(): UInt32
- GeoDmsMinorVersionNumber(): UInt32
- GeoDmsPatchNumber(): UInt32

**Comment by jipclaassens** [comment]
GeoDmsMinorVersionNumber() gives the major version number.

**Comment by MaartenHilferink** [comment]
Fixed in v11.5.0 (fka 11.11.0)
