### ISSUE TITLE
Add CUSA project to regression test

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#196]
The regression configuration can be found here on OVSRV5:
`C:\SourceData\RegressionTests\prj_snapshots\geodms_africa_cusa2\cfg\Africa.dms`

The following container contains a couple of indicator results that can be compared. 

`/Regressie_test`

Calculation time of all indicators is 45 seconds.

**Comment by mtbeek32** [comment]
Added and is tested in full test for each new version.
