### ISSUE TITLE
Fatal OS structured exception in RSL

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#197]
Ctr+D on:
`BaseData/BAG_nieuwbouw/Verblijfsrecreatie/Totaal`

OVSRV6:
`C:\ProjDir\Jip\RSLight2021_ontwikkel_3_issueGH197\Runs\Casus.dms`

**Comment by MaartenHilferink** [comment]
Fout zat in 
/BaseData/BAG_nieuwbouw/CalcNieuwbouw_perDoel/logies/Nieuwbouw_vbos/Uitsmeren_Totaal/Aantal_Vbos_per_AdminDomain
