### ISSUE TITLE
values unit of collected item using org_rel -> gives no error if not matching.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#199]
If the configured values unit of the collected item does not match with original attribute, no error is given and gives false results! See attribute `/sub/D`

Moreover, attribute `/src/B` gives no real error message.

For example:

```
container Cfg
{
unit<uint32> Kwartalen : nrofrows = 45
{
	attribute<uint32> value        : [201201 ,201204, 201207, 201210
										, 201301 ,201304, 201307, 201310
										, 201401, 201404, 201407, 201410
										, 201501, 201504, 201507, 201510
										, 201601, 201604, 201607, 201610
										, 201701, 201704, 201707, 201710
										, 201801, 201804, 201807, 201810
										, 201901, 201904, 201907, 201910
										, 202001, 202004, 202007, 202010
										, 202101, 202104, 202107, 202110
										, 202201, 202204, 202207, 202210
										, 202301];
	attribute<string> label         := 'Y' + string(value);
}

unit<uint32> NoData: NrOfrows = 1
{
	attribute<uint32> value     := const(0,.);
	attribute<string> Label     : ['NA'];
}

unit<uint32> Kwartalen_nodata := union_unit(NoData, Kwartalen)
{
	attribute<string>   Label        := union_data(., NoData/Label, Kwartalen/Label), DialogType = "LabelText";
	attribute<uint32>   value        := union_data(., NoData/value, Kwartalen/value);
}

unit<uint32> src : nrofrows = 5
{
	attribute<uint32>           A_kw           : [201304, 201210, 201704, 201801, 202207];
	attribute<Kwartalen>        A              := rlookup(a_kw, Kwartalen/value); 
	attribute<bool>             selection_attr := A > 3;
	attribute<Kwartalen_nodata> B              := A;    // should give error, because mismatch of values units.
	attribute<Kwartalen_nodata> C              := 1 * A; //categorical multiplication should be allowed, but then without the 
                                                              categorical values unit. In this case, this should give an error.
	attribute<uint32>                    E              := 2 * A;  //so this should be allowed.
}

unit<uint32> sub := select_with_org_rel(src/selection_attr)
{
	attribute<Kwartalen_nodata> D              := org_rel -> A;
}
}
```

src:
![image](https://user-images.githubusercontent.com/48675272/229497314-e1eb68a4-2ebb-4ddd-bea4-45be0cbea44a.png)

sub:
![image](https://user-images.githubusercontent.com/48675272/229497360-3ca65331-5093-49bd-927b-6f850f385f08.png)

related with issues: #117

**Comment by jipclaassens** [comment]
The result of a union_unit should be catagorical.

**Comment by mtbeek32** [comment]
configuration also available in:
repository: https://github.com/ObjectVision/GeoDMS-Test
configuration file: Unit/Unit/cfg/categorical_test.dms

**Comment by MaartenHilferink** [comment]
> idea: All explicitly configured units with as a [value type](https://github.com/ObjectVision/GeoDMS/wiki/Value-type) of the group: CanbeDomainUnit and for which the cardinality is known or can be known: categorical.

What about:
   unit<uint16> BouwJaar := range(1050, 2300);  ?
Maybe we need an andditional function cat_range for this and let nrofrows = x be replaced by cat_range

**Comment by mtbeek32** [comment]
Source of unit determines if it is categorical or not.

Units with an expression, read from a storage or with a number of rows property are considered categorical, except if the source is:
- a range function
- a base unit function
- no expression

**Comment by basvanbemmel** [comment]
Ik krijg in 9.03 op (het werkt wel in 8.9.1):
/Analysis/Allocatie/Zichtjaren/Y2050/Impl/CalcStand/Subsector_rel

Domain unification of the specified categorical ValuesUnit (/CaseClassifications/StandVar/SubSector : UInt32) with the noncategorical calculation results ( : UInt32) is not possible (different CheckedKeyExpr)
/Analysis/Allocatie/Zichtjaren/Y2050/Impl/CalcStand/Subsector_rel

Context:
1. while in DMS_TreeItem_IncInterestCount( /Analysis/Allocatie/Zichtjaren/Y2050/Impl/CalcStand/Subsector_rel: AbstrDataItem )

Open casus.dms
PD9866:  https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3
SD 9863: https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL

**Comment by basvanbemmel** [comment]
En hebben jullie het bovenstaande nu kunnen reprodcueren?

**Comment by mtbeek32** [comment]
Hoi Bas,

Ik had deze vraag even bij Jip neergelegd omdat hij veel beter in de RS zit.

Ik zal zo even op het werkoverleg vragen naar de status.

Groetjes Martin



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Bas ***@***.***>
Datum: 08-05-2023 07:19 (GMT+01:00)
Aan: ObjectVision/GeoDMS ***@***.***>
Cc: Martin van der Beek ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [ObjectVision/GeoDMS] values unit of collected item using org_rel -> gives no error if not matching. (Issue #199)


En hebben jullie het bovenstaande nu kunnen reprodcueren?

**Comment by basvanbemmel** [comment]
Prima dank

**Comment by jipclaassens** [comment]
@basvanbemmel kun jij dit nog eens proberen met nieuwe basedata en variantdata? (lees; gegenereerde base/variantdata in een geodms 9 versie)

**Comment by basvanbemmel** [comment]
Ik heb opnieuw gegenereerd het lijkt nu inderdaad wel te werken.

**Comment by basvanbemmel** [comment]
Overigens in PD9712 is in Geography.dms iets gewijzigd waardoor cfg niet meer in te lezen is in exe 8.6.5 en lager.
Je krijgt dan:

Unknown property 'SpatialReference'
k:/pd/rslight2021_ontwikkel_3/cfg/RSLight2021/Geography.dms(6,94) at
    unit<fpoint> rdc_meter_base   : DialogData = "ngr_layer", SpatialReference = "EPSG:28992";
    unit<fpoint> rdc_meter_base   : DialogData = "ngr_layer", SpatialReference = "EPSG:28992"^
k:/pd/rslight2021_ontwikkel_3/runs/casus.dms(20,55) at
    #include <%projdir%/cfg/RSLight2021/Geography.dms>
    #include <%projdir%/cfg/RSLight2021/Geography.dms>^

Context:

1. while in AppendTreeFromConfiguration::casus.dms
2. while in DMS_CreateTreeFromConfiguration::casus.dms

**Comment by jipclaassens** [comment]
Klopt, de Format property naam is veranderd in SpatialReference.
