### ISSUE TITLE
By window resize, dont change the zoom scale

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#200]
keep zoom scale constant, but change the rectangle of interest.

**Comment by MaartenHilferink** [comment]
Why is this desired ? 
For scenario's I can think of, it is not:
- opening layer for a country in a tiled of cascaded MDI child window, then maximize: country will be shown small somewhere in the middle or the top-left corner
- opening layer for a country in a maximized MDI child window, then tile, cascade or resize MainWindow:  country will be clipped and shown partially (Center or North West region)

**Comment by MaartenHilferink** [comment]
conclusion: won't fix.
