### ISSUE TITLE
ClassifyNonzeroEqualCount

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#201]
### Discussed in https://github.com/ObjectVision/GeoDMS/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **jipclaassens** January 11, 2023</sup>
![image](https://user-images.githubusercontent.com/48675272/211804506-1e155d8b-0ff5-48b2-af78-6a9c941ece7c.png)
</div>

**Comment by MaartenHilferink** [comment]
Also implemented: ClassifyNonzeroEqualInterval

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/55718828-45e4-4ee8-ba7c-cf36cd2a33e8)
