### ISSUE TITLE
Tiling information in detailpage as summary-details block, and fss regular tiling

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#202]
Domain information, if domain is from FSS.

![image](https://user-images.githubusercontent.com/48675272/230094096-77788261-c14b-4f39-b3c1-ef41c9d7bb89.png)

OVSRV6:
`C:\ProjDir\Jip\NetworkModel_EU_issueGH202\cfg\main.dms`
`/SourceData/Infrastructure/TomTom/Read_Streets_fss_selection`

**Comment by jipclaassens** [comment]
FYI: Still issue in 14.1.0

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/a4061784-458a-47e4-93e4-581efc499a7e)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/24284e8d-cf93-4ad8-ba4f-d9dea04e2465)

**Comment by jipclaassens** [comment]
#112

**Comment by eoudejans** [comment]
- [ ] irregular tiling as summary - details
- [ ] recognize regular tiling for fss

**Comment by MaartenHilferink** [comment]
Implemented in v152 tilesizes in summary and details:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a462755e-20bf-4696-88f4-c546c2d452aa)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/49f1b750-8004-41fa-8968-b015a9b3076c)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d4f45e97-3d8a-4e75-a358-aae5c9f97864)

**Comment by MaartenHilferink** [comment]
The loading of tiling data from an fss should be tested for RS reading domain data from an FSS, such as the presented in the issue.

**Comment by MaartenHilferink** [comment]
The loading of tile data from an fss has here been demonstrated to convert to a regular tiling:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/75c25200-3e8d-44a4-a611-8f8b3a6897e7)
