### ISSUE TITLE
Let go of value trace in detailpage 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#204]
I would like the option to let go of the value trace in the detail page. 

If I have multipe feature layers in the map view, and I am tracing the value info in the detailpage. Switching between layers trigger the value trace again and again. I would like to option to stop the value trace. Now the only way is to alt+R, and restart the the calculation without the value info trace.

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\NetworkModel_EU_issueGH204\cfg\main.dms`

For example, add to the map view:
```
/NetworkSetup/NetwerkSpec/CreateMoreEfficientNetwork/LinkSet/Impedance
/NetworkSetup/NetwerkSpec/CreateMoreEfficientNetwork/FinalLinkSet/Impedance
/NetworkSetup/NetwerkSpec/CreateMoreEfficientNetwork/LinkSet/IsPartOfJunctionFreeSection
/NetworkSetup/NetwerkSpec/CreateMoreEfficientNetwork/LinkSet/IsInsideJunctionFreeSection
```

Then double click on an arc in the map, it initiates the value trace.
Then disable and enable the various layers. Each time it triggers the value trace. Which could be intended. But what if I don't want the value trace anymore, but just exploratively want to turn on and off the layers?

**Comment by MaartenHilferink** [comment]
Value trace should not be triggered by disabling nor enabling layers. If you intend to get such value trace, you can (double) click on its value widget.
