### ISSUE TITLE
constants in select_with_attr_by_cond results in error

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#206]
an expression like:

<pre> select_with_attr_by_cond(src, const(true,src))</pre>

results in an error for subitem generated, with a collect_by_cond expression.

steps to reproduce:  

1. repository: https://github.com/ObjectVision/GeoDMS-Test
2. file: tst\Unit\Operator\cfg\true_function_in_select_by_cond.dms
3. request item: /sel/id in table view

Additional information: /sel_using_att/id works fine.

**Comment by MaartenHilferink** [comment]
x was replaced by x() during parsing for x in {true, false}; this is now moved to the substitution phase and x remains parsed as an identifier until then.

**Comment by mtbeek32** [comment]
Issue tested and works fine in 9.0.3. Test added to unit test.
