### ISSUE TITLE
Foutmelding verbetering bij schrijven grid domain met gdal.vect

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#220]
storage type = gdalwrite.vect
storage name = xx.tif

geeft geen duidelijke error

**Comment by eoudejans** [comment]
Scenario reproducible. Using .tif as extension and internally the gdal open flag to restrict drivers to GDAL_OF_VECTOR results in an error at GDALDataset creation. The current error is as follows:

![gdal_write_error_improvement_1](https://github.com/ObjectVision/GeoDMS/assets/96182097/61996962-1686-4cc1-9746-fcdfb6ec7a49)

**Comment by eoudejans** [comment]
For this specific scenario, in case the GDALDataset was not created succesfully the found driver's capabilities are tested to support the GDAL_OF_RASTER in case of gdalgrid.write and GDAL_OF_VECTOR in case of gdalvect.write. A specific error message is thrown in case this test fails.
Proposed new error message is as follows:
![gdal_write_error_improvement_2](https://github.com/ObjectVision/GeoDMS/assets/96182097/0deccf35-b07f-458d-9f4a-3b985d9a337e)
