### ISSUE TITLE
DMS views: reconsider window naming for Mapview, for instance EPSG code in MapView Title

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#221]
The current title of a map view is someting like: 

1 recs in MapView geometry

Could we add the EPSG code used for the coordinates to this title

**Comment by MaartenHilferink** [comment]
Qt: first restore DataView titles from Delphi, also for the MainWindow

**Comment by eoudejans** [comment]
Further specification required for implementation.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/28f223b7-35db-474d-933a-b0c011266539)
