### ISSUE TITLE
Crash ImGUI when error in disc_alloc

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#223]
map view op /Output_Attributes/Run2_NHIModelType

OVSRV6:
C:\ProjDir\Jip\_Github_issues\Delta_Scenarios_2023_issueGH223\cfg\stam.dms

**Comment by eoudejans** [comment]
Reproducibility confirmed. Tableview works, Mapview results in crash.

**Comment by eoudejans** [comment]
Error resulted in a structured exception, which is likely incorrectly handled by the geodms imgui implementation as of now.

![Capture](https://github.com/ObjectVision/GeoDMS/assets/96182097/b7460610-4525-493f-a82a-e72e00f257df)

**Comment by eoudejans** [comment]
Structured exceptions are not caught at the moment. Macros to be used are:
DMS_SE_CALL_BEGIN
DMS_SE_CALL_END
In DmsCatch.h line 80.

**Comment by eoudejans** [comment]
Solved in commit https://github.com/ObjectVision/GeoDMS/commit/f12e2bf96534ada9bb30429ae1b76d6b265b1d94 . Added structured exception try-catch macros.
