### ISSUE TITLE
modus in grid NL 5 * 5 meter to 25 * 25 meter results in unknown software exception

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#224]
Steps to Reproduce

Repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration: grid\cfg\modus_large_grid.dms
Request item: /m25/GridData in table view

Results in error as shown:
 
![modus_large_grid](https://github.com/ObjectVision/GeoDMS/assets/24246911/14ff7c8d-0fb5-4b0a-b0e7-f78164cbe5dd)

**Comment by MaartenHilferink** [comment]
modus(xxx, id(.)[rdc25m]):

1. memory error handling: difficult to improve; requires better ex ante planning of resource usage
2. workaround: use modus(xxx, mapping(., rdc25m)
3. specific memory usage mitigation: consider how tile consumption by modus and similar operations can be delayed until after DataReadLock to avoid caching realised tiles

**Comment by mtbeek32** [comment]
An extra 25Gb RAM memory is used if a Tiff Storage is configured for the modus results, see commit of grid\cfg\modus_large_grid.dms of 23 may 2023.

**Comment by mtbeek32** [comment]
Issue with extra RAM if Toff StorageManager is configured is solved
