### ISSUE TITLE
nrofrows is presented as range in configuration detail page

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#228]
Steps to reproduce:

repository: https://github.com/ObjectVision/GeoDMS-Test
configuration: tst/other/cfg/nrofrows_detailpage_config.dms
request detail page [Configuration] for item: Class

This becomes more an issue, as nrofrows and range result in different behavior (categorical versus non-categorical)

**Comment by MaartenHilferink** [comment]
In 10.0.2: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/8fc69f1a-6e97-4d62-8b7f-db778d3cbace)

**Comment by MaartenHilferink** [comment]
In Qt: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ce6bd75b-4f81-4b23-8059-8299914c10c0)

**Comment by MaartenHilferink** [comment]
Now dp.configuration looks Oke as well in Qt:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e034d103-888b-4ef8-8c98-08ba8be82915)
