### ISSUE TITLE
Invalid recursion when reading a tif with geodms grid in geodms 10

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#229]
/SourceData/Grondgebruik/Basisjaar/NHIModelType25To100m/Read_Result_100m

adding storagetype="gdal.grid" fixes it.

<HTML><HEAD></HEAD>
<BODY bgColor=#ddd2d0>
<TABLE>
<TBODY>
<TR>
<TD>Invalid recursion in TreeItem::GetCurrMetaInfo() detected.<BR>Check calculation 
rule of this item</TD></TR></TBODY></TABLE></BODY></HTML>

OVSRV6:
C:\ProjDir\Jip\_Github_issues\Delta_Scenarios_2023_issueGH229\cfg\stam.dms

**Comment by MaartenHilferink** [comment]
Unable to reproduce with 10.0.1 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0d0efda7-6aa8-407c-b695-ded2044e3779)

**Comment by MaartenHilferink** [comment]
Fun fact: in debugger it works even after Alt+R
