### ISSUE TITLE
Crash op wegschrijven naar tif

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#230]
dubbelklik op: 
/SourceData/Natuur/NVK/BAU/BaUdiff_BT/Val_Rel

OVSRV6:
C:\ProjDir\Jip\_Github_issues\RSLight2021_ontwikkel_3_issueGH230\Runs\casus.dms

**Comment by eoudejans** [comment]
Reproducibility confirmed on OVSRV07.

**Comment by eoudejans** [comment]
Problem is most likely caused at time of writing, where the EPSG:28992 projection definition was mangled as can be seen from the warnings produced by GeoDMS crs consistency check:
![gdal_grid_write_proj_error](https://github.com/ObjectVision/GeoDMS/assets/96182097/c537fdfa-693f-40e7-9822-73ed54035a36)

**Comment by eoudejans** [comment]
Consequently proj is not able to produce a converter between the dataset projection and EPSG:28992, which results in the dataset being incorrectly read.

**Comment by eoudejans** [comment]
The projection is, on second thought, correctly interpreted, data can be read. The steps after reading try to write a grid with values unit uint64 to tiff. This is unsupported at time of writing.

**Comment by MaartenHilferink** [comment]
Issue is also reprodible without writing to a tiff file:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e429fd16-616d-4d1a-9c79-9d7e77525e66)

**Comment by MaartenHilferink** [comment]
In debug:	
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7d5a6a66-96aa-4875-8345-4a800f8b5218)
indicating data missing for 	unit<uint64> Valunique := unique(BaUdiff_BT/data)

**Comment by MaartenHilferink** [comment]
After last commit, issue is resolved for case without gdalwrite.grid storage, but persists with gdalwrite.grid storage: Crash without error message.

**Comment by MaartenHilferink** [comment]
Crash is fixed. Error now is: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ab824dd0-4993-41d7-a70c-ed7c4e21aff1)

**Comment by MaartenHilferink** [comment]
when using the TIF storage manager, the error msg now is:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7d3ae3b5-76f1-49b5-8a42-d657022c64bb)
I will enable writing (U)Int64 data as Float64 data now, but gdalwrite.grid still has to catch up with these.

**Comment by MaartenHilferink** [comment]
With gdalwrite.grid: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a1c9d797-c193-4757-999f-446b511617b6)

**Comment by MaartenHilferink** [comment]
Crash is fixed now. Follow up issues, see: 3236
