### ISSUE TITLE
crash op combine_unit_uint64/accu_pop door arrow operator

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#231]
OVSRV6:
C:\ProjDir\Jip\_Github_issues\geodms_africa_cusa2_issueGH231\cfg\Africa.dms

Openklappen van:
/Analysis/Praia_Dakar_Abidjan/Indicators/proximity/Combine_OrgDest

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4584bc36-e4b0-4a8b-a348-ab2f3075315e)

**Comment by MaartenHilferink** [comment]
Unable to reproduce with 10.0.01:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/1a98ed03-342f-414e-a181-727b9d0e2e96)
