### ISSUE TITLE
Main Menu options (File, Edit, View, Tools, Windows and Hel

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#234]

**Comment by MaartenHilferink** [comment]
actions that are included in both the MainMenu->View and the popup-menu shoud be added to a menu by calling a function in order to reduce redundancy, especially for the options MapView, TableView, and DefaultView.

**Comment by MaartenHilferink** [comment]
File-> Export Primary Data forms
File->recent files after separator

**Comment by MaartenHilferink** [comment]
Use OnCommandEnable mechanism to check for eligibility of Export Primary Data options for current item

**Comment by MaartenHilferink** [comment]
Window met opties: Tile, Cascade, Maximize, Close, Close all, Close All but this, separator, list met current DataView captions

**Comment by eoudejans** [comment]
> actions that are included in both the MainMenu->View and the popup-menu shoud be added to a menu by calling a function in order to reduce redundancy, especially for the options MapView, TableView, and DefaultView.

MapView, TableView and Default view QActions are now single source, owned by MainWindow.
