### ISSUE TITLE
GDalwrite.grid doesn't support writing (U)Int64 data.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#236]
See issue #230. 
1. Report on writing or reading non-supported value types.
2. recast (U)Int64 as Float64; find ways to read any element with a fixed no-of-bits <= 64

**Comment by eoudejans** [comment]
@MaartenHilferink I will create the requested testcase.

**Comment by eoudejans** [comment]
Furthermore, GdalDrivers have populated either GDAL_DMD_CREATIONDATATYPES for raster drivers or GDAL_DMD_CREATIONFIELDDATATYPES and possibly GDAL_DMD_CREATIONFIELDDATASUBTYPES for vector drivers. This can be used to check driver for capability of write a specific values unit to storage before writing, and throw an error.

**Comment by eoudejans** [comment]
Gdal write dms to gdal values unit type check is now implemented. Only when the driver supports the given gdal values unit, converted from the dms value unit, writing commences. See:

![gdal_write_values_unit_dms_gdal_compatibility_check](https://github.com/ObjectVision/GeoDMS/assets/96182097/7dc35c76-557a-4c99-aaf9-c464c9dc07c8)

**Comment by eoudejans** [comment]
Write testcase added to GeoDMS_Test project to gdal regression.dms item /Tiff/write/export/grid_uint64/GridData

**Comment by eoudejans** [comment]
We have implemented checks to compare the dms value type to gdal driver supported value types and implemented a write check for (u)int64 type tif. This should be sufficient for now, we can always reopen to research and implement @MaartenHilferink's option 2) if it becomes a necessity.
