### ISSUE TITLE
outer_polygon and outer_multi_polyon results in polygon with zero coordinates

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#238]
Steps to reproduce:

repository: https://github.com/ObjectVision/GeoDMS-Test
configuration: tst\operator\cfg\operator.dms
request item: sequence/UnTiled/outer_polygon_lake_island/att & sequence/UnTiled/outer_polygon_lake_island/att in table, both have zero coordinates

**Comment by jipclaassens** [comment]
This operator could be very useful for this project
https://github.com/ObjectVision/BegrenzingBebouwdGebied

**Comment by mtbeek32** [comment]
Simple variant with only a square also result in empty polygon:

repository: https://github.com/ObjectVision/GeoDMS-Test
configuration: tst\operator\cfg\operator.dms
request item: sequence/UnTiled/outer_multi_polygon_square/att & sequence/UnTiled/outer_multi_polygon_square/att in table, both have zero coordinates

**Comment by MaartenHilferink** [comment]
Fixed !


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/97c96306-dd5b-4b62-8036-85db6f3b39e6)

**Comment by mtbeek32** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/a2d6ead2-8763-4c0b-b6d8-61dbd3b03a0c)

in het mooie Brabant gaat het nog niet helemaal goed. Na vervangen opnieuw de ringen controleren.
