### ISSUE TITLE
Unnecessary redrawing from WM_NCLBUTTONDOWN leading to QExposeEvent.

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#239]
To reproduce set a breakpoint in DmsTreeview data() at displayrole and drag the window using left mouse from the application title bar.
Dragging the whole dms window causes WM_NCLBUTTONDOWN to lead to expose events in qt.

See:
Expose  https://doc.qt.io/qt-5/qexposeevent.html#details

And callstack:
![expose_event_left_mouse_dragging](https://github.com/ObjectVision/GeoDMS/assets/96182097/bbff8a4b-a9e2-40e5-b01f-d20471a68775)

**Comment by MaartenHilferink** [comment]
This issue results in invalidating -> redrawing TreeView, and DataViews when:
- Appl is Activated
- Appl is moved (dragged by the Appl title bar)
- MdiSubWindows is moved (dragged by the SubWindow's title bar)
- DetailPageSlider is moved (even for locationally unaffected Views)

**Comment by MaartenHilferink** [comment]
https://chat.openai.com/c/5667a506-1780-46ea-a719-19904a104177

**Comment by MaartenHilferink** [comment]
https://stackoverflow.com/questions/1133507/is-there-a-function-like-peekmessage-that-doesnt-process-messages#:~:text=GetQueueStatus%20is%20the%20fastest%20way,the%20message%20in%20any%20way.

We have:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/3985ef8c-ad04-43ff-8470-9ac33ce1ea70)
but it seems that GetQueueStatus doesn't prevent the app to go into "(does not respond)" mode, causing an Activation and consequently to this issue an invalidation-> repaint event upon completion. PeekMessage here did and probably does keep the app "responsive" according to windows and therefore prevents the painting loop, but that has the disadvantages as explained in this SO thread.

**Comment by MaartenHilferink** [comment]
Background discussion: https://chat.openai.com/share/12420724-2055-4cf5-bb4b-4a5ed06ee771
