### ISSUE TITLE
Qt: Multiple views are drawn overlapping

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#240]
![Image](https://user-images.githubusercontent.com/2284361/244431587-31b7e866-e8d1-41c8-800c-49173c907b76.png)

**Comment by MaartenHilferink** [comment]
QDmsViewArea Widget inside QMdiSubWindow contains a DataView with separate HWindow, which is clipped by sibbling windows with higher z-order (such as the 'test' window is clipped by the 'norm' window), but not by sibbling non-window widgets, such as the border drawing parent of QDmsViewArea, which is a QMdiSubWindow.

Possible solution: make border of the QMdiSubWindow part of the HWindow of the DataView and suppress Qt's border drawing, but how would that interfere with QMdi
No regret action: Make QDmsViewArea a subclass of QMdiSubWindow, then we save a layer of componentisation and can easily fix the moveEvent processing for at least the MdiChild moves; remaining issue: moves of the QMdiArea origin.

**Comment by MaartenHilferink** [comment]
partial solution resulting in: 

![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/fa164028-e7ae-45b0-b6e1-eb8df6d1d80c)

**Comment by eoudejans** [comment]
All qwidgets are now native, dms view can now be a child hwnd of the mdiview area, which solves the z-ordering.
