### ISSUE TITLE
File->recent files after separator

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#247]
Follow up on #234

**Comment by eoudejans** [comment]
Implemented from commit https://github.com/ObjectVision/GeoDMS/commit/7e8b661c4ec1e70b2ff5ce60221bed4319f4c366. See:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7ede56ce-35e3-46bb-a83d-72e956d6c956)
