### ISSUE TITLE
Add export primary data functionality (implementation from imgui)

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#251]

**Comment by eoudejans** [comment]
Implemented imgui export primary data implementation. See:
![export_window](https://github.com/ObjectVision/GeoDMS/assets/96182097/0d88890f-f12b-46f9-a67c-34f6f9852b96)

**Comment by eoudejans** [comment]
Implemented from commit https://github.com/ObjectVision/GeoDMS/commit/66a303bcda90203e528f4dab7a98ad112f3aa156
