### ISSUE TITLE
Tools -> GUI Style Options ; Advanced Options; Configuration Options

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#252]

**Comment by eoudejans** [comment]
Options windows moved to separate code units.
Implemented placeholders for gui options and config options dialogues.

See gui options window:
![gui_options_window_placeholder](https://github.com/ObjectVision/GeoDMS/assets/96182097/f6f19e08-34af-4772-b6e0-fa9643f8b129)

**Comment by eoudejans** [comment]
Gui options to be stored in current user registry, advanced options to be stored in local machine.

**Comment by MaartenHilferink** [comment]
Delphi code for reading and initializing GUI colors:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/2748fed2-8d0e-4f72-b6f7-4bbc94d84eee)

**Comment by MaartenHilferink** [comment]
// Register settings in <dmGeneral.pas> 
    m_nStatus: Integer;
    m_sStrings: array[0..SRI_Count-1] of string;
    m_nNumbers: array[0..NRI_Count-1] of Integer;

Initialisation status and strings for Advanced options:

  m_sStrings[SRI_LastConfigFile]  := '';
  m_sStrings[SRI_HelpUrl       ]  :='https://www.geodms.nl/GeoDMS';
  m_sStrings[SRI_DmsEditor     ]  :='"%env:ProgramFiles%\Notepad++\Notepad++.exe" "%F" -n%L';
  m_sStrings[SRI_LocalDataDir  ]  :='C:\LocalData';
  m_sStrings[SRI_SourceDataDir ]  :='C:\SourceData';

  try
    with TDmsRegistry.Create do
    try
      if OpenKeyReadOnly('')
      then try
        for i:=0 to SRI_Count-1 do
           if ValueExists(SR_Names[i]) then
           begin
             regString := ReadString(SR_Names[i]);
             // discard stored old default helpUrl, see issue 199
             if (i <> SRI_HelpUrl) or (regString <> 'http://wiki.objectvision.nl/index.php/GeoDMS') then
                m_sStrings[i] := regString;
           end;
        for i:=0 to NRI_Count-1 do
           if ValueExists(NR_Names[i]) then m_nNumbers[i]  := ReadInteger(NR_Names[i]);
      finally
        CloseKey;
      end;
    finally
      Free;
    end;
  except on E: Exception do
    AppLogMessage(E.ClassName + ': '+ E.Message);
  end;
  SHV_SetAdminMode(AdminMode);

**Comment by MaartenHilferink** [comment]
Opslaan status en strings:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/db9269ba-fb7c-49be-aaa2-bba9e92ba718)

Naar Users/Machine specific registry location:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9109faaf-5410-4921-bfe7-9df1b5417df4)
