### ISSUE TITLE
Data read from configuration file is presented as a different value in tableview

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#254]
Repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration: operator/cfg/operator.dms
Request item: Arithmetics/srcDomain/A in TableView

See screendump: Third element in item A is -2, presented in table as -1.

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/546dfd82-dce6-4908-9397-f185319bc4b7)

**Comment by MaartenHilferink** [comment]
Issue was caused by changes for #244
