### ISSUE TITLE
Treeview: make dms root also visible and interactable treeitem.

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#258]

**Comment by eoudejans** [comment]
Alternative for root item visibility, in view menu: all items -> submenu -> expand, update, etc..

**Comment by MaartenHilferink** [comment]
I'll implement the View menu route in order to evaluate this alternative

**Comment by jipclaassens** [comment]
Already implemented?

**Comment by eoudejans** [comment]
Implemented as action in menu.
