### ISSUE TITLE
Disc_alloc gives mixed up value types

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#267]
OVSRV6:
C:\ProjDir\Jip\_Github_issues\Delta_Scenarios_2023_issueGH267\cfg\stam.dms

First generate once:
/SourceData/Grondgebruik/BBG/Dominant/Make_per_5m/CBSKlasse_rel_2017

Then, map view of:
/SourceData/Grondgebruik/BBG/Dominant/Make25mgrids_allocation/J2017/Result_discrete

**Comment by MaartenHilferink** [comment]
Issue is likely caused by not using SpatAggr as intended. In affected locations West of The Haye, no land use type has a suitability > 0, which allows for these deviation.
Possible solutions/mitigations:
1. Define CompactedDomain as only those locations that have any per_5m/jxxxx defined.
2. use MakeDefined(/SourceData/Grondgebruik/BBG/Dominant/per_5m/Jxxx, 0) in the suitabiltiy definitions.

**Comment by MaartenHilferink** [comment]
Ad 2: gg.dms: 

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/6435766e-c851-49d0-b53e-fd67fb52f00d)

geeft:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/f05a81c3-69d6-425f-ad0a-d6a33dff9688)

**Comment by MaartenHilferink** [comment]
container Input
	{
		unit<uint8> AggRegio := Geography/RegioIndelingen/Corop;
		
		attribute<LandUsePreparation/CBSKlasse> lu_per_5m_raw(rdc_5m) := ='per_5m/j'+string(year);
		attribute<LandUsePreparation/CBSKlasse> lu_per_5m_cln(rdc_5m) := MakeDefined(lu_per_5m_raw, LandUsePreparation/CBSKlasse/V/oorspronkelijk_nodata);
		
		container Compacted
		{
			unit<uint64> ADomain := subset(IsDefined(AggRegio/per_rdc_25m))
			, DialogType = "Map", DialogData = "BaseGrid";
			
			attribute<ADomain> BaseGrid (rdc_25m) := invert(ADomain/nr_OrgEntity);
					
			container Suitability := for_each_nedv(LandUsePreparation/CBSKlasse/name
					, 'value(sum_uint8(lu_per_5m_cln == LandUsePreparation/CBSKlasse/V/'+LandUsePreparation/CBSKlasse/name+', rdc_5m/rdc_25m_rel)[ADomain/nr_OrgEntity], int32)'
					, ADomain, int32
				);
				
			attribute<AggRegio> AtomicRegionMap (ADomain) := AggRegio/per_rdc_25m[ADomain/nr_orgEntity]
			{
				attribute<AggRegio> id (AggRegio) := id(AggRegio);
			}
		}
		
		container Claims
		{
			container maxclaims := 
				for_each_nedv(
					  LandUsePreparation/CBSKlasse/name
					, 'sum_uint32(lu_per_5m_cln == LandUsePreparation/CBSKlasse/V/'+LandUsePreparation/CBSKlasse/name+', AggRegio/per_rdc_5m)'
					, AggRegio
					, uint32
				)
			{
				attribute<uint32> Totaal (AggRegio) := = 'add('+AsItemList(LandUsePreparation/CBSKlasse/name)+')';
			}
			
			container minclaims := 
				for_each_nedv(
					  LandUsePreparation/CBSKlasse/name
					, 'const(0, AggRegio)'
					, AggRegio
					, uint32
				);
		}
	}
