### ISSUE TITLE
Qt: Config files changed: files without LFCR breaks

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#269]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d151a305-2b18-44dd-888f-00364a37ceab)

**Comment by eoudejans** [comment]
Changed sourcefiles will now be separated by linebreaks, see:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/1a512a77-09c5-4526-8de8-034d68457aec)
