### ISSUE TITLE
Qt: calc time in statusbar

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#270]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/310627be-0637-46fe-99eb-1879eb240a2b)

**Comment by MaartenHilferink** [comment]
En een MessageBeep wanneer er (na meer dan 5 sec) weer idletime is aangebroken,.

**Comment by eoudejans** [comment]
Longest time till now is fine as is, but as feature request: it would be great if this could be reset.
For instance running an item takes 30minutes, the follow-up item takes less time, but how much exactly? 10minutes, 20 minutes?

**Comment by eoudejans** [comment]
@MaartenHilferink: functionality in Borland was working well, how should we transfer this to qt?

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/8db24011-a7ba-422b-8ceb-74216f340730)
