### ISSUE TITLE
Geen multi-threading op parallelle sums

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#275]
OVSRV6:
C:\ProjDir\Jip\_Github_issues\Delta_Scenarios_2023_issueGH275\cfg\stam.dms

In nieuwe GUI
Table view op: 
/SourceData/Grondgebruik/BBG/Dominant/Make25mgrids_allocation/J2017/Input/Claims/maxclaims

**Comment by MaartenHilferink** [comment]
Cannot reprodiuce:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4f8bef27-de72-42ef-b03d-a4b3e9fa7f41)

**Comment by jipclaassens** [comment]
Seems to be fixed
