### ISSUE TITLE
Close subwindows with ctrl + W

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#279]
This works in old GUI and many windows applications

**Comment by MaartenHilferink** [comment]
I used Ctrl-F4, both should work.

**Comment by eoudejans** [comment]
Various actions are now made available application wide, using QAction::setShortcutContext(Qt::ApplicationShortcut);.
Remaining issue: when dms dataview has key focus, application wide shortcuts don't work yet.
