### ISSUE TITLE
Reading large .tif is very slow with high memory consumption, much higher than QGIS

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#285]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\TowardsAnUrbanPreview_UrbanDensity_issueGH285\cfg\stam.dms`

Map view on:

`/Preprocessing/Urban/BuiltUpPresence_R2023_Create/Y1975/big_raster/GridData`

However, QGIS might be using pyramids. Even though the .ovr files have been deleted.

**Comment by MaartenHilferink** [comment]
Usage of pyramids would result in applying different calculation rules for visualizing results on different scales. We don't want to follow that road, at least not in this decade.

64 gigapixel x 2 bytes/pixel = 128 GB, to be classified by JenksFisher classbreaks to a resulting UInt8 palette index, thus 64 GB. The latter is stored and not lazily calculated to avoid reclassification. So the 64 GB seems quite reasonable.

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/b6a21fdf-8dc1-474e-8b6c-9569554ba2dd)

However, when the classification was materialized in a mapping from all UInt16 to UInt8 (by classify(id(range(0, 65534)), classbreaks) and used as lookup, only 64 KB needed to be stored.

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7a51120b-0327-4d28-bf2f-004bb0eb3fbc)
