### ISSUE TITLE
Add key binding to Code Analysis > Add target

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#289]
When checking a configuration for unused items, you have to select many final attributes. With the chance of clicking the wrong context menu option and having to start over. A key binding would be very convenient. 

I am not sure with bindings are still unused and suitable for this use? 
Alt + K
Alt + B
Alt + N

In QT the context option is also gone.

**Comment by eoudejans** [comment]
Implemented, see:
![hotkeys_for_code_analysis](https://github.com/ObjectVision/GeoDMS/assets/96182097/1627ee42-1dae-4f08-bf5f-d2a1b133a616)
Closing issue.
