### ISSUE TITLE
runtime error in Delphi GUI after Update Subtree 

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#291]
Steps to reproduce:

- repository: https://github.com/ObjectVision/GeoDMS-Test
- configuration: operator\cfg\MicroTst.dms
- Item: BackGroundLayer > Pop-up menu item: Update Subtree

results in a cascade of runtime errors.

**Comment by MaartenHilferink** [comment]
https://www.freepascal.org/docs-html/3.0.2/user/userap4.html

**Comment by MaartenHilferink** [comment]
Fixed in 11.3.1
