### ISSUE TITLE
GDAL BMP driver tries to append to dataset instead of creating a new dataset.

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#296]
For example in gdal regression.dms:
/bmp/write/export/nl_lu_2010/GridData

And exporting primary data via right-mouse context menu from new qt gui.

To be investigated.

**Comment by eoudejans** [comment]
There is a difference in behavior between exporting to vector and raster data in this scenario.
Vector data will branch to the WriteDataItem whereas raster data will branch to UpdateMetaInfo.
Raster callstack:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/0be92e9a-4cb7-4843-9b5a-8d7296eb9c86)
Vector callstack:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/548294fb-68f2-4644-a0f0-1039547e7ee0)

**Comment by MaartenHilferink** [comment]
Fixed by skipping UpdateTree for gdalwrite.grid and gdalwrite.vect storage managed items; possibly still an issue for other storage managers where write-only cannot be easily derived from storagetype and StorageReadOnly not being set. See code marked with #352
