### ISSUE TITLE
Crash op connected_parts

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#3]
OVSRV6
C:\ProjDir\Jip\NetworkModel_EU_issueGH3\cfg\main.dms

ctr+D op /SourceData/Infrastructure/Read_Final_Network/Opschoning/ConnectedParts/PartNr
geeft crash

**Comment by MaartenHilferink** [comment]
Reproduction:

First, go to /SourceData/Infrastructure/Prepare_SourceData/Make_Roads_fss and press Ctrl-D
then go to /SourceData/Infrastructure/Read_Final_Network/Opschoning/ConnectedParts/PartNr and press Ctrl-D
=> GeoDmsGui.exe disappears.

**Comment by MaartenHilferink** [comment]
Fixed in v8.6.3
