### ISSUE TITLE
Fatal OS Struc... the thread used up its stack

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#300]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\RSLight2021_ontwikkel_3_issueGH300\Runs\casus.dms`

Openklappen van deze container:
`/BaseData/AlternatieveLISA/Performance/OLS/OLS`

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ba0735f6-d455-42e7-8988-1e11f3482501)

**Comment by MaartenHilferink** [comment]
Fixed in 11.4.2

**Comment by MaartenHilferink** [comment]
Current error is understandable when looking at the definition of X:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e3b5bd14-1b64-41e5-b00f-8aec90727963)
