### ISSUE TITLE
use OGRCoordinateTransformation in parallel from multiple threads producing data for mapping and/or coordinate conversions

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#304]
currently, proj4 calls are synchronised and (lazy) tile requests on different threads are not processed in parallel.
See: https://proj.org/en/9.2/development/reference/datatypes.html#c.PJ_CONTEXT

How to specify a PJ_CONTEXT in the construction of the used object:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e3d66c77-c103-438a-8414-f21d004b5717)

**Comment by MaartenHilferink** [comment]
See also:
- #298 
- https://chat.openai.com/share/bd3abd5c-85d7-4a80-be52-90207efb3eac (laatste code snipper, vervang proj_context door pj_ctx)

**Comment by eoudejans** [comment]
> See also:
> 
> * [optimize mapping(D, V) for coordinate families that are coordinate separable transformations by storing transformed x and y values separately. #298](https://github.com/ObjectVision/GeoDMS/issues/298)
> * https://chat.openai.com/share/bd3abd5c-85d7-4a80-be52-90207efb3eac (laatste code snipper, vervang proj_context door pj_ctx)

Waiting for a mutex (per tile) seems like a big improvement from having one PR_CONTEXT and waiting for coordinate transformation.

**Comment by jipclaassens** [comment]
No action required
