### ISSUE TITLE
Pop-up menu remains visible after activating Export Primary Data menu option

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#306]
Pop-up menu remains visible after activating Export Primary Data menu option

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/752877c1-4c5d-4770-9b0c-515e39025c77)

**Comment by eoudejans** [comment]
Rather hard to reproduce issue, changes have been made to hopefully address this issue. Maybe close and reopen once it reoccurs?
