### ISSUE TITLE
F2 should work in operators like impedance_matrix_od64()

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#308]
Like here:

OVSRV06:
`C:\ProjDir\Jip\_Github_issues\NetworkModel_EU_issueGH308\cfg\main.dms`

Item is red when opening the cfg. 
`/NetworkSetup/Pop_Weighted_NUTS_centroids/Indicator_Lewis/Numerator_Di`

I know the error in this case, but it would be nice to jump to it. Especially when it is a more complex issue.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/8a98a4d1-6e5b-4b67-915a-1c97a5d50e02)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/cbc2675d-fa78-4ad1-a86b-769bc661634f)
Population is as unit<uint64> and not an attribute and cannot be casted to a unit<float64>
