### ISSUE TITLE
csv with only one column have to be ended with semicolon for each row

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#310]
Why I Have to define a csv with only one field this way

FileName;
Y1975_ReadData_stats;
Y1975_UrbanArea_after_urban_stats;
Y1975_UrbanArea_stats;
Y1980_ReadData_stats;
Y1980_UrbanArea_after_urban_stats;

instead of
FileName
Y1975_ReadData_stats
Y1975_UrbanArea_after_urban_stats
Y1975_UrbanArea_stats
Y1980_ReadData_stats
Y1980_UrbanArea_after_urban_stats

GeoDMS 11.4.2

		unit<uint32>      optionSet := range(uint32, 0, 1);
		attribute<string> GDAL_Options (optionSet) : ['AUTODETECT_TYPE=YES'];//https://gdal.org/drivers/vector/csv.html
		
		unit<uint32> Overzicht
		: StorageName     = '%LocalDataProjDir%/results/stats/overzicht.csv'//generated by MSDOS: dir *.txt /s /b -->overzicht.csv
		, StorageType     = "gdal.vect"
		, StorageReadOnly = "True"
		, Source          = ""
		{
			attribute<uint32> id         := id(.);
		}

**Comment by eoudejans** [comment]
The [GDAL CSV driver](https://gdal.org/drivers/vector/csv.html) states that: "At least two fields per line must be present.", and a valid separator needs to be resolved for reading, which can be one of: [comma, semicolon, tabulation, a pipe, or a space].

This is behavior of the driver itself, we could change the driver, but it would require more knowledge why the original implementers of the driver chose this behavior; as there may be a good reason for it.

**Comment by eoudejans** [comment]
Could you post a screenshot of the error message that you receive? Perhaps it is not clear enough and there is room for improvement. The improvement part depends on extra information that can be retrieved from GDAL that is not already presented to the user.

**Comment by basvanbemmel** [comment]
GDAL Error: cannot open dataset K:/LD/towardsanurbanpreview_urbandensity/results/stats/overzicht.csv 
`K:/LD/towardsanurbanpreview_urbandensity/results/stats/overzicht.csv' not recognized as a supported file format.
/Postprocessing/Scenarios/ReadResults/ReadStats/Overzicht 

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/186b8273-0ae5-4330-85c9-1a1936182c38)

**Comment by basvanbemmel** [comment]
aangezien het een gdal-ding is zoals Erik aangaaf:
The [GDAL CSV driver](https://gdal.org/drivers/vector/csv.html) states that: "At least two fields per line must be present.", and a valid separator needs to be resolved for reading, which can be one of: [comma, semicolon, tabulation, a pipe, or a space].

is het niet meer relevant. Lijkt mij niet dat we nog native storage manager csv e.d. verder blijven ondersteunen. Kan wat mij betreft afgevoerd worden.

**Comment by eoudejans** [comment]
Super dan sluit ik dit issue.
