### ISSUE TITLE
MINUS operator at uint8

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#314]
II don't know if this is actually a bug but I've seen this behavior already before,
With a MINUS operator on a uint8 value type I get a positive value for "negative numbers" (which is not possible according to this value type)

So in the example below
attribute<uint8> GridData; // values ​​1 and 101 occur
attribute<uint8> Build:=GridData - 100b;// returns for 101-->1 and for 1-->157

So I have a grid with values ​​1 and 101 of the unit8 type, I subtract 100 from that and the value 1 then becomes 157.
It looks like something is being done like (256+1)-100.

It doesn't make sense to me one way or another.
Actually, I expected error.

**Comment by MaartenHilferink** [comment]
Addition and subtraction on integers (both signed and unsigned) are modulo 2^nr_of_bits, which is 256 for uint8; I could start checking for overflow and underflow, and provide alternative function names (circular_addition and circular_subtraction) to access the current behaviour. We should first check how much impact this would have on existing projects.

**Comment by jipclaassens** [comment]
Zou een error moeten geven

**Comment by MaartenHilferink** [comment]
Wat we willen verbeteren is overflow en underflow detectie bij optellen, aftrekken, en vermenigvuldigen (en delen van de laagste signed int door -1) voor alle integer types: uint2, uint4, uint8, int8,  uint16, int16, uint32, int32, uint64, int64, en gerelateerde operaties met WPoint, SPoint, UPoint, en IPoint.

We zullen eerst als optie alle overflow en underflow gaan detecteren en dan betreffende en alle afgeleide items rood kleuren met een data error fail reason een vermelding van (tenminste) het eerste voorkomen van een overflow/underflow. 
Diagnostics ?  Overige resultaten (van andere rijen) zijn dan dus ook niet opvraagbaaar.

Issue is dat een reken-resultaat definieren als: 
  (alleen geldige resultaten) OF DataError 
niet voldoet aangezien we willen toestaan dat met iif, makedefined, lookup, en * 0 uit (deels) ongeldige elementen toch geldige resultaten kunnen komen.
Dan toch een quiet NaN (undefined) als resultaat van overflow/underflow ? En als aparte bitmap per attribuut-resultaat gaan bijhouden?

Er zijn geen efficiënte standaard c++ functies om carry of overlow vlaggen te gebruiken, maar wel compiler intrinsics (welke?) en inefficiënte standaard c++ implementatiestrategieën

**Comment by jipclaassens** [comment]
Also implement it for sum operators.

4 * 1,500,000,000

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e6504a83-6991-4ead-b3ec-75866277f7ef)

**Comment by MaartenHilferink** [comment]
Overflow detectie voor add, sub, mul en aggregatie operatoren is geïmplementeerd in 14.1.0: Item en afgeleide items worden rood met data error.
Wanneer overflow niet tot een data error maar tot een undefined value moet leiden, gebruik dan de nieuwe functies: add_or_null, sub_or_null of mul_or_null

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a5788c4c-7eb5-4cf1-9693-ea612376a8fe)
