### ISSUE TITLE
GDAL, writing to GeoPackage only writes one table

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#315]
Since version 11.5.0. the following command:

_"%Program Files%\ObjectVision\GeoDms11.5.0\GeoDmsRun.exe"  /S1 /S2 
..\RegressionTests\prj_snapshots\BAG20\cfg\BAG20_MakeSnaphot.dms 
snapshot_date_nl_geoparaat_gpkg/result_gpkg/make_geopackage_

results in a GeoPackage with only the addreses from the BAG and no other BAG entity.

**Comment by eoudejans** [comment]
Caused by incorrect check if the dataset should be appended or not. (WIP)

**Comment by eoudejans** [comment]
Solved in commit https://github.com/ObjectVision/GeoDMS/issues/315. Gdal regression test now properly creates multi layer geopackage files.
