### ISSUE TITLE
Reopen dialog should have a hot-key for choosing [Reload]  either 'r' or 'alt-r' or both.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#323]
![Image](https://user-images.githubusercontent.com/2284361/253820468-26d7b14a-c8b5-423e-8c89-d0805d340776.png)

[Ignore] as default (Enter) is ok i think.

**Comment by MaartenHilferink** [comment]
See also hotkey considerations at #279

**Comment by eoudejans** [comment]
Closing, as implemented, see commit above.
