### ISSUE TITLE
Opening this container freezes the application (old GUI)

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#324]
Opening this container freezes the application in old GUI

`/ModelParameters/Advanced`

OVSRV6:

`C:\ProjDir\Jip\_Github_issues\NetworkModel_PBL_issueGH324\cfg\main.dms`

might be related with #350

**Comment by MaartenHilferink** [comment]
As this is likely fixed with the #350 fix, this issue only needs to be re-tested and then either reassigned to me or closed.
