### ISSUE TITLE
layout ConfigOptionsDialog:

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#326]
![Image](https://user-images.githubusercontent.com/2284361/253927137-1d90de59-229c-4aff-a27a-f89a72710813.png)

**Comment by eoudejans** [comment]
Layout appended by a spacer item to properly orient items to top.

![config_options_layout](https://github.com/ObjectVision/GeoDMS/assets/96182097/9a2be580-b47f-444a-aed0-d341c662bf2b)
