### ISSUE TITLE
Recent file list: add options to remove and/or edit, sort? and/or pin items in this list would be useful

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#328]

**Comment by mtbeek32** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/9033a4ac-4c84-421e-b8d8-dbb6cd703ec3)

My list becomes a little long :)

**Comment by eoudejans** [comment]
User is now able to control recent files list and throw away configurations no longer needed. See:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/477bd9be-5fb4-4ff1-b58e-2c378ece3bf2)

Icon is a placeholder at the moment, may be candidate for replacement.
