### ISSUE TITLE
Treeview context menu not closing on user click. For instance when opening export primary data dialog.

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#331]

**Comment by eoudejans** [comment]
Can no longer be reproduced, treeview context menu seems to properly close on click.
Also properly closes on switching application context.

**Comment by eoudejans** [comment]
Closing for not being reproducible.

**Comment by mtbeek32** [comment]
Issue seems to be still happening after a reload of the project. A repeatable scenario is not yet found.

**Comment by jipclaassens** [comment]
If a task is moved to done, please close it. Or it isn't done?
