### ISSUE TITLE
ValueInfo navigatie

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#335]
When source was a tableview row, column, we want to reactivate or reopen that tableview, record (which might be on a different row when sorting, grouping or selection has changed) and column (which might have to be re-added).
Similar issues for when value info was requested from a MapView.

**Comment by MaartenHilferink** [comment]
When source was a tableview row, column, we want to reactivate or reopen that tableview, record (which might be on a different row when sorting, grouping or selection has changed) and column (which might have to be re-added).
Similar issues for when value info was requested from a MapView.

**Comment by eoudejans** [comment]
Added newly created forms to project.

**Comment by eoudejans** [comment]
Value info now moved to seperate window.
Also added history navigation (forwards / backwards).

See:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6ee26e5c-d2d9-4de9-878a-81e7cdefc00f)

Closing issue as implemented.
