### ISSUE TITLE
Crash op sum(pop) 2up populatie raster

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#338]
Crash wanneer ik de parameter sum_pop open.

sum(populatie 1975 > 0d ? pop 1975 : 0d)

Laatste waargenomen hoeveel geheugen committed: 420gb. Daarna hangt de computer. Op een gegeven moment is alles afgesloten. Alle open apps, maar computer niet herstart.

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\TowardsAnUrbanPreview_UrbanDensity_issueGH338\cfg\stam.dms`

`/Preprocessing/Urban/Population_R2023_Create/Y1975/big_raster/Sum_pop`

**Comment by jipclaassens** [comment]
Implementatie van #372 lijkt het geheugen probleem opgelost, maar na 13 minuten zit er pas 8gb in het geheugen...

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/64825d12-6931-40f4-856b-44781331b992)
