### ISSUE TITLE
drawing issue in MapView on scaled monitor

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#341]
Although #334 has been fixed, some of #246 has returned. See partially redrawn feature after selecting it, and horizontally truncated labels.

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0d3afb49-4021-4251-99c7-7a318c3064b0)

**Comment by MaartenHilferink** [comment]
However, render quality improvement with Delphi Gui (left) on a 125% monitor is significant:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/fbd333b0-805c-4df6-8922-504fd89f44d6)

**Comment by MaartenHilferink** [comment]
See also commits for issue #349

**Comment by mtbeek32** [comment]
Resizing the column width in tables results in issues like:

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/19f2c71b-9044-490b-9a53-d6d7621e3479)
