### ISSUE TITLE
drop op QDmsMdiArea accepteert alles

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#344]
ook drags uit FileExlorer.
De volgende code zou specifieker moeten worden:

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/cc32e5fd-4cac-4060-a52d-c84c3bc53aa2)

**Comment by mtbeek32** [comment]
It would be nice if a .dms file could be dragged in the TreeView as alternative for Filen Open

**Comment by eoudejans** [comment]
Drop events can now only be .dms files, which opens a new configuration OR a treeitem, which opens the treeitem in default view or appends it to the current view.
