### ISSUE TITLE
Fatal structured exception

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#345]
Open cfg naar: 
`/SourceData/Infrastructuur/OSM/NetworkPreperation/Network_with_extraverbindingen/Make_Final_Network`

Exception raised in release versie van debugger. 
In exe van 11.5.0 weer niet.

OVSRV6
`C:\ProjDir\Jip\_Github_issues\AccessibilityModelling_issueGH345\cfg\main.dms`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/2b3b4f02-5a17-4106-bbc7-fada277dbda8)

**Comment by MaartenHilferink** [comment]
Possible duplicate of #342

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8a2f1099-19de-4881-bbab-63d9f2dc4824)
Will be available in 12.0.0
