### ISSUE TITLE
Qt docks after resize and toggling very small

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#353]

**Comment by mtbeek32** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/24246911/41855f55-4b50-487f-89bf-9e7323227e2e)

Steps to reproduce

- Resize TreeView
- Alt-0 To Toggle Treeview Off
- Alt-0 To Toggle Treeview On again, treeview becomes very small
 
This also applies to the DetailPages (and, but less troublesome) for the EventLog

**Comment by eoudejans** [comment]
Fixed from commit https://github.com/ObjectVision/GeoDMS/issues/353.
Toggling visibility was set at widget level, which caused the dock to collapse but somehow to forget it's orignial size pre-collapse.

**Comment by mtbeek32** [comment]
For the TreeView this now works. For the Detail Pages and Eventlog not.

Detail Page > Resize a page > Toggle On/Off with button > Detail Page becomes small again.

**Comment by eoudejans** [comment]
Resizing fix was not implemented for eventlog. 
Furthermore, in the geodms qt branch treeview and detailpages work at my end when resizing.

**Comment by eoudejans** [comment]
Closing as resolved.
