### ISSUE TITLE
Eventlog: grouping and layout style of type and category filter options.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#354]
|                             | Minor     | Major | Warning | Error | Fatal |               
|--------------------|----------|----------|---------|-------|------|
| System                |                |              |            |           |         |
| WMS                   |  connect  |              |            |           |         |
| Progress               |                |              |            |           |         |
| Memory               |                |              |            |           |         |
| Commands          |                |              |            |           |         |
| Disposable           |                |             |             |           |         |

**Comment by mtbeek32** [comment]
- Categorize message types that appear in Eventlog
- Choose (editable?) colors for message types
- Define selectable options (combining category and severity) in an intuitive lay-out
- Storing selected options, e.g. in registry

**Comment by MaartenHilferink** [comment]
I prefer coloring to stay related to severity type, at it is now.

**Comment by MaartenHilferink** [comment]
wms category should allow for major and minor message filtering

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/dd54a854-d593-4b5e-8e3f-26fc4ba27464)

**Comment by MaartenHilferink** [comment]
minortrace msgs should not be generated, nor formatted and stored, when filtered off

**Comment by eoudejans** [comment]
@mtbeek32 what to do with this issue after rework of eventlog filter?
