### ISSUE TITLE
Main Menu File Remove option Export Primary Data (with submenus from Delphi GUI)

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#360]

**Comment by eoudejans** [comment]
Fixed from commit: https://github.com/ObjectVision/GeoDMS/commit/f26c5ab0429a17fe1b0cfa76cb3c14f997248ab1
See:
![file_menu_removed_export_primary_data](https://github.com/ObjectVision/GeoDMS/assets/96182097/589d28d7-9b1c-4d44-8bc3-97569d29ca2e)
