### ISSUE TITLE
Muisklik eerst afhandelen voor de source change check

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#362]
Nu kun je nog van item veranderen voordat het bericht dat er iets is verandert op komt. 
In de nieuwe GUI kan dat niet.

**Comment by eoudejans** [comment]
Fixed, source change check if now performed 500ms after used switches focus back to GeoDms. Which allows for the scenario of changing the current item to a more appropriate item before the model source file changed window opens and the used has no control what item will be expanded to after reopening.
