### ISSUE TITLE
reload na openen dataview geeft regelmatig unit unification errors

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#363]
1. open cfg op OVSRV6: `C:\ProjDir\Jip\_Github_issues\RSLight2021_ontwikkel_3_issueGH363\Runs\Casus.dms`
2. ctrl+D  op: `/CaseIndicatoren/Basisjaar/Materiaalgebruik/Stock_perProv`
3. Alles rood 'no calculation rule'
4. alt+r
5. Nog een keer ctrl+D  op: `/CaseIndicatoren/Basisjaar/Materiaalgebruik/Stock_perProv`, weer alles rood.
6. even naar beneden scrollen in de treeview.
7. log geeft aan dat `Classifications/Vastgoed/WP4/name` een error geeft. Op een andere computer kwamen er andere items naar voren, bijv: `/geography/RegioIndelingen/Impl/NL_BoundingBox/top_left`
8. sluit applicatie af
9. herstart applicatie
10. `Classifications/Vastgoed/WP4/name` werkt gewoon
11. Stock_perProv nog steeds niet. Mysterieuze error bestaat nog. Heeft iets met de storagename/type te maken? wegschrijven naar csv.

**Comment by MaartenHilferink** [comment]
onverwachte fouten lijken steeds domain unifcation errors van x met x, na een reload en in Dephi zien we dit niet. 

relevant code in Dephi:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/cb7a7176-2469-4fc4-9959-c845c6aa5098)

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0a6fd02f-690d-43dc-8ba8-18857de6470d)
etc.

**Comment by MaartenHilferink** [comment]
Jip zag dit vrijdagmiddag 1-9 nog een keer gebeuren

**Comment by MaartenHilferink** [comment]
Zie ook speciaal geval #484

**Comment by MaartenHilferink** [comment]
Mitigated in 14.1.1 waarin LoadConfigIpl pas 100ms na CloseConfig()->Close subWindows wordt aangeroepen.
