### ISSUE TITLE
Windows taskbar not informative

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#368]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/ca6780ff-ee2f-42b3-9bab-0ef63b02ae4e)

Due to the fact we place projects in a user specific folder, the first part of the name of the root configuration file is not distinguishing.

Could the root name of the configuration, presented in brackets, be placed before the root configuration file name.

**Comment by mtbeek32** [comment]
in Delphi this works nice

**Comment by MaartenHilferink** [comment]
Fixed !
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7cd834d9-0251-4f67-acdd-2735bb0fdf6a)
