### ISSUE TITLE
Error box FailReason not nicely formatted

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#369]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/bda0f10c-c9c4-4e2c-9d4f-a95669c5ec11)

Scenario:
Microtst.dms
item: /BackGroundLayer/district/float_hoek
request Statistics View

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/853dbb4e-edc2-4bfc-b289-0cf0e98f1305)

**Comment by MaartenHilferink** [comment]
Clicking on test/e now works !
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/2830e6de-1f52-446b-b723-6348aa6c6818)
