### ISSUE TITLE
Export Primary Data Dialog, Clicking on button with folder results in lost of file/folder name. Option Save does not work

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#371]

**Comment by eoudejans** [comment]
Folder/File information is now unchanged when file dialog is cancelled
Folder and file entries are now split, see:
![export_primary_data_folder_filename_split](https://github.com/ObjectVision/GeoDMS/assets/96182097/ac88bc3f-6863-4009-b80c-7682a4d0b277)

Closing as implemented.
