### ISSUE TITLE
2UP memory crash op /Preprocessing/Urban/Population_R2023_Create/Y1975/big_raster/GridData_wo_NoData wegens JenksFischer en vervolgens classify (en dan count op resultaat) die de 64GPix * 8Byte/Pix = 512 GB laat vasthouden.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#372]
Oplossingsrichtingen: 
- JenksFisher op instelbaar maximum aantal elementen laten bepalen (default: 5000 conform qGis, in te stellen bij GuiOptions)
- (default) geen count kolom toevoegen; te overrulen bij GuiOptions
- per expressie instellen of FutureTileFunctor (i.g.v. KeepData ? ) of LazyTileFunctor gebruikt moet worden.

n.b.:

![Image](https://user-images.githubusercontent.com/2284361/253954822-830fd65a-8daf-460a-9e67-26e930ad96b6.png)

**Comment by MaartenHilferink** [comment]
LazyCalculation wordt als property toegevoegd om big_raster/GridData_wo_NoData snel zonder veel geheugengebruik te kunnen opvragen in MapView.

**Comment by jipclaassens** [comment]
same issue #338

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/447ed825-e0fb-46d3-98f1-ba7ab27405f6)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e8061572-315f-40f7-b3b2-3bfb6d1c9eb0)

**Comment by MaartenHilferink** [comment]
Now, dafta is read and displayed in 00:01:52.

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/f9cabc34-bc16-414c-89a0-d56cd4f3161a)

**Comment by MaartenHilferink** [comment]
Note that the LazyCalculated property only affects the final calculation operation of the calculation rule for an item with that property, thus for: 

  attribute<float32> D := (A+B)+C, LazyCalculated = "True";

D will be calculated lazily, but A+B will be calculated as FutureTileFunctor, thus retaining intermediate results as the LazyTileFunctor for D can request the same tiles as long as it is active. To avoid the related memory consumption, define (A+B) explicitly as a LazyCalculated intermediate result, thus:

  attribute<float32> intermediate := A+B, LazyCalculated = "True";
  attribute<float32> D := intermediate+C, LazyCalculated = "True";
