### ISSUE TITLE
Unavailable options in menu not greyed out on my W11 computer

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#373]
QT:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/ca631d5f-d931-4501-b11f-e00a91c6a71a)

Delphi:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/f13dd4b3-84ba-4d43-8224-3a11283b50f3)

**Comment by jipclaassens** [comment]
It appears to be related to having 'dark mode' enabled in windows 11.

**Comment by mtbeek32** [comment]
I will add this to the known issues in the documentation.

**Comment by jipclaassens** [comment]
@mtbeek32 closed? Ik begreep van @eoudejans dat we dit wel kunnen oplossen. Maar natuurlijk pas later.

**Comment by jipclaassens** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/48675272/43f7f746-b679-430b-81da-b7d938b0d98c)




![Image](https://github.com/ObjectVision/GeoDMS/assets/48675272/158644b3-f8af-467b-bac3-4d721d8182be)
