### ISSUE TITLE
Edit source descr options: move to separate toolbar for Source Detail page with radiobuttons.

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#378]

**Comment by eoudejans** [comment]
Source description now also follows the same route as the other detail pages (with the exception of the configuration page. See:
![source_descr_rework](https://github.com/ObjectVision/GeoDMS/assets/96182097/e770aea5-bc8f-4b04-a6f7-63a1344cc0de)

**Comment by eoudejans** [comment]
List is now visualized as ol, with li elements. See:
![source_descr_rework_ol_li](https://github.com/ObjectVision/GeoDMS/assets/96182097/2da8e31e-a0be-4834-a109-c77d1ff5ec50)

**Comment by eoudejans** [comment]
Implemented detail pages buttons for properties and source description pages, see:
![dp_button_widgets_implemented](https://github.com/ObjectVision/GeoDMS/assets/96182097/924a89af-783b-4a29-bd97-8c3c55988801)

**Comment by eoudejans** [comment]
Closing issue as implemented.
