### ISSUE TITLE
icons for storages back as in IMGUI

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#380]

**Comment by eoudejans** [comment]
@mtbeek32  To be tested and evaluated what icons to use eventually.

**Comment by mtbeek32** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/a1505479-d45a-46af-9362-0542690b2d86)

in IMGUI (9.1.1) the db icon was used for reading, the floppy disc icon for writing. I think this is a good starting point. Distinction between reading and writing is important.

**Comment by eoudejans** [comment]
See:
![storage_icons_treeview](https://github.com/ObjectVision/GeoDMS/assets/96182097/381fd5d0-34c9-49cd-b436-def4761b5f33)

Closing as implemented.

**Comment by mtbeek32** [comment]
The export icon in the table toolbar is a floppy disc. 

Maybe therefor is it more logical to use the database icons for reading and the floppy disc icons for exporting data.

**Comment by eoudejans** [comment]
Swapped icons, good suggestion to be more in line with other icons in application, closing issue.
