### ISSUE TITLE
Coordinate label + control: only enabled when a Map View is opened. The Z coordinate is ambiguous, use e.g. ZL instead

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#381]

**Comment by eoudejans** [comment]
Implemented, zoomlabel changed from Z to ZL.
Coordinate widget is now only visible in statusbar when the active mdi view has the type Mapview.
![ZoomLabel](https://github.com/ObjectVision/GeoDMS/assets/96182097/8e3332d1-d794-473c-8d9d-ab8f52a57661)

Closing as implemented.
