### ISSUE TITLE
Metainfo: %projdir% does not get resolved.

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#383]

**Comment by eoudejans** [comment]
Likely resolved, following syntax properly expands %projdir% 
**from:**
unit<uint32> reference: nrofrows = 5, url = "%projdir%/test_issue_383.txt"
**into:**
![projdir_resolved](https://github.com/ObjectVision/GeoDMS/assets/96182097/4271cf91-dd56-4c6f-a386-0e1c06cf8ee5)

Closing as completed.
