### ISSUE TITLE
Format Statistics in Table Layout

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#386]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/c7882922-2d9d-4082-89f2-dee6d0119cac)

It would be nice if these statistics could be presented in a table format.

**Comment by MaartenHilferink** [comment]
(Delphi)

![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/97870422-025d-4bbc-aa57-615dd2255f5f)


(Qt)
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4001a6fd-6396-4439-adb2-0e085d077136)

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/f7217a8b-ba54-450b-acb4-edaf51c8cba8)
