### ISSUE TITLE
Export data doesn't work (shp)

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#389]
Right click on unit with geometry and several attributes > export data
Leave everything on default values, save as ESRI shapefile.

Following messages in the log;
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e8f99020-9dac-4008-81f2-bec7fa63f7bf)

No files are exported.

Idem for csv, and geopackage.

OVSRV6:
Right click on unit:
`/SourceData/RegioIndelingen/Buurt/centroiden`

`C:\ProjDir\Jip\_Github_issues\AccessibilityModelling_issueGH389\cfg\main.dms`

**Comment by eoudejans** [comment]
I added checks for the to be exported geodms data type to gdal datatype if the driver is compatible with the gdal datatype. Here it states that FPoint, (float32) is not compatible with ESRI Shapefile.

Looking at the docs of gdal ESRI Shapefile it states that for creation: Only Integer, Integer64, Real, String and Date (not DateTime, just year/month/day) field types are supported. Further investigation is needed..

**Comment by eoudejans** [comment]
Looking at the other warnings, it seems likely that the error is caused by existance of multiple geometry fields in the to be exported set. The first geometry field will be the geometry of the dataset ie. Shapefile/GeoPackage. The next field will be written to storage as is. But FPoint is not supported as valid type conversion from geodms to gdal type in DBF.

**Comment by eoudejans** [comment]
What should be done, is convert the second to nth geometry field from geometry to WKT reprensentation and export as string type. To be scheduled for implementation.

**Comment by jipclaassens** [comment]
btw, it works in the delphi gui

**Comment by eoudejans** [comment]
Yes, likely done using our native shapefile and dbf drivers, with conversion of second to nth geometry field to WKT representation.

**Comment by eoudejans** [comment]
Likely related to issue #399

**Comment by eoudejans** [comment]
From commit https://github.com/ObjectVision/GeoDMS/commit/d050c6b895e592e7527d64d465c02b2a244f7609 on only one geometry dataitem will be written to storage, geometries of compatible domain will be skipped. 

To be tested if it now works properly.
