### ISSUE TITLE
Program Files in export pad GeoDmsGuiQt 12.1.0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#390]
GeoDms12.1.0 --> GeoDmsGuiQt

PD:
https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3_COROPTotaalKlasseMetZonNabewerking
SD:
https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL (eigenlijk is alleen RSL\Resultaten\PD9288 nodig)

Open ../Runs/Casus.dms

Ga Naar:
/Postprocessing/Totaalklasse/Case/WLO_laag_VW/COROPTotaalKlasseMetZonNabewerking
export primary data, csv, uitvinken use native driver
export pad: K:/LD/Program Files/Postprocessing/Totaalklasse/Case/WLO_laag_VW/COROPTotaalKlasseMetZonNabewerking
klapt eruit

![Program Files in export pad GeoDmsGuiQt 12 1 0](https://github.com/ObjectVision/GeoDMS/assets/24241780/1bf1e757-abcb-42af-821f-c16fd50c4a8d)

**Comment by eoudejans** [comment]
Fixed as of issue #392. Full filename now split into foldername and filename for clarity purposes.
