### ISSUE TITLE
Export primary data to csv with gdal

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#394]
Steps to reproduce:

GeoDMS 12.1.0, QT Gui,

repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration file: ..\tst\Unit\Storage\cfg\write_gdal_csv.dms

Export primary data on item: /export

Select format 
.csv, make sure Use native driver is disabled.

Option Export crashes

related to issue https://github.com/ObjectVision/GeoDMS/issues/390

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by eoudejans** [comment]
Crash caused by dereferenced nullptr, Function ColDomain->GetProjection() can be nullptr. Added test for nullptr/empty result from GetProjection to solve crash.
