### ISSUE TITLE
Crash if export settings have svn ref, but it is a git project

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#395]
OVSRV6: 
`C:\ProjDir\Jip\_Github_issues\NZlijn_issueGH395\Analysis\NZlijn.dms`

Open en klik op container: 
`/ExportSettings/SvnImpl`

**Comment by jipclaassens** [comment]
Might not be the cause of the error. Might be related to #320

**Comment by eoudejans** [comment]
Likely similar to crash fixed for #320. To be tested.

**Comment by eoudejans** [comment]
![fixed_crash_395](https://github.com/ObjectVision/GeoDMS/assets/96182097/5ad24ec7-56d7-4c38-9cba-50ed48cceab4)

**Comment by eoudejans** [comment]
Issue seems resolved, closing.
