### ISSUE TITLE
Script Editor folder dialog needs to be a file dialog

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#396]
With the Script Editor folder button a dialog appears to select a folder. But what you need to select is a file (e.g. Notepad ++.exe).

See :

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/2f1abb58-9ada-4d11-84d5-c08cb0cbda1f)

**Comment by eoudejans** [comment]
Script Editor is now a file selection dialog, solely able to select .exe files. See:
![editor_exe_path_selector](https://github.com/ObjectVision/GeoDMS/assets/96182097/6a324cc4-bb85-4def-947d-a37781c5482c)

Closing as implemented.
