### ISSUE TITLE
crash 12.1.0 Tools, Code analysis, clear target

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#397]
Activating op menu-item Tools, Code analysis, clear target results in crash (geodms windows disappears)

example:
https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/Cursus_MartijnSpoon

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by eoudejans** [comment]
Clearing target correctly cleared the target treeitem(s). However after clearing, the a state update to the cleared item is issued, which does not exist, resulting in crash. Fixed, closing issue.
