### ISSUE TITLE
New QT application icon

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#400]
How about a new application icon to go with the new application? It makes the distinction between the new and old. 

For instance, I got this stock image and added the summation sign:

![My project-1 smaller](https://github.com/ObjectVision/GeoDMS/assets/48675272/affd6938-94a0-4d1a-adba-a354d13244ce)

n.b. this needs to be posted in the download section of GeoDMS exe
<a href="https://www.flaticon.com/free-icons/globe" title="globe icons">Globe icons created by Vectors Market - Flaticon</a>

**Comment by mtbeek32** [comment]
I added a 32/32 pixel (GeoDmsGuiQt.png) variant and committed this in:
..\GeoDMSQT\qtgui\exe\res\images

**Comment by mtbeek32** [comment]
2 issues:
- add the text above to the about box
- old logo still seems to appear in start menu
