### ISSUE TITLE
more explaining centroid_or_mid in doc-wiki

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#401]
Could it be more explained what exactly is happening within the centroid_or_mid-syntax
https://github.com/ObjectVision/GeoDMS/wiki/Centroid_or_mid

_The centroid_or_mid function results in the centroid if it is located within the polygon or else **in the mid of the polygon**. This means the result of the centroid_or_mid is always located within the polygon._

What is the mid of the polygon?

I've added an example of the provincies of The Netherlands with holes in it to investigate the matter (red centroid-syntax and blue centroid_or_mid). Gelderland seems to a bit odd to explain
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/99a82a7f-687c-4420-8fd6-322930c0357a)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a8274698-bcc6-40ad-8dcb-9bd3387ca437)
