### ISSUE TITLE
reading float32 data from csv files with gdal.vect results in strange values

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#404]
Steps to reproduce:

GeoDMS 12.2.0, QT Gui,

repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration file: ..\tst\Unit\Storage\cfg\write_gdal_csv.dms

steps:
1) Ctr-D on item: export/FloatAtt > FloatAtt.csv file is written (this file looks fine in editor)
2) Ctr-D on item: reRead_FloatAtt > last thee values are not the data as in the exported file.

**Comment by eoudejans** [comment]
Behavior resulted from string interpretation in gdal.vect read logic to always interpret Float32 and Float64 data as Int64. 
![fix_issue_404](https://github.com/ObjectVision/GeoDMS/assets/96182097/1d248ca0-305a-4b6d-86e5-61544e903a22)

Closing as fixed.
