### ISSUE TITLE
formatting background layer eventlog messages

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#406]
steps to reproduce

tst repository > operator/cg/microtst.dms 
request item: BackGroundLayer/district/border

Eventlog issues, see screendump:
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/695eba3f-b1dc-436b-a40d-6c24809073a9)

1) connection and request items both have colors of connection
2) reformat: connect toservice.pdok.nl:OK... to: connect to: https://service.pdok.nl , result: OK
3) if the following eventlog line is the same as the last one, skip this line. 
4) reformat: request line to: request: _full request name_, result: OK
5) remove text wms (is confusing)

**Comment by eoudejans** [comment]
1: colors are now properly distinct between connection and request.

**Comment by eoudejans** [comment]
3: double log lines may point to duplicate messages being send. This may be better solved at generation level on a per-message basis. Otherwise wrong logging logic may get occluded..
