### ISSUE TITLE
exe niet vertrouwd door Google (Chrome)

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#407]
( met Chome 116.0.5845.96 )

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e329c9ec-c416-488b-a64a-82c6647f3a64)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/0770028a-2539-486b-ad60-0db8bdec8044)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/4497776e-bc5e-4214-a963-dd0641ca7bab)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/2f83b3f3-a548-48eb-86e4-5d4ced8f7530)

**Comment by eoudejans** [comment]
https://stackoverflow.com/questions/75901025/just-released-an-executable-of-my-code-on-github-but-chrome-stops-the-dowload-b

Apparently we are not the only ones with this issue, and zipping does not resolve the issue for this user at least.

**Comment by eoudejans** [comment]
From the [this chrome answer](https://support.google.com/chrome/answer/6261569?hl=en#:~:text=Why%20the%20download%20was%20blocked,%2C%20uncommon%2C%20or%20insecure%20file.) one category that is listed is: 
Unwanted: You tried to download a deceptive piece of software. This program, disguised as a helpful download, may actually make unexpected changes to your computer or device.

We do make changes to the user registry, however for Windows apps this is a common procedure to store app data.

**Comment by eoudejans** [comment]
Possible solution route would be to change the GeoDMS installer file extension from .exe to .msi to signal Chrome or other apps that it is in fact an installer.

**Comment by eoudejans** [comment]
Packaging and signing an app can be done using Visual Studio 2022.
https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net

Even signing can be build into one process.
https://learn.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps

**Comment by MaartenHilferink** [comment]
I guess we're in the category "Uncommon: You tried to download an unfamiliar and potentially dangerous piece of software."; 
what makes Chrome's claim that our software "gevaarlijk is" quite ​libelous and slanderous.

Let's first follow Chrome's guidelines in 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9f4217dd-9d84-437d-b2ba-01934d0e1017)

**Comment by eoudejans** [comment]
In https://www.google.com/about/unwanted-software-policy.html it states the unwanted software policy:

We hebben vastgesteld dat de meeste ongewenste software een of meer van dezelfde basiskenmerken bezit:

- De software is misleidend, de waardepropositie wordt niet nagekomen.
- Er wordt geprobeerd gebruikers over te halen de software te installeren of de software wordt samen met een ander programma geïnstalleerd.
- De software stelt de gebruiker niet op de hoogte van alle hoofdfuncties en andere belangrijke functies.
- De software beïnvloedt het systeem van de gebruiker op onverwachte manieren.
- De software is moeilijk te verwijderen.
- Het programma verzamelt en verzendt privéinformatie zonder medeweten van de gebruiker.
- Het programma wordt als onderdeel van een pakket geleverd (samen met andere software) en de aanwezigheid van die software wordt niet bekendgemaakt.

**Comment by eoudejans** [comment]
Furthermore it states that:
**Eenvoudig verwijderen**
Gebruikers moeten de software gemakkelijk kunnen uitschakelen of verwijderen.

- De informatie over de verwijdering moet goed toegankelijk, eenvoudig uit te voeren en duidelijk herkenbaar zijn nadat de software is geïnstalleerd.
- Tijdens het verwijderingsproces moeten gebruikers duidelijk gelabelde en herkenbare instructies krijgen waarin wordt uitgelegd hoe zij de vorige instellingen van hun browser en/of computer kunnen herstellen.
- De software moet een duidelijke verwijderingsprocedure bieden en mag geen misleidend gedrag vertonen om het verwijderen te ontmoedigen. Enkele voorbeelden van misleidend gedrag zijn:
- Valse of misleidende beweringen doen over potentiële negatieve effecten op het systeem of de privacy van de gebruiker als de software wordt verwijderd.
- Een vergoeding vragen om de software te verwijderen.
- Extra aanwijzingen of aanbiedingen opnemen die niet nodig zijn voor het verwijderingsproces.
- De standaardoptie in het programma voor verwijdering van de software zo instellen dat de software wordt verborgen in plaats van verwijderd.
- De verwijdering mag geen invloed hebben op niet-gerelateerde bestanden.
- Nadat de software is uitgeschakeld of verwijderd, moet de verwijdering volledig zijn. Configuratiewijzigingen die van invloed zijn op het gedrag van bestaande software, moeten ongedaan worden gemaakt. Na verwijdering mogen er geen gedeelten van de software actief blijven of automatisch worden ingeschakeld, uit zichzelf of door een ander programma.

**Comment by jipclaassens** [comment]
Download van 13.0.0 van GitHub met Chrome v 116.0.5845.97 geeft geen enkele melding over moeilijkheden

**Comment by jipclaassens** [comment]
Op OVSRV6:

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/26d74454-917e-4833-bb77-252eadedecda)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/199a9b81-286e-45ba-a507-e74084eb1358)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e43f684b-d4a5-4b7a-920a-a7e59c5ca42e)


![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b408598b-804f-48b1-85d5-16a640acb6ae)

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/2be66f59-2e7e-4dff-b895-87a06d7615d5)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/64cd88ce-1e0d-4dda-9cbd-b2a8ecb3b186)

**Comment by jipclaassens** [comment]
Actie:
Setup op eigen website zodat we een security report aan Google kunnen vragen.

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b3a0b85a-bb03-4a72-94e9-95b3e38c7dbd)


![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e3afa70c-cae4-4442-84ab-b44a52b56903)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/0a24a591-9e8e-46ea-944b-8d8cd9da77f8)

**Comment by mtbeek32** [comment]
Setup for 14.1.0 is now also available at: 

https://www.geodms.nl/downloads/Setup/14/GeoDms14.1.0-Setup-x64.exe

We can also add other files here.

**Comment by eoudejans** [comment]
Issue remains for Google Chrome version:
Versie 117.0.5938.134 (Officiële build) (64-bits)
And GeoDMS version 14.2.1

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/bb99653d-5987-42d2-8ec8-dff1f65d064d)

**Comment by jipclaassens** [comment]
its back!

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/82351e45-262b-4329-b8ac-65ba8f75a585)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5720d193-0110-407e-b885-1700f0ead47c)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b91b366a-4163-4045-9bf9-8ee16faccdec)
