### ISSUE TITLE
sleep table item in table view van ander domein zou error moeten geven

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#408]

**Comment by eoudejans** [comment]
From now on adding an item to a view which is incompatible to that view will now result in an error and no longer open the default view of that window. See error:
![fix_issue_408](https://github.com/ObjectVision/GeoDMS/assets/96182097/5ee1a28d-1213-4c17-a3d5-225193dc6fc4)

Closing issue.
