### ISSUE TITLE
Copy tool for Eventlog

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#414]
It would be nice to have an explicit Copy button in the Eventlog.

Can we use the same button as the the copy buttons in the toolbar?

Related: selection of multiple records and select all (ctr-a) in eventlog.

**Comment by eoudejans** [comment]
Implemented multi-line copy. Copied lines are always sorted in chronological order in eventlog model, changed from default order as chronological selection order.

**Comment by eoudejans** [comment]
Eventlog copy multiple lines functionality available using CTRL+C, or from the copy selected eventlog lines to clipboard pushbutton, see:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7a1fa455-951a-490c-80aa-a6cc52dd1751)

Closing as implemented.
