### ISSUE TITLE
Not able to go to last record in TableView in 12.2.0Qt

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#419]
The behaviour of table view is very strange to go to the last record. I'm not able to go to the last record in table view. Or I see only the header of the table (fields) or have to scroll by hand with the arrows but not able to go to the end as this would take very long. It looks like the vertical scrollbar with the arrows doesnt fit or something with the size of the table. Looks out of sync.

GeoDMS 12.2.0 Qt
cfg:
https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/Cursus_MartijnSpoon   rev 10052 (remark: revision number matters! as there much development in this cfg)
item: /RV23/Subsector  (control D). 140400000

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/e45f518d-4640-4fd4-93c8-bbcd89520d0f)

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/870e641c-36bd-4056-b935-abed3e728f71)

**Comment by basvanbemmel** [comment]
By the way in 12.2.0 Delphi I get

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/c8939c22-5275-483f-96be-189f8fae9b58)

It does work in 8.9.1

**Comment by jipclaassens** [comment]
Issue persists. Open table, drag scroll bar to bottom with mouse, but it is not the end. You can manually scroll further to the real bottom of the table.

**Comment by eoudejans** [comment]
@basvanbemmel scrolling in the requested tableview results in crash in GeoDMS using Debug x64 mode. To be further investigated. Failed (Debug only) check: assert(drawn_rect_is_included_in_device_rect);, line 438 in MovableObject.cpp.
![issue_419](https://github.com/ObjectVision/GeoDMS/assets/96182097/641eeec4-591c-4faf-bb7c-74ea36b680e2)

**Comment by MaartenHilferink** [comment]
Related issue: when pressing home or end, active row becomes the first resp. last row, but only becomes visible after pressing right resp. left

**Comment by MaartenHilferink** [comment]
Workaround: use the End (and then Left for GeoDms version <= 13.0.1) to display the last row.
