### ISSUE TITLE
exporting data does not work if data is read from an data array [..]

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#420]
steps to reproduce:

Repository: https://github.com/ObjectVision/GeoDMS-Test
C:\Users\Martin\tst\Unit\Storage\cfg\read_and_write.dms

Scenario I: 
1. Request item /test in table view

results: 
- no data is exported
- an incorrect message occurs that the data is provided to a csv file.

Scenario II: 
1. Edit Config Source on item: /test
2. Uncomment item: name_expr
3. Reopen configuration
4. Request again item /test in table view

results:
- no name_expr attribute is exported
- unclear gdal message appears: it seems no file system object called ... exists

The exporting behavior is probably related to the fact that read/write storages are mixed up here. Two options:
- 1) If data is read from a data array, it can not be directly exported. In this case a clear error needs to be given.
- 2) (preferable) Support exporting the data read from a data array  directly to a storage.  

Furthermore the writing of storages need to be synchronized with the event log messages and the unclear gdal errors need to removed or clarified.

**Comment by eoudejans** [comment]
Considering the part of the issue:
_unclear gdal message appears: it seems no file system object called ... exists_

This unclear gdal message originated from a CSVDriver->Delete() call. The csv driver does not check if the .csv file actually exists on the filesystem and attempts to delete it always. Which results in this error message when the file does not exist. This part is solved, see commit reference above.

**Comment by eoudejans** [comment]
Considering scenario I:
There seems to be a disconnection between where the file is actually created/written to and where the log message of 
[AbstrUnit.cpp line 250 ](https://github.com/ObjectVision/GeoDMS/blob/main/tic/dll/src/AbstrUnit.cpp#L250) is generated. In this case it is very confusing because no file is written but GeoDMS informs the user that there was a file written.

**Comment by MaartenHilferink** [comment]
Fixed in 12.4.0
