### ISSUE TITLE
Error dialog, source file changed dialog are modal, but can be shown without the mainwindow shown. 

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#422]
Alt-Tab from config source editor to a GeoDMS window with a error or source file changed dialog active causes only the dialog to appear. 

On the other hand, the export primary data modal dialog does work fine.

**Comment by mtbeek32** [comment]
Other options dialogs seem to work fine, as the export primary data modal dialog

**Comment by eoudejans** [comment]
The main reason for error- and recent-files modal windows being seemingly disconnected from the rest of the application is that they are opened using exec, which blocks all other events to the application, possibly also the show events for the main application window.
