### ISSUE TITLE
If table view of a domain is already opened do not open a new table 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#424]
ctrl +d op een table opent een tableview, doe nu nog eens ctrl+d op diezelfde table

**Comment by eoudejans** [comment]
At the moment this behavior seems identical to the old geodms gui behavior. To be decided what behavior is preferable and what to implement.

**Comment by jipclaassens** [comment]
Requested behaviour is realised by double-clicking
