### ISSUE TITLE
tab edits

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#425]
- achtergrond kleur vna tabs aanpassen
- titel van tabs aanpassen (view type onnodig, want icoontje). 
  - Suggestie tables: dom_name (xxxx rows)
  - Suggestie mapview: mapview window counter; EPSG-code (of evt vervangen door een geconfigureerde label); active: Stops/FirstEvent (46,155 rows). Dus: "0; rdc; active: Stops/FirstEvent (46,155 rows)" 
- als cascade windows is geselecteerd, dan geen tabs
- tabjes links uitlijnen

**Comment by eoudejans** [comment]
Background color implemented for tabs, to be finally determined.
Tabs outlined to the left.
See:
![rework_tab_mdi_area](https://github.com/ObjectVision/GeoDMS/assets/96182097/5f18a8f1-8d1e-4650-826c-1fa08c418148)

**Comment by jipclaassens** [comment]
Fly over maken bij tabs waar namen te lang zijn.

**Comment by eoudejans** [comment]
Mapview labels now also changed to no longer redundantly specify that it is a Mapview, while the mapview icon is already clear enough.
![mapview_labelling](https://github.com/ObjectVision/GeoDMS/assets/96182097/e9a6c515-1035-4b2c-99f8-97f7cf5a6526)

Closing issue as completed.
