### ISSUE TITLE
arcs with null coordinates visualise towards the top left corner, but stay in view when panning

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#426]
Mapview van:
`/SourceData/Infrastructuur/GTFS/StaticNets/CreateTransfersSet/TransfersByStart/geometry`

OVSRV6:
`AccessibilityModelling/cfg/main.dms`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b0b73855-a306-4232-b15b-254109a4d7fd)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/bbca184a-29e5-4dd7-9c26-110a25aa0969)
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/aed4f3a3-51a3-40f3-a05b-2fc1c4eea345)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5f0e42c3-daf2-4e72-8e10-4219fb6257ae)

**Comment by MaartenHilferink** [comment]
Ik vermoed dat dit in v14.17.2 is opgelost, aangezien de <nulls> nu bij het tekenen als linstring-separators worden herkend.
