### ISSUE TITLE
the outline of the grid-pattern looks irregular when zooming in in 12-serie

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#427]
When zooming in at griddata for example /RegioIndelingen/Per_10m in cfg: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/Cursus_MartijnSpoon
the outline of the grid-pattern looks irregular.

12.2.0 Qt (also Delphi) versus 8.9.1

In this case only vertical lines
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/32b4f45f-fd94-4347-b2d9-f422169e3cb4)

**Comment by MaartenHilferink** [comment]
See also #341

**Comment by MaartenHilferink** [comment]
Issue appears in both Delphi Gui and QtGui on a 100% scaled monitor on GeoDms 12.x.y.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d4345e23-7ce1-451d-8ec4-371f5deba2f3)
Fixed in 12.3.0; issue was introduced at the end of July when fixing issue #341
