### ISSUE TITLE
GeoDmsGuiQt.exe not always detect dms-file-changes forcing to reopen cfg

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#428]
I notice sometimes the GUI don't pop up the "Source changed"-widget when a dms files has changed and saved. Sometimes it pops up later. Most of the time it works fines but it is not negligible.
You have to reopen the cfg by hand with ALT-R

**Comment by eoudejans** [comment]
GeoDMS does check on every refocus event (switching for instance from an editor to the GeoDMS application) for changes in source files. This source file change check does not always result in the full list of file changes. To be further diagnosed what is the cause of this behavior.

**Comment by basvanbemmel** [comment]
no, unfortunately not really

**Comment by mtbeek32** [comment]
After opening a new configuration, still some old tree items still seem to 'live' and old configuration files seem to be checked for changes.

**Comment by jipclaassens** [comment]
open dit dms bestandje

klik eenmaal op de root, zodat je een general page ziet

klap dan de provincie unit open, deze wordt dan rood.
Klik dan op een ander item, de general tab is nu bevroren.

**Comment by MaartenHilferink** [comment]
Issue is zojuist gefixt, zie bovenstaande code-wijzing. Komt beschikbaar in 13.2.0
