### ISSUE TITLE
many read eventlog messages (errors) while all results can be calculated

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#430]
Expanding a case results in many red eventlog messages. See the screendump:
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/d93d7560-00ca-4680-9b26-62af6f9e07eb)

The results of this case can all be calculated. This sounds paradoxical. If the results of a case can be calculated, only warnings but no errors should be reported.

Steps to reproduce:
- GeoDMS 12.2.0, Qt
- configuration: https://svn6.sliksvn.com/objectvisi_acc/CityCo 
- revision: 98

expand item: Wroclaw, messages appear

**Comment by jipclaassens** [comment]
Waarom worden die items in de template uberhaupt rood? Bij de template instantiatie werkt het wel gewoon...

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/c007ea3f-b939-4c1e-ae28-9a9b90bcc078)

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9b4af4f2-6a5e-4e09-9f78-01a0b2b6ced8)
