### ISSUE TITLE
gdal.write.csv export string null values are re-read as empty strings.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#432]
See C:/dev/tst/Unit/Storage/cfg/write_gdal_csv.dms test_string after exporting.

**Comment by jipclaassens** [comment]
Can be solved using geodms script, using specific encoding for undefined values. 

Writing string:
MakeDefined(item_x, "@@@");

Writing numeric:
MakeDefined(string(item_x), "@@@");

Reading string:
iif(item_x=="@@@", string(null_f), item_x)

Reading float32:
iif(item_x=="@@@", null_f, float32(item_x))


Alternative for string(null_f) see #790
