### ISSUE TITLE
Config options dialog is not using the DmsConfigOptionsWindow.ui

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#437]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/e84c43d4-ec7d-473a-883a-b21e8d840d7e)

A ui is made available for this dialog, but not yet in use

**Comment by eoudejans** [comment]
As the ui is only specifying a small section of the form, this specific form is better done fully programatically. The Ok Apply and Undo buttons were grouped to be in line with the other option forms. See:


![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/31ccbddb-1cbd-4205-a580-c797a7578447)

Closing issue.

**Comment by mtbeek32** [comment]
It's fine if this dialog is done fully programmatically, but can the header be (to make it consistent with the other dialogs) like this:

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/de510a32-10c8-4e9b-9465-b2996e7136c7)

**Comment by eoudejans** [comment]
Config options form now conflict with programatically added part of the form, see:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/013d8170-8f4e-4e8c-a437-93c414313830)

**Comment by eoudejans** [comment]
Proposed solution is to:
- remove the Ok, Cancel, Undo buttons at Qt Designer form side, these will be implemented at the c++ side.
- make use of gridlayout for the config options header.  To this gridlayout further config options can be appended programatically.

Which will result in a clean form with layout in line with other option windows.

**Comment by eoudejans** [comment]
Now using the new ui form, combined with programatically added user specified config options, see:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/f09a554d-93f1-4bd6-a121-15059de48d7d)

Closing as implemented.
