### ISSUE TITLE
Crash with code analysis on red item

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#441]
OVSRV6:
C:\ProjDir\Jip\_Github_issues\RSOpen_issueGH441\Runs\PrepareBasedata.dms

Remove LocalDataProjDir/BaseData

Then open container /MaakBasedata, you'll see the last two run9 and run10 being red. 
Tools>Code Analysis>set target and add target on those items will result in crash.

It should not give a meaningful result, but foremost it should not crash.

**Comment by eoudejans** [comment]
Reproducibility confirmed. Likely unhandled exception at gui side.

**Comment by eoudejans** [comment]
Issue resolved, proper error handling added in case of code analysis.
![issue_441_fix](https://github.com/ObjectVision/GeoDMS/assets/96182097/b5d3c369-6fcd-4a19-ac90-2660ccfdb6e8)

Closing issue.
