### ISSUE TITLE
Crash if unit in using is missing

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#443]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\RSOpen_issueGH443\Runs\casus.dms`

Ga naar
`/SourceData/Grondgebruik/BGT/filedate`

In detailpages staat 
```
UsingCache Error: Cannot find reference in Using = "units"
[c:\projdir\jip\rsopen\cfg\main\SourceData\GG\BGT.dms(1,1) ](editconfigsource:c:\projdir\jip\rsopen\cfg\main\SourceData\GG\BGT.dms(1,1)): /SourceData/Grondgebruik/BGT: TreeItem
/SourceData/Grondgebruik/BGT/filedate
```

Dan klik je op die `BGT.dms(1,1)`

Dan krijg ik deze melding in Notepad++

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/be4f4936-6995-42a1-a709-ab07ac471714)

Klik no, terug naar GeoDMS, alt+r 

Dan verandert de melding in de detailpages naar:
```
UsingCache Error: Cannot find reference in Using = "Classifications/LandUsePreparation"
[c:\projdir\jip\rsopen\cfg\main\SourceData\GG.dms(1,1) ](editconfigsource:c:\projdir\jip\rsopen\cfg\main\SourceData\GG.dms(1,1)): /SourceData/Grondgebruik: TreeItem
/SourceData/Grondgebruik/BGT/filedate
```

Klik nu op LandUsePreparation, en crash.

**Comment by MaartenHilferink** [comment]
Now, SourceData/Grondgebruik is failed; failure now appears at UpdateMetaInfo directly when any of the using refs is invalid.

**Comment by MaartenHilferink** [comment]
Fix was accidentally committed to branch v10, but now merged into v13
