### ISSUE TITLE
unreachable href link in fly-over text in Local Machine options 

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#444]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/3f9ff653-8b78-4519-94e3-514701c1a06e)

I don't manage to activate the blue href in the PP (i) fly-over text.

How could a user be helped to click on the blue text (specific hot-key?) , or should we remove non-functioning links ?

**Comment by mtbeek32** [comment]
The tooltip pop-up disappears after a mouse move, making it not possible to click the hyperlink.

From the documentation I understand this is not easy to change and might also be less intuitive (user expects that tooltips disappear after mouse moves). Current implementation:  don't use hyperlinks in tooltips.
