### ISSUE TITLE
separator between close all but this and the current views

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#447]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/b40b0c02-7111-43ab-886c-535a75133692)

**Comment by eoudejans** [comment]
Implemented, see:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/460678ee-287d-4a83-a6b4-1aed6140494e)

Closing issue.
