### ISSUE TITLE
icon in Windows menu and in View > Calculation times view 

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#448]
As the titles of the menu do not consist the view type anymore, an icon is useful in the mentioned locations.

**Comment by mtbeek32** [comment]
see e,g,
http://www.learningaboutelectronics.com/Articles/How-to-add-an-image-icon-to-a-menu-item-qt-widget-c++.php

**Comment by eoudejans** [comment]
Implemented, icons in window menu required some way to retrieve the viewstyle of the MdiSubWindow, which is no problem for dms native views: mapview, table view. However statistics and calculation times views had no specific viewstyle.

This is now solved by adding a "viewstyle" property to all MdiSubWindows destined to be shown in the main mdi area. More information on the QProperty system can be found [here](https://doc.qt.io/qt-6/properties.html).

![icons_view_menu](https://github.com/ObjectVision/GeoDMS/assets/96182097/88b328e3-0fbb-4a37-95a9-0772711501ac)
![icons_window_menu](https://github.com/ObjectVision/GeoDMS/assets/96182097/1401fe85-83a1-435e-a85a-cd707fd12d14)

Closing issue as implemented.
