### ISSUE TITLE
Crash Code Analysis

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#449]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\RSOpen_issueGH449\Runs\casus.dms`

Code Analysis > set target op:
`/Analysis/Allocatie/Zichtjaren/Y2030/Impl/Generate`

**Comment by jipclaassens** [comment]
In debugger versie van einde middag 17 aug, crasht ie niet.

**Comment by jipclaassens** [comment]
In release v 21 aug 10u, crasht wel

**Comment by eoudejans** [comment]
Can confirm that in debug no crash happens.

**Comment by jipclaassens** [comment]
Volgens mij is het issue nog niet opgelost? Ik zit in release van gister middag.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/ea429e06-34bd-4b1f-87a6-eff749596271)
