### ISSUE TITLE
Unclear error nth_element

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#455]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\Delta_Scenarios_2023_issueGH455\cfg\stam.dms`

Zie error op rood item:
`/SourceData/Grondgebruik/NVK/ParijsBossen/ExtraBosBuitenNNN/Afkapgrens`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/77edeee7-5f05-4d05-a722-207277317d49)

Documentatie zegt: 
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/fe74865e-41ee-41df-8232-5fda92a510cc)

Maar in de RuimteScanner zit deze ook, en daarin is a uint32, n float32, en rel uint32.

OVSRV6: 
`C:\ProjDir\Jip\RSOpen\Runs.dms`
`/Analysis/Allocatie/Zichtjaren/Y2030/Sequences/Seq_0/SectorAllocRegios/Wonen_NVM/Iters_Normaal/Iter_0/Subsectoren/meergezins_SocialeHuur/AllocRegio/Afkapgrens0`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/77961abc-5d89-4045-935d-68163d8a9ac6)

**Comment by MaartenHilferink** [comment]
Confirmed. In nth_element.cpp, only operators with UInt32 partitionings have been instantiated.
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/5e0cbaac-bc42-4d05-b886-873217de50c2)

**Comment by jipclaassens** [comment]
GeoDMS-Test:

`C:\ProjDir\Jip\_Tools\GeoDMS-Test\Operator\cfg\issue_gh455.dms`

zie error bij: `/nth_element`
