### ISSUE TITLE
%LocalDataProjDir% verkeerd geevalueerd

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#459]
%LocalDataProjDir%/basedata/... wordt niet %LocalDataDir%/%projname%/basedata/...
maar

%LocalDataDir%/projdir/basedata/...

zie test script: 
[test.zip](https://github.com/ObjectVision/GeoDMS/files/12429798/test.zip)

**Comment by MaartenHilferink** [comment]
Test script saved as "C:\dev\tst\Unit\Storage\cfg\issue_459.dms"

**Comment by MaartenHilferink** [comment]
cannot reproduce:

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/4f8bfce5-462b-4c51-8293-f0833b41274e)
