### ISSUE TITLE
lowercases and uppercases in recent file list

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#460]
in GeoDMS 13.0.1 still lower and uppercases are in use in the recent file list.
 
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/5f1a977e-9bf5-457d-9496-53971c43183d)

Options 11 and 13 refer to the same configuration file.

Why is number ten not aligned with 11, 12 and 13 ?

**Comment by mtbeek32** [comment]
Other observation: Computer\HKEY_CURRENT_USER\SOFTWARE\ObjectVision\DMS\RecentFiles contains 30 entries, menu option shows only 13.

**Comment by MaartenHilferink** [comment]
Maybe the casing isn't what causes double entries, see numbers 1, 26, 28, and 30.



![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4b8d7619-9aa2-4203-895c-793705ee9bed)
