### ISSUE TITLE
Eventlog TextFilter button, disable when currently filtered based on text, reenable when text changes.

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#465]

**Comment by eoudejans** [comment]
Solved in latest commit, see:
![eventlog_text_filter_disabling_enabling](https://github.com/ObjectVision/GeoDMS/assets/96182097/14c6ae4c-013f-4ff3-87ff-ef5ae5f9725e)

Closing as implemented.
