### ISSUE TITLE
Cannot reclassify data to user-defined number or classes

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#467]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/ebe9f6bd-47e9-4e45-a71a-eb4ecca5d7d7)

Only option Equal Counts is enabled, number of cells can not be set.

Scenario:
- MicroTst.dms
- Request DistTo in MapView
- Activate Edit Palette from legend
- Try to reclassify
 
See also issue #454

**Comment by jipclaassens** [comment]
You can also not type in the number of classes, AND not edit classbreaks...

**Comment by MaartenHilferink** [comment]
Fixed in 13.3.0

**Comment by jipclaassens** [comment]
Als je een class break aanpast en dan ernaast klikt wordt het juist opgeslagen. Maar druk je op enter, dan wordt het null ipv opslaan.
