### ISSUE TITLE
consistent ok, cancel buttons.

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#469]
GUI options has Cancel button enabled (button does not work), Local machine Options and Config Options has Cancel button disabled.

I think it is best to have the button enabled in all three dialogs and activating the button should close the dialog without making any changes.

**Comment by eoudejans** [comment]
Gui cancel button was connected to apply, not to cancel function in GuiOptions. Fixed in latest commit.

Closing issue as fixed.
