### ISSUE TITLE
Recent files reordering

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#470]
void MainWindow::insertCurrentConfigInRecentFiles(std::string_view cfg)

contains

m_recent_files_actions.swapItemsAt(cfg_index_in_recent_files, 0);

i tried:

        while (cfg_index_in_recent_files > 0)
        {
            auto more_recent_cfg_index = cfg_index_in_recent_files - 1;
            m_recent_files_actions.swapItemsAt(more_recent_cfg_index, cfg_index_in_recent_files);
            cfg_index_in_recent_files = more_recent_cfg_index;
        }
but then first item was moved down to cfg_index and the rest 1 up.

**Comment by eoudejans** [comment]
Implemented in latest [commit](https://github.com/ObjectVision/GeoDMS/commit/f6aa55a4bd9e6263229b75a3032e2a74a800ee8a), closing issue.
