### ISSUE TITLE
Expand All does not work in QT

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#474]
Steps to reproduce:

Configuration: in full test: ..\prj_snapshots\RSLight_2020\cfg\RSLight_2020.dms
Activate Item: /SourceData/Claims/ReadData
Expand all via * does not expand all items.

Probably related: ExpandRecursive from script does not expand all items.

**Comment by MaartenHilferink** [comment]
2x '*'seems to expand 2nd layer. Does '*'expand all visible closed '>' once to allow a certain amount of sub-items to be opened determined by pressing '*' that amount? If so, maybe this is even better than expanding all at once.

**Comment by eoudejans** [comment]
Confirming that in Operator.dms all items expand as expected.

**Comment by eoudejans** [comment]
Reproducibility of issue confirmed.
Stepping into DmsModel::rowCount(const QModelIndex& parent) const while calling * on /SourceData/Claims/ReadData results in 0 rows for item /SourceData/Claims/ReadData/WLO_laag, which may indicate that UpdateMetaInfo has not (yet) been called for this item. To be further investigated..

**Comment by eoudejans** [comment]
Expand all was not functioning properly as it was assumed that metainfo was updated always before calling rowcount. This is not the case for recursively expanding all items using *. Fixed in latest commit. Expanding now seems to properly work.

To be further tested.
