### ISSUE TITLE
Code Analysis doorverwezen units lichten nog niet op

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#478]
/![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/2824a9d1-6450-43b4-9965-0abf979fdf6f)

B en C lichten niet op, maar wordt wel gebruikt in de impedance matrix.

OVSRV6, of in GeoDMS-test repo:
`C:\ProjDir\Jip\_Tools\GeoDMS-Test\Operator\cfg\issue_GH478.dms`

set target op `/Matrix/impedance`

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/47d04382-fa7d-42bf-bf65-84cf72939e73)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a486e2ea-15ac-4f30-8c7c-9a1ee519c10a)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/58183922-6fde-47d8-a5a3-dd93c5e03273)

**Comment by MaartenHilferink** [comment]
Available in 13.4.0

**Comment by MaartenHilferink** [comment]
Now also included: used template definitions.
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e78c060b-34b5-4040-b2f2-4256d7e5dfe4)
