### ISSUE TITLE
Betere error wanneer placeholder dir niet bestaat

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#480]
De placeholder %NetworkModel_dir% is niet geconfigureerd in dit model. Ipv een vaag pad in system32 of soms krijg je de C:/GeoDMS/dev/GeoDMS/qtgui/exe/../ zou een foutmelding beter volstaan.

Cannot find placeholder '%NetworkModel_dir%' 

test script in:
`..\GeoDMS-Test\Operator\cfg\issue_GH480.dms`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/f38771c1-1bc5-4d41-8d3d-ee11ab1b8054)

**Comment by eoudejans** [comment]
Modified the placeholder resolve function GetPlaceholderValue in AbstrStorageManager.cpp, where now when a placeholder cannot be resolved an item error is thrown.
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/753e2626-3dd3-4fde-b395-8db9614994a1)

Closing issue as completed.

**Comment by MaartenHilferink** [comment]
Updated behaviour: only a warning is emitted, to avoid errors where a default is provided.
