### ISSUE TITLE
Replace WKT name with something if WKT is specified instead of EPSG

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#481]
Tab name is now super long...

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/02bebb87-6521-4389-9687-7754cf2bf029)

any spatial item in:
`C:\ProjDir\Jip\geodms_africa_cusa2\cfg\Africa.dms`

**Comment by jipclaassens** [comment]
use label property for configured unit with spatial reference in map view title, if available.

**Comment by eoudejans** [comment]
Treeitem label property is now prioritized over SpatialReference property if available for world coordinate unit.
ie unit<dpoint> AfricanACEA    : SpatialReference = "PROJCS[""A ...... ", Label="African Albers Conic Equal Area";

See:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/b82d61a3-d78e-49cb-b546-605fc1c58406)

**Comment by eoudejans** [comment]
Closing issue as implemented.
