### ISSUE TITLE
reload van unit met storage geeft ambiguiteit oud/nieuw in UnifyDomain

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#484]
Voorbeeld:
	
	unit<uint32> CorridorNameCSV
	: StorageName = "%projdir%/data/ListOfCorridorsCusaII.csv"
	, StorageType = "gdal.vect"
	, StorageReadOnly = "true"
	{
		attribute<int32> CorridorID := int32(corridorFootprintId);
		attribute<string> Label := replace(corridorName, '-','_',' ','_', '\''','');
	}
	
SourceLocation -> FileDescr -> timestamp waren equivalent.

**Comment by jipclaassens** [comment]
lijkt voornamelijk te falen bij reopen na edit in editor

**Comment by MaartenHilferink** [comment]
Dit issue Is een speciaal geval van #363 en is opgelopst
