### ISSUE TITLE
Disable Windows menu options if there is no window 

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#490]
If there is no data vies, menu options like Tile, Cascade and Close are still enabled.

It would be nice if they are disabled when no views are available.

**Comment by mtbeek32** [comment]
Please use underscores for different letters in Windows menu:
T: Tile Windows
a: Cascade
C: Close
l: Close
B: Close All But This

**Comment by MaartenHilferink** [comment]
Impl in GeoDms 14.1.0
