### ISSUE TITLE
Detailpage blijft leeg staan naar wegklikken, of value info te breed

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#495]
**Scenario 1:**
- klik 1x op G, zodat de detailpage weg is
- druk op alt + 1
- nu heb je lege detail page

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/7b278409-057c-4fed-8aef-5300ed2f3a0e)

**Scenario 2:**
- open value info, deze komt ipv generic
- open nu property page erbij, nu schuift value info naar links
- klik nog eens op property page knop, nu schuift value info niet terug

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/3d415595-1bfa-46e3-8cd8-3bfb7a23a8fa)

- dan value info sluiten met kruisje, dit geeft ook een lege detail page

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e4901ece-6b77-4928-8e25-deeda50fa5b5)

**Comment by basvanbemmel** [comment]
Ik heb vandaag hetzelfde geconstateerd in 13.3.0. Best wel storend overigens, mag van mij wel een hoge prio krijgen

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by eoudejans** [comment]
Scenario 1 fixed, Alt-1 / menu -> toggle detail pages never toggled the detailpages using the proper toggle route of the detail pages component.

**Comment by eoudejans** [comment]
Scenario 2 fixed, resizing docks was not straight forward but can be done using QMainWindow::resizeDocks(...,...,...) function. After closing the last value info window, the detail pages are now scaled back to default, 500 pixels.

Closing issue as fixed.

**Comment by eoudejans** [comment]
Closing as completed
