### ISSUE TITLE
sequence2points fails when sequences have more than 2^32 - 2 elements

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#498]
For such occasions, one needs a sequence2points_uint64.

**Comment by jipclaassens** [comment]
Issue Observed at 0vsrv06 when debugging Africa.dms (aka CUSA)

when opening  /Results/Maputo_Gaborone_Walvis_Base/Export_Package2_TrafficAllocation

  | nrPoints | 18537444261 | unsigned __int64

arg1 has 1424 tiles, thus at least 1423*2^16 integer sequences

average sequence size is therefore approximately 200 elements

**Comment by MaartenHilferink** [comment]
use sequence2points_uint64, available in 13.4.0
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/85b1f0b3-2f4a-4536-8114-3724ce0a28e0)
