### ISSUE TITLE
FenceContainer operator for compartimentization and tracing of a calculation process.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#5]
Use case: 
In RuimteScanner zien waar hij is in het proces.
Dus graag ook iets van pad informatie toevoegen.

**Comment by MaartenHilferink** [comment]
Beter om de geplande Fence functie van user-speficied-log-msg te voorzien, zie https://trello.com/c/vRfITtiz/112-block-operator

**Comment by jipclaassens** [comment]
linked #44

**Comment by MaartenHilferink** [comment]
De items die samen klaar moeten zijn, zullen als sub-items van het Fence resultaat opvraagbaar worden. Vraag is dan welke namen deze sub-items moeten hebben. Opties:
- FenceOne(msg, item) -> signature en subitems van item
- NamedFence(msg, name1, item1, name2, item2, ...) -> { name1 := item1; name2 := item2; ...);
- NumberedFence(msg, item1, item2, ...) -> { 'R1':= item1; 'R2' := item2; ... }

Bijvoorbeeld: 

```
 container WriteStand := 
     FenceContainer('Zichtjaar '+string(curryear)+' is nu berekend', CalcStand), 
     StorageName = "='%LocalDataProjDir%/'+casename+'/'+string(curryear)+'.mmd' ";
```

**Comment by MaartenHilferink** [comment]
Performance testcase: compare from branch /PBL/ProjDir/branches/RSLight2021_ontwikkel_3_PlanMonitor2023_9618_FenceContainer:
- revision 9702
- dan Head (komt er aan)

Eerst updaten:
- SourceData/RSL
- batch/RunAll.cmd -> ProductieRun: Nee; direct 2050: Ja; BaseData hergebruiken: Nee

**Comment by eoudejans** [comment]
2 Scenarios created in RS Open using FenceContainer, to be tested.
