### ISSUE TITLE
GUI option show hidden items does not hide items with IsHidden = 'True' in qtGUI 13.3.1

### ISSUE THREAD

**Issue by poorthuis-w** [ObjectVision/GeoDMS#502]

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by eoudejans** [comment]
Implemented logic for hiding treeitems in dms treeview using the IsHidden="True" property.

**Comment by eoudejans** [comment]
Treeitems in treeview now make use of the IsHidden="True" property. To be tested.

**Comment by MaartenHilferink** [comment]
TODO: warning indien DmsTreeView::expandToCurrentItem in hidden beland

**Comment by MaartenHilferink** [comment]
warning gegeven, maar eigenlijk zou DmsTreeView::expandToItem helemaal niet aangeroepen mogen worden met een target_item waarvan en ancestor Hidden Is.

**Comment by MaartenHilferink** [comment]
When clicking on a calculation rule link to a hidden item:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ed360790-bf49-4c1e-bde4-c54c74b2fe33)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4944a9f5-8d76-4007-96c1-6477de90b53f)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0fbf5a80-daaf-4acf-ba5c-2a15946517ea)
