### ISSUE TITLE
Impedance OD uitbreiden met extra interactie aggregaties

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#514]
Voor het werk van Chris hebben we een aantal uitbreidingen nodig van de interactie opties in [impedance_matrix_od64](https://github.com/ObjectVision/GeoDMS/wiki/Impedance-options#interaction):

**BOLD** = DONE

- **aggregeren over impedance, gewogen naar $M_{ij}$**  --> _SumImp_
- **aggregeren over alt impedance, gewogen naar $M_{ij}$ (if alt_imp is provided, it automatically is used in $M_{ij}$)**
- aggregeren over euclidische distance (wellicht in de vorm van een formule, zodat je ook $distance^2$ zou kunnen aggregeren) (Chris geeft aan deze weinig prio heeft)
- **daarnaast wordt er ook een constante $d_{ij}$ verondersteld wanneer je binnen een origin naar destination reist ($i = j$), namelijk een theoretisch gemiddeld 0.23 km die je moet reizen om een random bestemming binnen je eigen 1km grid cel te bereiken, volgens Lewis. Dit betekent dat $d_{ij}$ wordt aangepast naar 0.23 km voor de netwerk afstand/euclidische afstand als $i=j$, en voor reistijd 0.23km / default speed). EDIT: kan nu al via interaction optie:  interaction(OrgZone_min,DstZone_min,..)**
- **het teller/noemer trucje kan ook in een enkele stap, wat de rekentijd voor de indicator voor Lewis door twee zal delen.**
- **ander soortige aggregaties: fractie van de trip loopbaar zijn (alt_imp <= loop_threshold) * T_ij. Of fractie van de trip over snelwegen (gewogen naar tijd of afstand?). Eventueel door alt_imp alleen imp waardes heeft op snelwegen, en de rest 0.**

**Comment by cjacobscrisioni** [comment]
**Aanleiding**
Uitbreiding van de interactie opties zou in eerste instantie nodig zijn omdat ik, voor een indicator, een interactiemodel zou willen runnen met een minder beperkende max impedance. Het betreft de indicator die ik bereken met de ComputeProxy module in de JRC network_methods configuratie. Die indicator gebruik ik binnen een model dat geschatte autokm per capita disaggregeert naar kleinere zones.

**Probleem**
Eerdere versies runde op 30 minuten cutoff; bij 60 minuten cutoff kwam ik geheugen tekort op mijn PC (en ook op een machine met een 126GB RAM + een 200Gb pagefile). Runnen binnen de EU-network config bood geen soelaas. Een van de problemen was dat ik de matrix een keer doorrekende en op basis van die indicator een groot aantal floating point attributen doorrekende met steeds andere distance decayed reistijden. Bij het doorrekenen van 1 distance decay functie per keer is het uiteindelijk gelukt binnen de network_methods configuratie.

**Noodzaak**
Eerste resultaten obv een grotere cutoff zijn inmiddels berekend. Mijn regressies voor het verklaren van autokm per capita doen het slechter met de indicator met 60 minuten cutoff dan met de indicator met 30 minuten cutoff; dus voor voortzetting van dit specifieke project stappen we waarschijnlijk sowieso terug naar 30 minuten.

Vraag is of er strategische noodzaak is voor een diepgravende aanpassing?
In de praktijk gebruik ik het bestaande geïntegreerde interactiemodel bijna niet, omdat vaak maatwerk-aanpassingen nodig zijn binnen de reistijdmatrix (transformatie van Dj of Impedance, typisch wanneer OrgZone_rel = DstZone_rel). Voor interactiemodellen is er meestal geen praktisch bezwaar tegen het opknippen van origin sets, om de resultaten later weer aan elkaar te plakken. Dus er is een praktische oplossing voorhanden die tot nog toe geen beperking is voor de modelspecificatie. Voor de indicator die ik aan het doorrekenen is opknippen per lidstaat zelfs wenselijk, omdat we er sowieso vanuit gaan dat het grootste deel van de dagelijkse trips binnen landsgrenzen blijft (zie ook Jacobs-Crisioni en Koomen, 2017). 

Zo gezien lijkt de aangedragen oplossing goed voor een theoretisch probleem dat niet praktisch relevant hoeft te zijn. Maar er komen een aantal projecten aan waarbij we mogelijk alsnog massaal interacties willen gaan berekenen met o's en d's op een fijne ruimtelijke resolutie. 

**Aankomende projecten met EU netwerk model**
Projecten die ik binnenkort wil gaan uitvoeren met de EU-netwerk configuratie:

- Schatting van reistijdverlies door congestie. Een EU-brede reistijdverlies schatting is nog erg ambitieus, we weten niet hoeveel mensen van waar naar waar reizen, en hoe laat ze dat dan doen. Dit paper van collega's zou als startpunt kunnen dienen om richting een antwoord te werken: https://www.nature.com/articles/s41597-020-00619-7 (zelf alleen nog diagonaal gelezen).

- Maakt de mate van self-rule van local authorities uit voor connectiviteit over gemeentelijke / regionale / landelijke grenzen? Daarvoor willen we een beperkte OD matrix maken obv random populated origins en destinations (10,000 origins met 100 destinations elk). Mogelijk wisselende random selecties als een soort van bootstrapping.

- Overbrengen van de methodes om settlement networks op te zetten, local centres te identificeren, en functional rural areas te definieren. Dit omdat 1) de huidige configuratie een aantal outermost regions en veerdiensten mist, en 2) we volgend jaar misschien naar cross-border vraagstukken willen gaan kijken.

**Comment by jipclaassens** [comment]
/Analyses/ComputeProxy/Results_per_distdecay/Geurs_VanEck_2003_general/Exports

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/dd8d4dde-ccb0-46f1-ac2f-4a7b2a8ba4d2)
