### ISSUE TITLE
Overview map too zoomed out

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#515]
When opening the configuration (e.g., LUS_demo) the starting value is too zoomed out.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/cf1d08ea-1206-4a15-8e99-3f84576ade0b)

**Comment by MaartenHilferink** [comment]
Cause and workaround:
The assumed size of the overview layer(s) is determined by the possible string length of the text-labels. Configuring a feature attribute and not a label attribute as background layer would prevent this.

**Comment by jipclaassens** [comment]
Volgens mij is dit issue nog niet opgelost:

<img width="1416" height="872" alt="Image" src="https://github.com/user-attachments/assets/292d6dd0-8914-401a-9e58-2e858622ab1e" />

Open een willekeurig item

**Comment by MaartenHilferink** [comment]
See #1107

**Comment by MaartenHilferink** [comment]
Als je de overview niet (meer) nodig hebt, kun je m ook uit zetten

**Comment by jipclaassens** [comment]
> See [#1107](https://github.com/ObjectVision/GeoDMS/issues/1107)

ah, het gaat hier om de start situatie. Wanneer je een laag voor het eerst opent zie je dus ook alles buiten NL. De implementatie als je vergenoeg inzoomt lijkt me nu goed.

**Comment by MaartenHilferink** [comment]
Max zoom-out:

<img width="479" height="512" alt="Image" src="https://github.com/user-attachments/assets/2019964d-b8c3-4167-a5d2-d5be9c2dd541" />

**Comment by MaartenHilferink** [comment]
Fixed on branch `refactor_ownership` (commit 3d5b5c11).

The overview map no longer zooms out past the extent of the background layer (a WMS layer's tile-matrix-set coverage) or, when that cannot be determined, past the range of valid coordinates of the world coordinate system (the world-crd-unit's `range()`).

Implemented as a cap in the overview ViewPort's update (`ViewPort::CalcMaxWorldRect()` + `GraphicRect::AdjustTargetVieport()`). Verified in the GUI on an RD map with an `ngr_layer` WMS background: overview zoom-out is now bounded.
