### ISSUE TITLE
add list uit lus demo werkt niet meer

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#517]

**Comment by mtbeek32** [comment]
Steps to Reproduce:

Configuration: 
OVSRV05:
C:\SourceData\RegressionTests\prj_snapshots\lus_demo\cfg\regression_test.dms

Request item:
Simulations/A1_GE/CaseData/Land/TotalExogenousLand

Results in errror:
ExprParser Error: 'add_list': unknown operator and no template or function was found with this name

**Comment by MaartenHilferink** [comment]
add_list werd herschreven naar add en is uit RewriteExpr.lsp verwijderd (net als mul_list, etc.) Het lijkt alleen (nog) in de LUS demo gebruikt. Voorgestelde resolutie: vervangen in lus_demo.
