### ISSUE TITLE
Paths in eventlog should be clickable (links)

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#518]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/aec85959-4490-4542-9891-871080abfa8c)

**Comment by eoudejans** [comment]
Eventlog text that has an item link with item full name encapsulated by double brackets: [[ ]] is now clickable in latest commit.
See:
 
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/cd793cfc-4b36-4686-934f-a802915db0da)

Closing issue as implemented.
