### ISSUE TITLE
Error: Numeric overflow when subtracting UInt8 values 1 from 0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#519]
This has to do with release 14.1.0

For 2UP I get on:
```
	attribute<string> prev_name     := MakeDefined(name[ID(.)-1b], 'StartingYear');
```
this error: 
`Error: Numeric overflow when subtracting UInt8 values 1 from 0`

What is the best way to solve this?
Change the unit from uint8 tot int8?
so:
```
	attribute<string> prev_name     := MakeDefined(name[ID(.)-1c], 'StartingYear');
```
This will works

I only like to know if this the royal road to solve this error?
It looks like maybe more units with value type of unsigned needs to be signed

**Comment by basvanbemmel** [comment]
and change

			unit<uint32> Iter: nrofrows = 8
			{
				attribute<string> name := 'I'+string(id(.));
				attribute<string> PrevPopName := MakeDefined(name[ID(.)-1]+'/NextPop', 'CurrState/Pop');
			}

to

			unit<int32> Iter: nrofrows = 8
			{
				attribute<string> name := 'I'+string(id(.));
				attribute<string> PrevPopName := MakeDefined(name[ID(.)-1i]+'/NextPop', 'CurrState/Pop');
			}

**Comment by MaartenHilferink** [comment]
Issue fixed en committed naar branch TowardsAnUrbanPreview_cal21 in rev 10248.
Deze branch vereist nu 14.1.0.

**Comment by basvanbemmel** [comment]
Maar blijft wel de vraag dat stel dat ik het wel backward compatible wil blijven houden heeft het dan nadelen om de units te transformeren van unsigned naar signed. Ik vermoed dat je wellicht in sommige situaties sneller tegen je range loopt.

Ik wil TowardsAnUrbanPreview_cal21 ook kunnen blijven runnen met oude exe's, defacto zou het dan nu betekenen (als ik dus gebruik  maak van sub_or_null) dat ik een extra branch nodig heb,

**Comment by MaartenHilferink** [comment]
Workaround met backward compatibility: 

attribute<string> prev_name  := (id(.) >= 1b) ? name[id(.) - min_elem( id(.) 1b) ] : 'StartingYear';

of

attribute<string> prev_name  := MakeDefined(name[ id(.) >= 1b ? id(.) - min_elem( id(.) 1b) : 0b  / 0b ], 'StartingYear');

**Comment by MaartenHilferink** [comment]
UInt8 -> int8 had wellicht ook gekund, maar voor palettes van int8 categorische waarden is er ook nog #509, dus voorlopig liever UInt8 blijven gebruiken. Negatieve zichtjaar of modeljaar nummers vind ik ook niet goed te vatten.
