### ISSUE TITLE
EventLog filter menu opens too narrow, and if closed leaves the EventLog too large

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#521]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/dd76348d-a214-4ea4-aa17-7f69a88b83ac)

Open filter:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/1bb9f4fa-4b93-4430-9a7e-3e45c6b5e921)

Resize event log:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5f88e5e8-56e6-4019-8737-446ff6254d01)

Close event log:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/a7def657-b493-46f8-9b17-e3947f2b3599)

**Comment by eoudejans** [comment]
The resizing of one dock seems to interact with the size of other docks. Proposed solution direction is to keep track of the width and height if applicable of dms helper windows.

**Comment by eoudejans** [comment]
I reverted to hard fixed size constraint on the width of the detail pages dock widget. This seemed to negatively interact and impose staleness on the other docks and their respective widgets. Furthermore I added a sizeHint to the DmsTreeview widget to be 300 logical pixels default width on startup.

The eventlog filter now opens up normally and closing the filter now again resizes the eventlog to its original size.

**Comment by eoudejans** [comment]
Issue seems resolved; along with some other tweaks to the docking areas overall.

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/371b7dc3-9e35-494f-837c-5bdd9c34c0fb)

Closing as completed.
