### ISSUE TITLE
Vesta hangs on numeric overflow error

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#522]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/523982de-39b5-40e7-8036-6bd94a366126)

Steps to reproduce:

configuration: ..\RegressionTests\prj_snapshots\VestaProductie_issue522\Runs\Regression_test.dms
request item: /RunContext/J2020/VestaRunData/Woning/Opwekking/eWP in table view

Errors appear in the event log, item does not become red, table column stays empty, no error in detail page and application seems to hang

**Comment by MaartenHilferink** [comment]
Unable to reproduce:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/1edeae5c-5c90-482e-95b1-1e2df36e30a3)
