### ISSUE TITLE
Numeric overflow when subtracting UInt16 values 1 from 0.

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#530]
Het lijkt erop dat ik een foutmedling krijg in 2UP op de legenda die verwijst naar Desktops die echter niet meer bestaat

Voor 2UP ga in 14.2.1 exe naar:
PD10257 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_cal21

/Scenarios/SSPs/SSP1/ProjectionDates/Y2010/NewState/Pop

Value Info
Active Item 

/Desktops/Default/ViewData/Scenarios/SSPs/SSP1/ProjectionDates/Y2010/NewState/Pop/Classifications/PopClass/ClassBreak/count 

/Desktops/Default/ViewData/Scenarios/SSPs/SSP1/ProjectionDates/Y2010/NewState/Pop/Classifications/PopClass/ClassBreak/count 
:= pcount(classify( /Scenarios/SSPs/SSP1/ProjectionDates/Y2010/NewState/Pop , /Classifications/PopClass/ClassBreak )) 

PopClass 
UInt32 
2 (0.001-1) 
Error: Numeric overflow when subtracting UInt16 values 1 from 0.
Consider using sub_or_null if your model deals with overflow as null values or consider converting the arguments to Int16.
/Desktops/Default/ViewData/Scenarios/SSPs/SSP1/ProjectionDates/Y2010/NewState/Pop/Classifications/PopClass/ClassBreak/count

/Classifications/PopClass/ClassBreak 
:= [ ... ] 

PopClass 
Float32 
2 (0.001-1) 
0.001 

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/dc151a39-8e7a-40f7-bdf8-369011834f08)

**Comment by basvanbemmel** [comment]
@MaartenHilferink : zou je wellicht kunnen aangeven hoe ik de syntax
attribute<Person_km2> North (gtopo) := TotalPopulationDensity2015[(gtopo/id) - point(1w, 0w, wpoint)];
dien te coderen om geen foutmelding te krijgen

**Comment by MaartenHilferink** [comment]
@Bas:
Voor alleen GeoDms 14 of later is het eenvoudigst:
```
attribute<Person_km2> North (gtopo) := TotalPopulationDensity2015[sub_or_null(gtopo/id), point(1w, 0w, wpoint))];
```

Teneinde backward compatible te zijn/blijven:
```
attribute<Person_km2> North (gtopo) := TotalPopulationDensity2015[
    gtopo/id) - point(min_elem(1w, pointrow(gtopo/id)), 0w, wpoint))
];
```
maar deze dupliceert de TotalPopulationDensity2015 van de eerste rij, want 0->0, 1->0, 2->1, 3->2, etc. terwijl sub_or_null resulteert in  0->null, 1->0, 2->1, 3->2; als dat een probleem zou zijn, doe dan:
```
attribute<Person_km2> North (gtopo) := TotalPopulationDensity2015[
   iif(pointrow(gtopo/id)>0w
      , gtopo/id) - point(min_elem(1w, pointrow(gtopo/id)), 0w, wpoint))
      , point(0w / 0w, 0w / 0w, wpoint))
   ];
```
