### ISSUE TITLE
Strange characters in html output statistics from command line

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#532]
a command like:
"C:\Program Files\ObjectVision\GeoDms14.2.1\GeoDmsRun.exe" 
/L"E:\LocalData\regression\log\GeoDmsTemp.txt"  
/S1 /S2 /S3 
C:\Users\Martin\tst\Operator\cfg\Operator.dms @statistics /Arithmetics/UnTiled/add/attr 
@file E:\LocalData\regression\log\t1742_command_statistics_stat.html

results in an html file with strange characters at the end of the file, see screendump:

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/c985bbee-7af9-4e9d-b8c8-ea720bf45a69)

The characters also differ for each run, this make that the full test on the results of the statistics fails most of the times.

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/3ea89f34-ef4b-4be4-bca4-a2b881aa50bd)
statistics (html) file was not properly \0 padded which caused variable line ending positions for the returned c-string. After adding the correct file closure the html file looks as follows:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/92d20c36-3eb7-4ce2-92ea-1af3d2599350)

Issue likely resolved.
