### ISSUE TITLE
GUI seems unresponsive in tasks with many eventlog messages

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#533]
Run 
`/WriteVariantData/Verblijfsrecreatie`

It takes many minutes, while the GUI is completely unresponsive. When finished, all log messages are dumped at once.

Disabling 	

`//eventlog_view->scrollToBottomThrottled();`

in DmsEventLog.cpp, it complete this item in 30 seconds.

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\RSOpen_issueGH533\cfg\main.dms`

**Comment by jipclaassens** [comment]
Breaking in VS for the scenario without eventlog scroll to bottom throttling always stops at posting the message to the eventlog model and issuing a scroll to bottom event, which in terms will redraw the eventlog. There was a throttling mechanism in place just for this scenario, however in light of update fluidity of the eventlog we disabled this mechanism.

Another observation is that the fss StorageManager posts a read eventlog message for each tile. In the past this was per 1M rows, the new default since the 8 series is 64K. See screenshot:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/21e85081-0622-4640-a1ee-d5a526ee413c)

Two proposed changes:
1. Change the frequency of log message produced by fss StorageManager from per tile to per dataset.
2. Reintroduce a throttling mechanism, this time based on the status of void MainWindow::begin_timing(AbstrMsgGenerator* /*ach*/) s_IsTiming singleton.

**Comment by MaartenHilferink** [comment]
TODO: checken dat er geen reentrancy optreedt vanuit eventlog->repaint() naar DataViews.
