### ISSUE TITLE
Unclear error for union data in classbreaks?

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#534]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/c09e1aca-8478-46e0-88d7-b8d393198db5)

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\RSOpen_issueGH533\cfg\main.dms`

`/BaseData/Verblijfsrecreatie/Per_AllocRegio/Corop/Zichtjaren/Y2050/Make_PerRegioUnit/Zichtjaar_Object_perHa`

**Comment by MaartenHilferink** [comment]
`union_data(targetDomain )`  zonder 1e attribuut maakt het onmogelijk om valuesUnit en valueType van het resulterende attribuut af te leiden. Een variant van union_data waarbij je zowel targetDomain als targetValuesUnit zou meegeven zou hier gewenst zijn.

**Comment by jipclaassens** [comment]
Diagnostische melding is nu verbeterd. Om te testen zou het fijn zijn als \C:\ProjDir\Jip\_Github_issues\RSOpen_issueGH533\cfg\main.dms nog zou bestaan.

**Comment by MaartenHilferink** [comment]
Diagnostische info is nu verbeterd:

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e79cf901-353c-4d22-abfc-276210b310e7)

**Comment by jipclaassens** [comment]
It still does not make me wiser. However, the data I want to visualise only container null values. So the classbreak/count cannot be calculated?

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/ae93e397-d866-4b5a-af6b-18559f0060ef)

**Comment by MaartenHilferink** [comment]
Reproduced with MicroTst.dms
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/5745eadd-9a4f-40a4-97e8-68050c4993b7)

**Comment by MaartenHilferink** [comment]
Fixed: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/255f27d1-d25e-44cb-9e1e-c8d872b03898)
