### ISSUE TITLE
Request: search for label property in name space, not only in root of domain

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#536]
Currently, GeoDMS only looks for a label in the root of the domain. And if you configure a label in a derived domain, it is not being found.

In the case of reading from storage, it is unwanted to explicitly configure the label property there. For example, if you read a Geopackage with units in it.  Then, you would have to configure the label attribute in the reading phase. 

It would be better to look for a label in the inherited subitems, just like geometry.

**Comment by jipclaassens** [comment]
@jipclaassens maak code voorbeeld

**Comment by MaartenHilferink** [comment]
Fixed for case with /RegioIndelingen/Gemeente referring to GeoPackage for derived attributes
