### ISSUE TITLE
long eventlog processsing

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#539]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/f205f1f7-c241-4aae-b53b-424c91698754)

**Comment by MaartenHilferink** [comment]
After 3h40 in TreeView update, 100k+ msg in eventlog block

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0b229a1a-4233-457e-805a-ff4e4b169879)

**Comment by MaartenHilferink** [comment]
Possible steps to reproduce: 
```
container Test_539 {
  unit<uint32> EventLogLine := range(uint32, 0, 100000);
  parameter<bool> CalcThing := true;
  container result := FenceContainer(CalcThing, 'LogMsg '+string(id(EventLogLong)));
}
```

**Comment by eoudejans** [comment]
The following example creates a callable fence container. Issue reproducible.

```cpp
unit<uint32> EventLogLine := range(uint32, 0, 100000);
container calculation
{
	parameter<uint32> A := 1;
	parameter<uint32> B := 2;
	parameter<uint32> C := A+B;
}
		
container result := FenceContainer(calculation, 'LogMsg '+string(id(EventLogLine)));
		
```

**Comment by eoudejans** [comment]
I've reworked the eventlog update mechanism and added two ways the eventlog will update:

1. the eventlog will redraw directly after receiving a new message when it has not been updated for 5 seconds
2. the eventlog will post a redraw event 5 seconds after receiving a new message.

Note that the redraw on a newly received message does not have to lead to a redraw of the eventlog as the new message may be filtered out and is no candidate for visualization.

At first sight the speed seems to greatly improve for simple configurations run in the gui.

**Comment by MaartenHilferink** [comment]
recent issue when repaint is called and main message pump hasn't been able to do its thing again:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7e24d00d-4ce0-478d-a9e8-a541cf45a227)

**Comment by jipclaassens** [comment]
@eoudejans maak nieuw issue van dit laatst genoemde issue van Maarten en close deze

**Comment by eoudejans** [comment]
Created issue #558 based on previous comments, closing this issue as implemented.
