### ISSUE TITLE
Memory usage info in Statusbar (Committed xxx Max Committed xxx; allocator xxx Highest allocator xxx

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#540]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/14cd7f3b-76d1-4d1d-b896-b2f6ed20c307)

**Comment by MaartenHilferink** [comment]
possible format: Committed xxx Max Committed xxx; allocated xxx Highest allocated xxx

**Comment by jipclaassens** [comment]
duplicate of #537
