### ISSUE TITLE
Add memory usage to View>Calculation Times

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#541]

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/19cf825a-1b79-40f1-95c9-cee7f0afd98f)

**Comment by MaartenHilferink** [comment]
En onderin in de status-bar:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/89c47c97-b2ab-4867-a9bc-8dc98c931609)
