### ISSUE TITLE
recent file list, remove from list removes always the last config

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#546]
The remove option in the recent file list now always seems to remove the last configuration, in stead of the selected one.

Additional related questions:
1) remove might be interpreted as deleting the configuration, remove from list is a better label
2) pin does not yet work, it is better to disable this option until it works
3) it would be nice to keep the blue selection bar after opening the pop-up menu, to make it clear which row is selected.

**Comment by eoudejans** [comment]
Issue reproducible. An eventfilter to catch right-mouse click events is installed using installEventFilter. Which in terms is called on the associated menu widget for a QAction. This menu widget is the Qmenu of files menu and **not** the menu widget of the individual recent files entry.

**Comment by eoudejans** [comment]
Solution to be implemented is to properly retrieve the widget associated with the recent files file menu entry widget and correctly set the eventFilter for right-click mous events.

**Comment by eoudejans** [comment]
Right mouse click events are processed using eventFilter at DmsRecentFileEntries. This filter is set for every DmsRecentFileEntry, however there is one eventfilter active at one time. This meant that tha last item was always the item to be deleted, irrespective of what menu item that was right-clicked on.

Fixed in latest commit.

**Comment by eoudejans** [comment]
When a newly opened config was already in the config list, it is properly moved to the first (1.) position. However in case the config was not in the list it was moved to the end of the list. Changed this in latest commit. Issue likely resolved, to be further tested.

**Comment by eoudejans** [comment]
During creation of the right mouse click context menu, a connection was set that connects the widget to the remove (and later pin) buttons see:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/55f44cc5-dfb5-49c9-846a-19db00942726)
This connection was always slotted to the last recent file list item. This has been changed to the last active recent file list item.

Closing issue as fixed.
