### ISSUE TITLE
Request: new impedance_matrix variant where you specify the maximum number of OD-pairs

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#548]
In order to skip the 'counting' phase.

**Comment by jipclaassens** [comment]
related #514

**Comment by jipclaassens** [comment]
Interesting for you @cjacobscrisioni

**Comment by MaartenHilferink** [comment]
For proper functioning of the (Multi threaded) impedance matrix calculation, it needs a maximum number of destinations *per* origin.
