### ISSUE TITLE
Add horizontal scroll bar to tree view

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#549]
And change the behaviour like it was in the old GUI. If I expand a container more to the right than the current view of the treeview, it should automatically scroll to the right.

![Screenshot_20231016-210744.png](https://github.com/ObjectVision/GeoDMS/assets/48675272/e9955302-9679-4537-a56a-3fd0e5fabdf6)

**Comment by eoudejans** [comment]
Horizontal scrollbar has been implemented, see:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/04f82457-8a89-47fd-9cce-e08a21eaae86)

Closing issue as completed.
