### ISSUE TITLE
Save contents of value info

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#553]
In the Delphi GUI, the Value Info was a Detailpage. With the generic functionality to save a Detailpage, it was possible to save the contents of the Detailpage as a txt file, which could be used in the test process.

In the QT, the value info now is a separate dialog, it would be nice to have an option as well to save the contents as txt file

**Comment by eoudejans** [comment]
Implemented in latest commit. To be tested at the gui scripting side using: SaveValueInfo <filename> in a similar fashion as the SaveDetailPage <filename> gui command. See https://github.com/ObjectVision/GeoDMS/wiki/Gui-scripting for more info on available gui scripting commands and their usage.

**Comment by eoudejans** [comment]
Closing issue as implemented.
