### ISSUE TITLE
Valluisa test can be run from GUI, but results in error from GeoDMSRun

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#554]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/962f08af-76d8-4669-bc7e-eb9f5642a24d)

Steps to reproduce:
OVSRV05

Configuration: 
C:\SourceData\RegressionTests\prj_snapshots\100m_DynaPop\cfg\StatusQuo.dms 
request item: t810_ValLuisa_Czech_LU_POP/result_html

in GUI, this goes fine, in the GeoDMSRUN, the following error is generated:

Failure: Check Failed Error: valueRangePtr
C:\dev\GeoDMS_2\tic\dll\src\DataArray.h(320):

This seems to be a GeoDms internal error; contact Object Vision or report this as issue at https://github.com/ObjectVision/GeoDMS/issues
/Runs/Czechia/CaseData/JrcFactorData/TiffData/Erodibility

Context:
Thread 8
1. while in TreeItem::ReadItem( /Runs/Czechia/CaseData/JrcFactorData/TiffData/Erodibility: AbstrDataItem )1

**Comment by MaartenHilferink** [comment]
Waarschijnlijk veroorzaakt door deze aanpassing:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/48c20f5b-dbfe-4e4f-a0c4-4df910e0395a)

**Comment by mtbeek32** [comment]
Mooi dat je het (waarschijnlijk) hebt gevonden. Maar de aanpassing zal vast een reden hebben gehad.

Verwacht je andere issues als je dit weer terug zou zetten?
