### ISSUE TITLE
Groupby does not give the expected result

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#556]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/bf3864fa-57b3-413a-8a8f-d0edbbe99209)

So, I do as requested:

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8103e2d8-ea70-423c-84ff-1a312498e08b)

The aggregate by option should also give the count or sum option

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/276c586c-636c-4521-9876-953d8a215970)

The domain here is a ipoint grid domain.

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/1bf08e5f-95a7-4ec3-9fc0-0fd54b5e2077)

In compactedadmindomain = uint32 domain it does give more aggregation option. But summing the id is also irrelevant. I just want to count the subsector_rel.

**Comment by MaartenHilferink** [comment]
Microtest open /DistTo in dataview en aggregeer er op: Traceback wordt gesumd, maar dat kan niet met UInt4 values:

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a28f8fb8-9190-408f-84d3-8631a7f64c47)

**Comment by jipclaassens** [comment]
Make list of which value types should give what aggregation options:

**Comment by MaartenHilferink** [comment]
aanvulling:
- id (eerste) column: default altijd count, ook al is domein integer of categorical
- points en sequences van points: default bounding box (= combinatie van lower bound en upper bound)

**Comment by MaartenHilferink** [comment]
Frequency table suggestion:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4ef3e576-df92-4f80-a31a-31b1160ee2ba)

(Apple (25), Banana (30), Orange (15), Strawberry (20), Total (90)

**Comment by MaartenHilferink** [comment]
Default resultaat op Aggr op categorische rasterdata is nu dit:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/12127c5b-80eb-4158-9b8d-2c8c73cf575e)

**Comment by MaartenHilferink** [comment]
Of dit:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/2dc8f64e-7018-413f-9083-3682a94fdb04)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/19c5c7d9-10e1-4565-a5b4-7d67d01450ef)

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ffcb1a78-01f0-4bde-96f7-241196f99499)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/897d81ce-3583-4d76-a320-d28382c68e82)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/93b74225-6f5a-4b04-ac04-6c1b619f68a0)
