### ISSUE TITLE
WorldMollweide EPSG:54009 to WGS84 EPSG:4326 tilted result

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#557]
Nadere instructie volgt nog

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/ffcf709c-4679-4319-8542-540632862aa8)

**Comment by basvanbemmel** [comment]
Dit heeft overigens best wel prio. Gisteren overleg met Jonathan er is nu echt besloten om 2UP-output te gaan gebruiken voor Image. 1 van de actiepunten (voor 2UP) is om ook de nieuwe GHSL te gaan gebruiken van het JRC (https://ghsl.jrc.ec.europa.eu/download.php GHS-BUILT-S 100 mtr MollWeide). Ik wil dit graag naar WGS84 zetten tbv uitlevering aan Jonathan. Ik zie nu echter dat het tonen in WGS84-projectie niet goed gaat (zie screendump).


Hierbij de gegevens:
PD10284 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_cal21
PD 10283 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/2UP
item
/Preprocessing/Urban2023/BuiltUpPresence_R2023_Create/Y1975/TotalGridData
duurt op 192GB systeem ongeveer 4 minuten

Ik heb al het een en ander geprobeerd o.a. config.ini met
[general]
ConfigPointColRow = 1

maar ook 
[general]
ConfigPointColRow = 0

Ik heb ook al diverse codetchnische zaken geprobeerd maar nog geen soelaas.


India zit boven Noorwegen
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/301f28b0-db66-4381-960e-c75195652ae8)

**Comment by eoudejans** [comment]
First observation is that in Input.dms the WorldMollweide format property is specified as being:
unit<dpoint> WorldMollweide: Format    = "EPSG:54009";

Which does not exist, it should be ESRI:54009, as ESRI is the authority of this projection code. See for instance https://epsg.io/54009

**Comment by basvanbemmel** [comment]
Is er al progressie te melden? Er is eigenlijk wel haast bij. Ik kan de berekening ook doen in ArcMap maar heeft niet mijn voorkeur.

**Comment by eoudejans** [comment]
Zojuist gepushed, was een zoektocht maar ik denk dat het nu naar behoren werkt.

**Comment by basvanbemmel** [comment]
Is opgelost ja, dank


![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/f695f88b-a621-4dbc-8c21-28e7c5555a3c)

**Comment by eoudejans** [comment]
Super, dan sluit ik dit issue.
