### ISSUE TITLE
Title-tabs of DataView are sometimes not drawn or updated well after resizing events.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#559]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0411174d-f653-46b5-bdc8-69d41e70e448)

Steps to reproduce:  
- run Unit test.
- Do calculation, open a DataView and then the View calculation times window, close the latter and an empty tab appears.
- Open "Edit palette" from mapview, second right click on the counter sometimes results in a frozen pop-up menu for which clicking closes the Palette editor

**Comment by eoudejans** [comment]
In light of experimenting with the update mechanism of dms views, and the negation thereof several experimental settings and adjustments got leaked into the GeoDmsQt branch. Specifically introducing negation of paint events for the dms mdi subwindow caused weird painting behavior (or lack thereof).

These experiments are reverted in latest commit, which solves this issue. Closing issue.
