### ISSUE TITLE
Toggle layout of the Map View viewport does not show the correct icon.

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#561]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/f964f081-6cfd-4727-ab4a-894ec09f00f2)

After toggling the tool icon is not changed anymore.

**Comment by eoudejans** [comment]
Solved in latest commit. State rollover for icon was determined in two places, which was a conflict in logic, which caused the state never to rollover more than once.

Closing issue as implemented.
