### ISSUE TITLE
Google zoekresultaten ov.nl herindexeren

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#562]
Google > Ruimtescanner
https://www.google.com/search?q=ruimtescanner&rlz=1C1ONGR_nlNL993NL993&oq=ruimtescanner&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQABiiBDIHCAIQABiiBDIHCAMQABiiBDIHCAQQABiiBDIGCAUQRRg9MgYIBhBFGDwyBggHEEUYPdIBCDIyNjNqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

Kom je hier:
https://www.geodms.nl/Ruimtescanner

In naar de .info
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/d3deca24-46ef-4e5b-8530-a0275f826182)

**Comment by eoudejans** [comment]
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll
