### ISSUE TITLE
Convert operator results in incorrect conversion in several scenarios

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#563]
Following issue #557 it became apparent that the convert operator, or implicit conversions between value units in some scenarios return incorrect results.

Scenario 1:
See #557 for more details, where EPSG:54009 to WGS84 was configured as such:

```cpp
attribute<Input/gtopo> gtopo_rel := convert(org_rel, Input/gtopo);
```

Separating the conversion steps made the conversion return the correct values:

```cpp
attribute<input/WorldMollweide> org_rel_to_mollweide := convert(org_rel,input/WorldMollweide);
attribute<Input/latlong> latlon_point := convert(org_rel_to_mollweide, Input/latlong);
attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);
attribute<Input/gtopo> gtopo_rel := convert(latlon_point_swapped, Input/gtopo);
```

Note that Input/gtopo has wpoint and input/WorldMollweide has dpoint as base unit.

Simplified examples will be provided.

**Comment by jipclaassens** [comment]
```
container Issue_563
{
	unit<fpoint> rdc_meter_base   : DialogData = "ngr_layer", SpatialReference = "EPSG:28992";
	unit<fpoint> rdc_meter        := range(rdc_meter_base, point(y_min, x_min), point(y_max, x_max));
	unit<Float32> Meter := BaseUnit('m', float32);
	
	parameter<Meter> x_min := 0[Meter];
	parameter<Meter> x_max := 280000[Meter];
	parameter<Meter> y_min := 300000[Meter];
	parameter<Meter> y_max := 625000[Meter];
	
	parameter<Meter> gridsize := 25[meter];
	parameter<int16> nr_cols := int16((x_max - x_min) / gridsize);
	parameter<int16> nr_rows := int16((y_max - y_min) / gridsize);
	
	unit<spoint> rdc_25m :=
		range(
			 gridset(
				 rdc_meter
				,point(-gridsize, gridsize, rdc_meter)
				,point(y_max, x_min, rdc_meter)
				,spoint
			)
			,point(0s, 0s)
			,point(nr_rows, nr_cols)
		),	DialogData = "rdc_meter";
		
	unit<uint32> test : nrofrows = 1
	{
		attribute<ipoint>         ipoint_attr := const(point(5i, 2i, ipoint),.);
		attribute<rdc_25m> spoint_cast := ipoint_attr[rdc_25m];
	}
}
```

**Comment by eoudejans** [comment]
Simplified example also reproducible.

**Comment by eoudejans** [comment]
Expected behavior for the simplified example would be the direct interpretation of the input coordinates as rdc_25m.

What actually happens is a non unit m_PreRescaler applied to the coordinate(s):

**setting of m_prescaler**
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/ba515512-0b50-4b33-8546-63dae3fff428)

**application of prescaler** in OperConv.cpp line 654:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/05f55aa3-ae01-48c5-89b8-2fb646c8ef7f)

**Comment by eoudejans** [comment]
From now if there is no spatial reference during conversion in the from point, the prescaler will be zeroes. See results:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/75f9a91a-a592-471f-89f9-b0317db3075b)

**Comment by eoudejans** [comment]
The main culprit was the non-swapping of coordinates by the conversion operator, which this line fixed:
`attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);`

This narrows down the workaround from:

```
attribute<input/WorldMollweide> org_rel_to_mollweide := convert(org_rel,input/WorldMollweide);
attribute<Input/latlong> latlon_point := convert(org_rel_to_mollweide, Input/latlong);
attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);
attribute<Input/gtopo> gtopo_rel := convert(latlon_point_swapped, Input/gtopo);
```

To:

```
attribute<Input/latlong> latlon_point := convert(org_rel, Input/latlong);
attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);
attribute<Input/gtopo> gtopo_rel := convert(latlon_point_swapped, Input/gtopo);
```

**Comment by eoudejans** [comment]
Incorrect interpretation of axis order arrose from using **shp2dms_order** after coordinate transformation in OperConv.cpp. This incorrect behavior originated from the assumption that all coordinate transformations result in the ShapeFile whitepaper col-row axis order. Where to give a counterexample, EPSG:4326 has north, east or row-col order, which will be misinterpreted by the shp2dms_order transformation.

A new function is added that does take into respect, if possible, the destination projection after coordinate transformation its axis order.

**Comment by eoudejans** [comment]
To be tested:
- regression tests using coordinate transformation
- polygon clipping

To be added:
the src projection can also be in the wrong order delivered to gdal/proj. Here the inverse logic can be applied.

**Comment by jipclaassens** [comment]
I was under the impression that this code would now work, is that the case?

```
attribute<wgs84>            Geometry (poly);
attribute<WorldMollweide>   Geometry_MW (poly) := convert(Geometry, WorldMollweide);
attribute<WebMercator>      Geometry_WM (poly) := convert(Geometry, WebMercator);
```

However:

For WebMercator:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/89ebf764-0340-44d4-954c-8d3cf1802177)

For Mollweide:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/9ef460ce-0fdf-4492-91a0-59f418d0226b)

**Comment by MaartenHilferink** [comment]
> The main culprit was the non-swapping of coordinates by the conversion operator, which this line fixed: `attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);`
> 
> This narrows the workaround down from:
> 
> ```
> attribute<input/WorldMollweide> org_rel_to_mollweide := convert(org_rel,input/WorldMollweide);
> attribute<Input/latlong> latlon_point := convert(org_rel_to_mollweide, Input/latlong);
> attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);
> attribute<Input/gtopo> gtopo_rel := convert(latlon_point_swapped, Input/gtopo);
> ```
> 
> To:
> 
> ```
> attribute<Input/latlong> latlon_point := convert(org_rel, Input/latlong);
> attribute<Input/latlong> latlon_point_swapped := point(PointCol(latlon_point), PointRow(latlon_point), Input/latlong);
> attribute<Input/gtopo> gtopo_rel := convert(latlon_point_swapped, Input/gtopo);
> ```

@erikthehero : can you edit this example and specify what org_rel is, and why we still need to swap coordinates ?

**Comment by jipclaassens** [comment]
```
unit<uint32> Local_Units //Countries 
: StorageName = "%NetworkModelWorld_DataDir%/Regions/gadm_410.gpkg"
, StorageType = "gdal.vect"
, StorageReadOnly = "true"
{
	attribute<wgs84>            Geometry (poly);
	
	attribute<store_Countries>  store_countries_rel  := rlookup(Country, store_Countries/values);
	attribute<Continents>       continents_rel := rlookup(AsItemName(continent_edit), Continents/name);
	attribute<string>           continent_edit := continent == 'Australia' || continent == 'Oceania' ? 'Australia_Oceania' : continent;
}

unit<uint32> test_sub := select_with_attr_by_cond(Local_Units, Local_Units/Name_0 == 'Netherlands')
{
	attribute<wgs84>             geometry_WGS84          (poly) := geometry;
	attribute<dpoint>            geometry_WGS84_Reversed (poly) := Convert_wgs84_xy_to_yx/geometry_yx;
	attribute<WorldMollweide>    geometry_MW             (poly) := convert(geometry_WGS84_Reversed, WorldMollweide);
	attribute<WebMercator>       geometry_WM             (poly) := convert(geometry_WGS84_Reversed, WebMercator);
	
	attribute<float64>           area_wgs          := area(geometry_WGS84, float64);
	attribute<float64>           area_wgs_reversed := area(geometry_WGS84_Reversed, float64);
	attribute<float64>           area_wm           := area(geometry_WM, float64);
	attribute<float64>           area_mw           := area(geometry_MW, float64);
	
	container Convert_wgs84_xy_to_yx : DisableStorage = "true"
	{
		unit<uint32> border_points := sequence2points(geometry_WGS84)
		{
			attribute<wgs84> point_yx := Point(PointCol(point), PointRow(point), wgs84);
		}
		unit<uint32> Country_ui32  := range(uint32, 0, uint32(#..))
		{
			attribute<wgs84> Geometry_yx (poly) := points2sequence_pso(border_points/point_yx, border_points/sequence_rel[Country_ui32], border_points/ordinal);
		}
		attribute<wgs84> Geometry_yx (poly, ..) := union_data(.., Country_ui32/Geometry_yx);
	}
}

```

**Comment by eoudejans** [comment]
Indeed this example does not work yet, here the coordinate transformation **from** side is wgs84 or EPSG:4326 whereas the current implementation only works on the **to** side. To be implemented, but the logic will be very similar and an extension to the current implementation.

**Comment by jipclaassens** [comment]
Also see this conversion in https://github.com/ObjectVision/NetworkModel_World/issues/18

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/1a2afdd0-5de5-4399-88e2-b9430d05c7f1)

**Comment by jipclaassens** [comment]
OVSRV6:
C:\ProjDir\Jip\_Github_issues\NetworkModel_World_issue563\cfg\main.dms

```
/Analyses/Create_Centres_Catchments/Australia_Oceania/inGrids_centroid_wgs
/Analyses/Create_Centres_Catchments/Australia_Oceania/inGrids_centroid_wm
```

```
X=15910553.6; Y=-1613332.75; ZL=0.00282524034
```

**Comment by eoudejans** [comment]
Using the following code selects only points that are null after conversion to mollweide but defined in EPSG:4326.

```
unit<uint32> unique_nulls_in_wm := select_with_attr_by_org_rel(inGrids_centroid_wgs, !IsNull(inGrids_centroid_wgs) && IsNull(inGrids_centroid_wm))
{
	attribute<BaseProjection> points := inGrids_centroid_wgs[org_rel];
}
```

Results in the following points:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/49095a0c-abc4-4d5e-904d-c0e0712fdd17)

Left hemisphere Islands:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/a600271c-874e-4d46-acde-753e2d783f33)

Right hemisphere:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/26de8e7b-4df7-4507-b6f7-ed9e72e0c121)

**Comment by eoudejans** [comment]
Confirming that the following cases are working after the latest supplemental fixes:
/issue563/test_sub/geometry_MW_14_9_0
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/39fdbf86-cf98-444e-9bcc-55a5ac71e821)

/issue563/test_sub/geometry_WM_14_9_0
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/ff5da0c9-10a6-448a-94b1-77110b43120f)

/issue563/test_sub/geometry_RDC_14_9_0
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/ab0056a5-d69e-409c-8313-519aed51c4b6)

**Comment by eoudejans** [comment]
> Also see this conversion in [ObjectVision/NetworkModel_World#18](https://github.com/ObjectVision/NetworkModel_World/issues/18)
> 
> ```
> attribute<WebMercator>     inGrids_centroid_wm_old (inGrids) := convert(point(PointCol(inGrids_centroid_wgs), PointRow(inGrids_centroid_wgs))[BaseProjection], WebMercator);
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/48675272/294535981-1a2afdd0-5de5-4399-88e2-b9430d05c7f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDMzNTUsIm5iZiI6MTcwNDkwMzA1NSwicGF0aCI6Ii80ODY3NTI3Mi8yOTQ1MzU5ODEtMWEyYWZkZDAtNWRlNS00Mzk5LTg4ZTItYjk0MzBkMDVjN2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE2MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZmYwZDk5NjliODM5ZjRiOTY0NzE4Y2NhYjExOTVjYzU0ODA1YzEwYTRhY2UxOTg4ODc0OTkzZTg2MmJjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rLhWxh3cEc8RotoXtuLClgpyL7jXF-V8X5De7KdwYMo)

I can confirm that the workarounds for area calculations no longer work, which is a good thing, direct conversion without swapping coordinates is the way to go:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/851212c0-ac8b-4f43-bd12-b0020d3a195d)

**Comment by eoudejans** [comment]
> Note that in 14.8.0 geometries should always be represented internally as (row, col) == (y, x) == (Lat, Long) == Geometry for drawing, area calculation etc. The geometry_reversed == LongLat.
> 
> ![image](https://private-user-images.githubusercontent.com/48675272/294471321-acf45575-c3b0-4040-9b3d-43d091a5bacd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDMzNTUsIm5iZiI6MTcwNDkwMzA1NSwicGF0aCI6Ii80ODY3NTI3Mi8yOTQ0NzEzMjEtYWNmNDU1NzUtYzNiMC00MDQwLTliM2QtNDNkMDkxYTViYWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE2MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNGQwMWI0MjdhYTIxYWZhNTcwZmY0ZmM2YjFkYTU4MjdmYjEzZDAyN2FhNjRlZjljNDBiYzhhYjRkODUxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MVh7qvV0BNcdQuAr9LaACKuB5n24u9WB6iqvZiLSIwY)

I can confirm that the workarounds for area calculations no longer work, which is a good thing, direct conversion without swapping coordinates is the way to go:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/06a8af46-0f1e-4bd6-ab58-820ccbd64037)
