### ISSUE TITLE
Background layer sometimes not added to map view

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#564]
Happens quite often when iteratively working with the GUI.

- wms is not added to the layer control
- alt+r doesn't remedy it
- restart the application, then it is fixed again

**Comment by eoudejans** [comment]
To be checked:
When in the situation that the background layer does not show up, is the background layer for a completely different item also not being added to the layer control and thus not visible?

**Comment by jipclaassens** [comment]
> @jipclaassens To be checked: When in the situation that the background layer does not show up, is the background layer for a completely different item also not being added to the layer control and thus not visible?

Yes, indeed. Another item in a new map view also doesn't get the wms.

**Comment by MaartenHilferink** [comment]
Reproduction of no wms_layer when expected (after commits of yesterday that were related to #635 ):
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/bb42cd60-eca3-42b4-bd06-dcbf649c58ae)
