### ISSUE TITLE
Point attributes have limited statistics

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#565]
See currently listed statistics:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/807572ad-6156-408e-b31a-d3a5f58b8db5)

This could be expanded, for instance by:
- a min/max per coordinate component
- number of null per coordinate component

This would greatly help in debugging of point attributes

**Comment by jipclaassens** [comment]
- value counts now do not have the number of distinct values
- and no entrophy measure

**Comment by MaartenHilferink** [comment]
Implemented for point attributes:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7ffef409-307c-4c6b-8f4f-d97cc3769445)

**Comment by MaartenHilferink** [comment]
En point sequences ....
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a341d726-f902-4acb-86e6-74d2222dbcd1)
