### ISSUE TITLE
OS Structured Exception on pop-up menu option: FindNext Value (Ctrl-F), BrushColor column in PaletteEditor

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#566]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/b029fffa-fb3c-448f-b75a-b860b2c424f3)

steps to reproduce:

version GeoDms 14.5.0
configuration: MicroTst.dms
request item /DistTo in MapView
Activate with Edit Palette pop-up menu option in Legend on DistTo layer the PaletteEditor
Active pop-up menu option: FindNext Value (Ctrl-F) :... on BrushColor column with /DistTo in clipboard,

GUI crashes

**Comment by mtbeek32** [comment]
See also #567

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by eoudejans** [comment]
Crash is result of nullptr dereference in  DataItemColumn::FindNextValue(SharedStr searchText) line ~1000.  

GetActiveTextAttr() was dereferences but can return nullptr. 

Solved by splitting statements into separate variables and checking for nullptr and issueing appropriate warning, see:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7de4343c-c484-4b2c-b4bb-ec392f95938d)

Closing issue as solved.
