### ISSUE TITLE
PaletteEditor: split and merge classes result in errors

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#567]
steps to reproduce:

split issue;
version GeoDms 14.5.0
configuration: MicroTst.dms
request item /DistTo in MapView
Activate with Edit Palette pop-up menu option in Legend on DistTo layer the PaletteEditor
Active pop-up menu option: Classes>Split :... on LabelText column. The following situation appears:

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/47c8a97a-aaa1-4b6c-a844-b6e0c5451cb4)

merge issue;
reopen and peform the same steps. Only choose Classes>Merge in stead of Split. The following situation appears:
 
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/ba4ff352-34eb-42c7-b8b1-5ff1a6ea7f97)

**Comment by mtbeek32** [comment]
See also #566

**Comment by eoudejans** [comment]
See also #576

**Comment by eoudejans** [comment]
Suggested change: remove split and merge option
