### ISSUE TITLE
max operator werkt niet als verwacht en gedocumenteerd met null values in 14.4.2.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#568]
documentation: :https://github.com/ObjectVision/GeoDMS/wiki/Max
met name: 
* max(a) results in a [parameter](https://github.com/ObjectVision/GeoDMS/wiki/Parameter) with the maximum of the non [null](https://github.com/ObjectVision/GeoDMS/wiki/Null) values of [attribute](https://github.com/ObjectVision/GeoDMS/wiki/Attribute) a.

Ik dacht dat dit ook zo in de unit-test en regressie test wordt vastgesteld, die voor de gepubliceerde 14.4.2 zijn uitgevoerd; maar nu lijkt dat net niet het geval, zie onder Martin's bevindingen.

Desalniettemin:

Hoi Maarten,

Ik kwam een issue tegen waarbij de max operator niet functioneerde zoals ik had verwacht. Bij de invoer van nieuwbouwnormen wordt de hoogste norm gekozen uit alle die gelden dat jaar. Echter toen er twee normen stonden waarvan de eerste isolatieniveau 4 en de tweede een null, geeft de max functie een null terug. Dit in GeoDMS 14.4.2. Als ik een makedefined toevoeg geeft de functie wel de juiste uitkomst, hierbij de links naar 2 commits, in de onderste komt het issue voor. Mocht je meer informatie nodig hebben of het niet kunnen reproduceren, laat maar even weten.

Item: /TussenResultaten/R2_2022/ZichtjaarBeleid/NieuwbouwNorm/BouwdeelNorm (in oudere commit, zie ook BouwdeelNorm_i)

Branch: Sawec-WP5-v14.0.0, commits:

3e48fb33ecf19819efd94a1d8526a4c72c20f85f <- met fix

02d97d1b6c56b0887f21116f6da1866f4fce00a4 <- zonder fix

Groeten, Folckert

Todo: 
* reproduceren, 
* analyseren wat er gebeurt en 
* evt fixen.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a43802c0-b6cb-423e-aa05-e18490e8799e)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7cc69618-a604-4e9c-b1ed-80442413121a)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/5b27dec4-26bb-4728-8db3-4486481c7356)
 in componenten:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9e0a479e-f51b-45cc-a1de-250b3af08d4f)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/644a4700-f15c-4fcf-9341-18951caa49a5)

Het lijkt er inderdaad op dat max([4, null]) resulteert in null in 14.4.2.

**Comment by MaartenHilferink** [comment]
14.3.0 evenzeer:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/f699f3c8-3255-4833-b59d-7eef2311c7ea)

**Comment by mtbeek32** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/593546a8-78a7-458f-afd2-8d3dd8f13810)

In 12.0.0 the value for the calculated cell 3,3 was 200
In 14.5.0 the same cell with the same calculation rule results in the value null.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ca8bbdaa-947c-43e9-846e-ea5f877653de)

**Comment by mtbeek32** [comment]
in 13.4.2 the value for cell 3,3 was like in 12.0.0 still 200.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/b01c36b6-c35f-4a54-abae-320aa09ae435)

**Comment by MaartenHilferink** [comment]
Fix zal beschikbaar zijn in 14.5.0
