### ISSUE TITLE
string: yyyy-mm-dd hh:mm:ss text shown in eventlog in stead of actual date/time

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#570]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/d145a2bc-ddbf-40a0-82c5-d8a99c376424)

**Comment by eoudejans** [comment]
Solved in latest commit:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/1f97fb8e-fc0f-44b5-8e77-515ace75335f)

Incorrect std::strftime format parameter used see docs:
https://en.cppreference.com/w/cpp/chrono/c/strftime

Solved by changing 
```cpp
return std::strftime(buff, n, "yyyy-mm-dd hh:mm:ss", tm); 
```

To 
```cpp
return std::strftime(buff, n, "%Y-%m-%d %H:%M:%S", tm);
```
In DebugStream write_time_str.
