### ISSUE TITLE
Request: directed connected_parts to find subnetworks due to one-directional roads

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#574]

**Comment by jipclaassens** [comment]
Directed connected_part is **not** an option since it requires a starting point. Which is arbitrary.

A possible approach could be to perform a Dijkstra analysis to calculate the number of reachable destinations for each origin. We can assume that most origins can reach (almost) all destinations. So much lower numbers indicate problematic cases. This way, we can identify the problematic cases. 

However, how can we mitigate the problems? We cannot think of a generic solution (yet) that we can do to clean up the network. By 1) deleting the subnetwork, like we do with connected_parts(), or 2) overruling the one-directional road, which is the bottleneck.

**Comment by cjacobscrisioni** [comment]
Impossibility of a directed connected_part(): Fair point.

Would it be an option to identify which nodes are reachable within x km as a ratio of total nodes in a x km radius? If the ratio of reachable vs present nodes is very low, I would 1) try and force all links connected to the reachable nodes to bidirectional; 2) ditch the entire subnetwork if all links within radius are already bidirectional (and the problem persists?).

**Comment by MaartenHilferink** [comment]
I think it would first be good to better identify connectedness in a directed network (aka digraph). 
A relevant concept here is a Strongly Connected Component (further: SCC), which is a set of nodes which are all reachable towards each other according to the digraph. If we label maximal SCC's, similar to `connected_parts`, than all other links are, by definition, connections between different SCC's and cannot form cycles and therefore form a Directed Acyclic Graph (aka DAG). I therefore propose to implement a  `strongly_connected_components` function that relabels Nodes to SCC-identifiers and, additonally provide a F1, and F2, both: DAG_link ->SCC that represent from which SCC you can directly travel to which other SCC. 
This enables a user to identify large SCC's and how they are related and related to other smaller upstream or downstream SCC's.

Possible algorithms for identifying SCC's (according to ChatGPT, didnt check it yet):
- Tarjan’s algorithm
- Kosaraju's algorithm

**Comment by cjacobscrisioni** [comment]
@MaartenHilferink, this seems a useful addition to me. Tarjan's algorithm in particular, as (if I understand this correctly) it requires that every edge is visited only once. According to the Wikipedia page, Kosaraju's algorithm is not as efficient in practice as Tarjan's.

**Comment by jipclaassens** [comment]
@cjacobscrisioni what is in your opionion the priority of this issue?

**Comment by cjacobscrisioni** [comment]
I'm afraid we are too late to fix this for the upcoming Cohesion Report (deadline 20/11) while we need the global networks for the upcoming 2UP update. So global networks (and Functional Areas in cascade) come first. I hope to dedicate some time to the global networks git this afternoon.

**Comment by MaartenHilferink** [comment]
Testing with
/Invoer/RuimtelijkeData/OSM/NetworkPreparation/Network_with_extraverbindingen/strongly_connected_networks

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/075c9ad7-deb6-45e9-8dd2-963c3fd2341d)

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/88156147-3030-4a2b-9fec-c5c9b2470bdc)

**Comment by MaartenHilferink** [comment]
Voorbeeld: Batterijlaan abuisievelijk oostwaards waardoor Meulenwieklaan in Bussum niet meer te verlaten is:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/c2c3d865-3ef8-47d1-8da7-c597e02c3efd)

wel oke in google maps:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d802a683-e716-436b-a9e4-b6c1a43f2692)
