### ISSUE TITLE
Processing of WGS84 bilinear file doesnt work in 14.2.1. compared to default WGS84 default nearest file

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#575]
GeoDMS 14.2.1
PD  10319 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_cal21_IMAGE
SD 10299 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/2UP

open stam.dms
item
/Preprocessing/Urban2023/Urban2023/BuiltUpPresence_R2023_Create/Y1975/big_raster/GridDatatot
regel 60 in TowardsAnUrbanPreview_cal21_IMAGE\cfg\stam\Preprocessing\Preprocessing_urban2023\GHS_BUILT_S_WGS84.dms
Na 8 uur gebeurd er nog steeds niets

bilinear_LZW_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif is aangemaakt dmv (Mollweide naar WGS84):

gdalwarp -r bilinear -t_srs EPSG:4326 K:\MW_WGS84\MW\GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif K:\MW_WGS84\WGS84\bilinear_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif
gdal_translate K:\MW_WGS84\WGS84\bilinear_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif K:\MW_WGS84\WGS84\bilinear_LZW_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif -co compress=lzw
del K:\MW_WGS84\WGS84\bilinear_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif

De wel werkende (eerder gebruikte file):
WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif
ia aangemaakt in ArcMAp 10.8.1 met toolbox Project Raster (MollWeide naar WGS84 met NEAREAST als resampling techniek).

Specificaties van beide bestanden staan in de screendumps (in QGIS)

Om de wel werkende file te gebruiken activeer regel 61 in TowardsAnUrbanPreview_cal21_IMAGE\cfg\stam\Preprocessing\Preprocessing_urban2023\GHS_BUILT_S_WGS84.dms
en deactiveer regel 60

![default_nearest_1975](https://github.com/ObjectVision/GeoDMS/assets/24241780/ebb14e1d-d40d-42d0-8c1c-8bcaeb6e9fc5)
![bilinear_1975](https://github.com/ObjectVision/GeoDMS/assets/24241780/60480e6f-1196-459a-9660-757f0cda7af7)
![hang](https://github.com/ObjectVision/GeoDMS/assets/24241780/5fa53b45-4c3e-4e99-8d52-3752d58c1079)

**Comment by eoudejans** [comment]
@basvanbemmel in light of reproducing, the tif files you mention are not part of the SD?
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/13282188-0592-438d-a63b-9bf71fc2fbed)

**Comment by basvanbemmel** [comment]
Inmiddels gecommit

**Comment by basvanbemmel** [comment]
Zou het kunnen dat het te maken heeft met dat er geen tfw voor het bilinaire-bestand aanwezig is itt het default nearest bestand ? Maar ik zie wel projectie zit in de tif gebakken. Maar wordt beide wel ondersteund? Wellicht niet het geval met de native storage manager?

**Comment by basvanbemmel** [comment]
Met native driver dus
//,	StorageType     = "gdal.grid"
weggesterd krijg je de melding:

Error reading geographic reference info from K:/SD/2UP/Preprocessing/urban/JRC/BuiltUpPresence/2023/WGS84_bilinear/bilinear_LZW_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tfw
/Preprocessing/Urban2023/Urban2023/BuiltUpPresence_R2023_Create/Y1975/big_raster 

Maar is er is dus helemaal geen tfw aanwezig

**Comment by basvanbemmel** [comment]
Hierbij nog een update van het issue:
Ook met tfw file aangemaakt door QGIS:
gdalwarp -r bilinear -t_srs EPSG:4326 K:\MW_WGS84\MW\GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif K:\MW_WGS84\WGS84\bilinear_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif
gdal_translate K:\MW_WGS84\WGS84\bilinear_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif K:\MW_WGS84\WGS84\bilinear_LZW_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif  -co compress=lzw  -co TFW=YES
del K:\MW_WGS84\WGS84\bilinear_WGS84_GHS_BUILT_S_E1975_GLOBE_R2023A_54009_100_V1_0.tif

bleek dat de file niet door de geodms processed kon worden (blijft hangen op item /Preprocessing/Urban2023/Urban2023/BuiltUpPresence_R2023_Create/Y1975/big_raster/GridDatatot). 

Ik heb de bilineare bestanden geprocessed in ArcMap. Dit kon wel worden verwerkt door de geodms. Ik vermoed dat QGIS toch iets vreemds in het formaat doet.

de te verwerken bestanden (dus die aangemaakt zijn in ArcMap) staan nu in: de SD onder
..\Preprocessing\urban\JRC\BuiltUpPresence\2023\WGS84_bilinear

**Comment by basvanbemmel** [comment]
Erik: ik heb net het bestand niet te processen bestand gestuurd per filesender met als onderwerp WGS84 bilinear 1975 QGIS
Ik wil de SD namelijk niet vervuilen.

**Comment by eoudejans** [comment]
Super, ik begrijp dat je de SD niet wil vervuilen.

Hoe hoog is de prioriteit van issue #575? Je komt volgende week langs, we zouden er dan naar kunnen kijken, maar alternatief kan ik het issue nu nader bekijken.

Groet,

Erik Oudejans

Object Vision BV
p/a Vrije Universiteit
De Boelelaan 1085
1081 HV  AMSTERDAM - the Netherlands
tel +31-20-598.9083
***@***.***

www.objectvision.nl<http://www.objectvision.nl/>

________________________________

**Comment by eoudejans** [comment]
It turned out that both tif files were written with different tiling. Tif 1) (the file that could be properly read) had a tiling of two tiles: the whole world plus a small stripe and the other tif 2) with a striped tiling of ~360000x1. Tif 2) was being processed by GeoDMS, however the striped tiling was so far off of the default GeoDMS tiling of 256x256 that each stripe had to be read 256 times including decompressing.

In order to make sure that a tif file is optimally tiled to be used with GeoDMS the following gdalwarp command can be used. Note that the reprojection is optional, and in this case goes from ESRI:54009 (World Mollweide) to EPSG:4326:

**gdalwarp input.tif output.tif -co TILED=YES -co BLOCKXSIZE=256 -co BLOCKYSIZE=256 -s_srs ESRI:54009 -t_srs EPSG:4326 -co COMPRESS=LZW**

**Comment by eoudejans** [comment]
Updated our wiki, which now briefly goes into the GeoDMS default tiling:
[GeoDMS Default Tiling](https://github.com/ObjectVision/GeoDMS/wiki/GeoDMS-Default-Tiling)
