### ISSUE TITLE
Read fss-attribute with wrong value type, error "Illegal Abstract Error: MakeUndefined called." 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#577]
Changing the value type to the correct value type (int32), fixes it. But it should give a more informative error?
Like:

`The configured value type of this attribute does not match the stored value type`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/0d8ee68d-c113-429d-9715-b340e936890f)

**Comment by eoudejans** [comment]
@jipclaassens creates reproducible scenario.

**Comment by jipclaassens** [comment]
implemented
