### ISSUE TITLE
Writing to file, creating .tmp, then alt+r (or close app) doesn't always result a rename of .tmp file

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#582]

**Comment by eoudejans** [comment]
Suggested change: remove .tmp mechanism completely and make filesystem of os responsible for correct file closure.

**Comment by jipclaassens** [comment]
Many duplicates in changed files found, now two, sometimes six.
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/6c244102-4b15-4abb-b856-38c00bbd8652)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/4c16f5c7-3c4e-4849-8d9f-973d3901bd25)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/404785cf-1609-45ee-9f82-8b6e59a56d40)

**Comment by MaartenHilferink** [comment]
Since v16 the SafeFileWriterArrays are no longer used.  Files are directly (over)written, which may cause some adjustments, such as possibly demonstrated with #838
