### ISSUE TITLE
One cannot input an uint64 value in a select_with_attr expression

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#583]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/48cceb96-bf87-48d1-ad83-3dad73b61c9a)

```
unit<uint32> Test_subset := select_with_attr_by_cond(VBOs_Panden_set, VBOs_Panden_set/pand_bag_nr == 3100000117486u64)
```

Not allowed:
`uint64(3100000118116)`
`3100000118116[uint64]`
`3100000118116u64`

Dirty trick:
`uint64('3100000118116'))`

**Comment by MaartenHilferink** [comment]
Reproduced in MicroTst.dms:

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ea23a6cf-a15f-4b64-b79b-86596718069f)

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e88c8cb7-6c3d-4257-bf9f-15d9ff85af31)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/3c02a7e8-7db0-4cc9-92a4-1581bb9a73c7)
