### ISSUE TITLE
show line number in sorted table in status bar

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#585]
In a sorted table, it is not what the line number is of the focus cell. The id column can not be used in the case of sorted columns.

In a map view the coordinate is presented in the status bar, can we use this control to show the line number of the focus cell in the table?

**Comment by eoudejans** [comment]
Implemented in latest commit(s). Implementation is similar to Mapview behavior and works on hoovering over a tableview's column. The coordinate label is hidden for tableview. See:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/64c79ce6-aea2-4a05-a71d-ea3aec27480b)

Closing as implemented.
