### ISSUE TITLE
Request: includes should not necesarily need to be a container/template 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#586]

**Comment by eoudejans** [comment]
Additional remarks:
- Items should be fully defined in a single file

**Comment by MaartenHilferink** [comment]
Now #include <files> may contain one or several units, attributes without container, which are directly added as sub items at the container that contains the #include:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e98f5d67-a89e-46d2-ae19-8154ff5616d1)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/18510bc8-0851-43ff-bae5-d5949e92514b)
