### ISSUE TITLE
ClassifyNonzeroEqualInterval function results in error: Check Failed Error: minValueN < 0.0

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#589]
Steps to reproduce:

Repository: https://github.com/ObjectVision/GeoDMS-Test
file: ../tst/operator/cfg/operator.dms
Item: request item: classify/UnTiled2UnTiled/ClassifyNonzeroEqualInterval/att  in table

error occurs

**Comment by MaartenHilferink** [comment]
Reproduced: 


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/b0679b02-359d-45fa-b5ac-a0e94ded7e10)

**Comment by MaartenHilferink** [comment]
Fixed:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7892b118-fbe1-4042-9466-ccc65c66275c)
