### ISSUE TITLE
Storing results of for_each_nedvat in one storage only writes the last column

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#590]
The following code results in only writing the last column
```cpp
	container test_for_each_write :=
		for_each_nedvat(
		for_each_info/names
		,'reference/' + for_each_info/names
		,reference
		,int32
		,'%LocalDataProjDir%/WLO/Y1980.csv'
		, "gdalwrite.vect"
		);
```
results:

IntegerAttNull,
,
"1"
"256"
"-100"
"9999"

**Comment by eoudejans** [comment]
In reality both columns are written, but one after another, the latter column overwriting the former column.

**Comment by eoudejans** [comment]
What does work, is defining StorageName and StorageType at container level of the for_each statement, like so:
	container test_for_each_write_sm_container :=
		for_each_nedv(
		for_each_info/names
		,'reference/' + for_each_info/names
		,reference
		,int32
	),  StorageName     = '%LocalDataProjDir%/WLO/Y1980.csv'
	 , StorageType      = "gdalwrite.vect";
	 
This results in the correct two-column dataset:

IntegerAtt,IntegerAttNull
"0",
"1","1"
"256","256"
"-100","-100"
"9999","9999"

**Comment by eoudejans** [comment]
In case each for_each generated attribute is to be written to their own storage, this can of course be done like so:
	container test_for_each_write :=
		for_each_nedvat(
		for_each_info/names
		,'reference/' + for_each_info/names
		,reference
		,int32
		,'%LocalDataProjDir%/WLO/' + for_each_info/names + 'Y1980.csv'
		, "gdalwrite.vect"
		);

**Comment by basvanbemmel** [comment]
ok dank top ik ga het proberen.

Ik heb het nu zo opgelost:

		container COROP_WLO := 
			for_each_nedv(//at(
				WLO/name
				,'(sum(' + HGNYears_Name + '_5m_WLO == ' + string(id(WLO)) + '[uint8] ? 1f : 0f, COROP2023/per_5m) * geography/perGridsize/size_5m/Domain/NrHaPerCell)[Ha]'
				,COROP2023
				,ha
				//,'%LocalDataProjDir%/WLO/'+HGNYears_Name+'.csv'
				//, "gdalwrite.vect"
			);
			
		container COROP_WLO_export: StorageType="gdalwrite.vect", StorageType = "gdalwrite.vect", StorageName = "= '%LocalDataProjDir%/WLO/'+HGNYears_Name+'_tot.csv'"
		{
			attribute<uint8>  id          (COROP2023) := COROP2023/id;
			attribute<string> naam        (COROP2023) := COROP2023/statnaam;
			attribute<string> statcode    (COROP2023) := COROP2023/statcode;
			
			attribute<ha>     oppervlakha (COROP2023) := COROP2023/oppervlakha;
			attribute<ha>     bebouwd     (COROP2023) := = HGNYears_Name + '/COROP_WLO/bebouwd';
			attribute<ha>     landbouw    (COROP2023) := = HGNYears_Name + '/COROP_WLO/landbouw';
			attribute<ha>     natuur      (COROP2023) := = HGNYears_Name + '/COROP_WLO/natuur';
			attribute<ha>     water       (COROP2023) := = HGNYears_Name + '/COROP_WLO/water';
			attribute<ha>     overig      (COROP2023) := = HGNYears_Name + '/COROP_WLO/niets';
}

Maar is er een intentie om het op te lossen in het at-construct of wordt dit de workaround die gewoon leidend gaat worden?

**Comment by eoudejans** [comment]
Added example 7 to our documentation: https://github.com/ObjectVision/GeoDMS/wiki/For_each

**Comment by basvanbemmel** [comment]
ok dank dat je dit zo snel opgepakt hebt, top

**Comment by eoudejans** [comment]
> Maar is er een intentie om het op te lossen in het at-construct of wordt dit de workaround die gewoon leidend gaat worden?
Ik zou het geen work-around noemen maar een hoger niveau waarop je de StorageName en StorageType definieert. for_each constructen werken op de argumenten, namen van provincies bijvoorbeeld, daarmee zou het haaks staan om in de for_each iets over alle argumenten te laten werken.

**Comment by eoudejans** [comment]
> ok dank dat je dit zo snel opgepakt hebt, top

Super, geen probleem, schroom niet om direct een issue te maken, is ook handig voor toekomstige referenties. We kunnen issues altijd meteen sluiten mocht het toch geen probleem zijn.
