### ISSUE TITLE
ascii grids still used in LUS demo

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#592]
Since GeoDMS 15.0.0 reading ascii grids is no longer supported.

The LUS demo from the full test, still reads Ascii grids.

Scenario 1:
machine: ovsrv05
configuration: C:\SourceData\RegressionTests\prj_snapshots\lus_demo\cfg\regression_test.dms
e.g.: active item: Current_Situation/Current_landuse/LU_2010 

Scenario 2:
machine: ovsrv05
configuration: C:\SourceData\RegressionTests\prj_snapshots\lus_demo_2022\cfg\demo.dms
e.g.: active item: Current_Situation/Policy_maps/Spatial_plans/impl/recreation

**Comment by jipclaassens** [comment]
asc files are now replaced in the head of https://github.com/ObjectVision/LandUseModelling

Do you still want to use the old lus_demo version?
I could replace the files on Monday on OVSRV5.
