### ISSUE TITLE
Read file properties of grid like QGIS does

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#594]
iets als 'File properties'
info a la griddata (domein values type, relatie met projectie, tile informatie)

evt in detailpages > source description

**Comment by jipclaassens** [comment]
zie #121

**Comment by eoudejans** [comment]
Added radio button for dataset information (WIP), see:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6c5c7b40-4d61-4786-810b-01e9c9447e90)

**Comment by eoudejans** [comment]
Preliminary implementation completed, see:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6717d7a2-23d4-4268-8923-d58fedcfcf95)

To do: 
- formatting
- expand information

**Comment by eoudejans** [comment]
It should be a request to the storage manager.

raster:
- compression
- srs
- x, y size
- extend

**Comment by eoudejans** [comment]
Some geodata formats support nesting, see for instance:
- Geopackage (GPKG) with multiple layers with each layer a set of fields
- netcdf formats, with several timeseries of rasters.

**Comment by eoudejans** [comment]
Preliminary implementation completed, initial implementation only done for gdal.grid, see:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/181b153d-b95a-4533-97f6-dcc8866a9e83)

Both information and formatting can be improved upon.

**Comment by eoudejans** [comment]
Also implemented for gdal.vect:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/70a0be79-f5d5-4093-a381-db62f0aeea8a)

**Comment by eoudejans** [comment]
PropWriter.h provides an abstract mechanism to write xml type structures to files. This can also be adapted for visualization purposes.

**Comment by eoudejans** [comment]
Check and add example multi polygon.

For rasters: add pixel size, compression and file size.

**Comment by eoudejans** [comment]
Compression is now reported for gdal.grid storage manager, see:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/e4f9ca5d-7b6f-451a-9ee9-55dafaad88ce)

**Comment by eoudejans** [comment]
Number of bits per pixel is also shown if information is available in image structure metainfo. Closing as implemented. Opening individual issues for added information is the way to go.
