### ISSUE TITLE
Text in scale bar is not to correct size

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#595]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/c931a99d-4daa-4559-ad71-c42ce5655d63)

**Comment by MaartenHilferink** [comment]
Now font remains small and sort of fitting:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/8544a35a-b635-45dd-bf0e-85c874b20064)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9398f949-a7ed-462f-9ec1-baed920f6ce1)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/bc8c3a59-42f8-45b3-9885-6715b691535b)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/14ac6f61-5a2d-4be0-9d9f-ce7d59f611a5)

**Comment by MaartenHilferink** [comment]
Maximum size of a PDF, version 7. 381km x 381km
![Uploading image.png…]()
