### ISSUE TITLE
buffer functie op linestring geeft soms resultaat alsof de linestring een ring is.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#601]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/fbc6fe2b-4737-4c00-b4d7-92b915951af8)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/19d33fdc-e0c7-4d73-8a20-b00c3d86e4e5)

**Comment by basvanbemmel** [comment]
Wellicht kan ik dit lijnelement isoleren en naar je opsturen tbv reproductie (ipv een enorme dataset)

**Comment by MaartenHilferink** [comment]
> Wellicht kan ik dit lijnelement isoleren en naar je opsturen tbv reproductie (ipv een enorme dataset)

Of een verwijzing naar svn / github waarin dit is opgenomen; dan kunnen we zelf wel die geometries vinden

**Comment by MaartenHilferink** [comment]
n.b. i.p.v. 
`attribute<bool> xxx := IsDefined(invert(convert(Dyna, /geography/perGridsize/size_5m/domain))`

kun je ook toepassen:

`attribute<bool> xxx := has_any(convert(Dyna, /geography/perGridsize/size_5m/domain))`

of eventueel

`attribute<WegType> yyy := first(Dyna->Segment_rel->WegType, convert(Dyna, /geography/perGridsize/size_5m/domain))`

**Comment by basvanbemmel** [comment]
IK ga het vanmiddag committen, je hoort nog van me

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/264518cf-a50d-49e7-b584-294117ed11b1)

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/1e7407d0-db84-4d35-a300-3abe971b5320)

**Comment by basvanbemmel** [comment]
Ik heb de geometrie geisolseerd en in arcmap Features Vertices to Point gedaan dan zie ik wel een vreemde interne nummering. 5 tm 48 en 1 tm 4.  5 tm 48 wordt gek gebufferd

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/ace72150-cf30-4810-a2aa-faa467f16f3d)

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/50d72855-5f07-4995-b224-022fc5b601a9)

**Comment by basvanbemmel** [comment]
1 en 49 hebben dezelfde coordinaat overigens

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/9ecda45f-5c20-4b86-88b4-42cecb276420)

**Comment by basvanbemmel** [comment]
1 en 49 hebben dezelfde  coordinaat

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/1d7a720b-16b2-4287-8630-14fd210477cc)

**Comment by MaartenHilferink** [comment]
is this a duplicate of #701 ?

**Comment by MaartenHilferink** [comment]
> Ik heb de geometrie geisolseerd en in arcmap Features Vertices to Point gedaan dan zie ik wel een vreemde interne nummering. 5 tm 49 en 1 tm 4. 5 tm 49 wordt gek gebufferd
> 
> ![image](https://private-user-images.githubusercontent.com/24241780/288447983-ace72150-cf30-4810-a2aa-faa467f16f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDU5MzEsIm5iZiI6MTcxMjI0NTYzMSwicGF0aCI6Ii8yNDI0MTc4MC8yODg0NDc5ODMtYWNlNzIxNTAtY2YzMC00ODEwLWEyYWEtZmFhNDY3ZjE2ZjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE1NDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MmFiODEyZWY3ZjczMDY4ZGQ5YmQ1MzY3ZmU1OWE2YzUwMzJlNTQyMTNjOTcwMGNmMTU2NzU2NmM2Mzg0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wFs02vp3q-H-UC3f02XoIquEierkauuy9pWsgh_OgWE)

Dit doet me toch wel denken aan een multi-linestring, die, zie #701, als skinny polygon was geimplementeerd met verbindings-corridor naar de 2e linestring (dus van punt 4 naar 5). De skinny polygon representatie zou zijn geweest: 1, 2, 3, 4, 3, 2, 1, 5, 6, ..., 48, 49, 48, ..., 6, 5, 1. 
Nieuwe (v14.17.0) representatie wordt 1, 2, 3, 4, null, 5, 6, ..., 48, 49.

**Comment by MaartenHilferink** [comment]
Om dit nu goed af te handelen moet de bg_buffer_linestring misschien nog wel even aangepast worden om de null netjes over te slaan.

**Comment by MaartenHilferink** [comment]
Fixed in 14.17.2 ?

**Comment by basvanbemmel** [comment]
ik heb gecheckt fixed

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/4bbb3a57-7d58-4207-92cb-42064ee24eeb)
