### ISSUE TITLE
Value Info for values in grouped by column results in explaining incorrect values

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#602]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/4f82c30a-2520-435b-87e3-bb59f5c073cf)

In this example the value info is requested for the cell: WK_1.

The dialog indicates it explains the value: WK_0.

scenario:
project: MicroTst
request item: value_info/relational/src/buurt/WK_code  in table

Activate the Group By tool and double click on row 2 and col 1.

**Comment by MaartenHilferink** [comment]
Nu:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4e6ea4bb-8151-499d-8a9f-c040a99d3d85)
