### ISSUE TITLE
Request: add 'clip' operator

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#604]
The current sub-operator can only cut out a polygon that has a matching domain or a void domain. What if I want to cut a different polygon set? 

For example, I want to cut out all main roads (polygons) from a parcel polygon set. To my knowledge this is now not possible.

In ArcGiS, this operator is called 'clip':

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/fa954f0e-35a5-486d-808f-2145902dedb2)

**Comment by jipclaassens** [comment]
Met Boost geometry zou dit sneller kunnen

Nu kan het met overlay_polygon, enkel in integers

**Comment by MaartenHilferink** [comment]
hoe presteert:

`fpolygon(mul(ipolygon(INPUT), ipolygon(CLIP_FEATURE)))`

of, korter:
`fpolygon( ipolygon(INPUT) * ipolygon(CLIP_FEATURE))`
?

**Comment by jipclaassens** [comment]
@MaartenHilferink, this works indeed. However, even for a relatively small dataset, it is very slow. 

With a simplified (at 10 meters) BBG of Amsterdam and with a smaller rectangular clip feature, it still takes quite a while. It calculates for the last 25 minutes and still needs to finish.

**Comment by jipclaassens** [comment]
Project:
`https://github.com/ObjectVision/BegrenzingBebouwdGebied.git`

Make studyarea .fss
`/SourceData/BBG/MakeStudyArea`

Mul test case:
`/SourceData/BBG/StudyArea/test`

**Comment by MaartenHilferink** [comment]
Rekentijd test (m.b.v. boost::polygon) 4 sec, test2 (m.b.v. boost::geometry's bg_intersect): direct, < 1 sec.
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/3b47031b-88c0-4427-900d-c1e43c5771ff)

**Comment by MaartenHilferink** [comment]
overlay_polygon is now also applicable on fpoint and dpoint arguments, by using boost::geometry
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/12cf6f58-3dda-452e-a2ca-d28a1294aefc)

**Comment by MaartenHilferink** [comment]
Remaining todo's 
- [ ] allow cog_mul, cog_and for bg_intersect on floating point point sequences
- [ ] cog_sub, bg_difference
- [ ] cog_or, cog_add, bg_union
- [ ] bg_overlay_polygon as alternative for overlay_polygon on integer coordinates

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/c6e49a8e-7e2d-4be5-802e-c3f7ad1a7389)

**Comment by jipclaassens** [comment]
@MaartenHilferink does this mean there new operators: 
- bg_intersect
- bg_union
- bg_xor
- bg_difference
- bg_overlay_polygon
- bp_overlay_polygon

In that case, we need to update the documentation.
