### ISSUE TITLE
Export data > gpkg > cancel, results in Fatal OS error

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#605]
1. right-mouse click on /Brondata/BRK/Perceel/geometry
2. export data
3. change type to gpkg
4. type something after geometry in de name box
5. click cancel
6. seconds later, fatal error.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b9d57dda-2851-46e9-9bad-ea8c5b205c3a)

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\Redevelopment_issueGH605\analysis\verdichting.dms`

`/Brondata/BRK/Perceel/geometry`

**Comment by jipclaassens** [comment]
Ook bij export shp, en als ie klaar is en je drukt op close.

**Comment by eoudejans** [comment]
Observation: cannot be reproduced in a simple configuration with a point, arc or polygon attribute.

**Comment by eoudejans** [comment]
During reading of tif files, similar error messages occurred. Solved in latest commit. May be related, to be tested..

**Comment by jipclaassens** [comment]
Seems to be fixed in 14.7.1
