### ISSUE TITLE
how to nest add_or_null and sub_or_null in one statement

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#608]
This works

		attribute<Person_km2> North      (gtopo) := TotalPopulationDensity1990[(gtopo/id) - point(1w, 0w, wpoint)];
-->
		attribute<Person_km2> North      (gtopo) := TotalPopulationDensity1990[sub_or_null((gtopo/id),point(1w, 0w, wpoint))];

but how to do:

		attribute<Person_km2> SouthWest  (gtopo) := TotalPopulationDensity1990[(gtopo/id) + point(1w, 0w, wpoint) - point(0w, 1w, wpoint)];

I have to nest add_or_null and sub_or_null. But how? I've tried already many things. Any advice?

**Comment by MaartenHilferink** [comment]
How about: 

	attribute<Person_km2> SouthWest  (gtopo) := TotalPopulationDensity1990[sub_or_null(add_or_null(gtopo/id, point(1w, 0w, wpoint)), point(0w, 1w, wpoint))];

?

**Comment by basvanbemmel** [comment]
ok dank! Het lijkt te werken. Waarom staat er onder:
https://github.com/ObjectVision/GeoDMS/wiki/Arithmetic-functions
eigenlijk geen divide_or_null?
bij het delen door een klein getal kun je toch hele grote waarden krijgen?

**Comment by basvanbemmel** [comment]
Wellicht is het nesten wel iets om op te nemen in de doc, hoewel het wellicht te specifiek is.

**Comment by MaartenHilferink** [comment]
> ok dank! Het lijkt te werken. Waarom staat er onder: https://github.com/ObjectVision/GeoDMS/wiki/Arithmetic-functions eigenlijk geen divide_or_null? bij het delen door een klein getal kun je toch hele grote waarden krijgen?

Bij delen door 0 (of null) resulteert al null, bij te groot resultaat ook; er is geen doorteloptie zoals wel bij addition en subtraction. Multiplication (van signed en unsigned intergers) werkt wel modulo, dus een mul_or_null zou nog wel nodig kunnen zijn.

**Comment by mtbeek32** [comment]
voor mul_or_null, zie: https://github.com/ObjectVision/GeoDMS/wiki/mul_or_null
