### ISSUE TITLE
soms comment in statement niet mogelijk

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#610]
Soms is het niet mogelijk om in een statement te commenten, hieronder een voorbeeld. Wat is daar de reden voor eigenlijk. Het is niet altijd namelijk. Ik vermoed dat iets te maken heeft met volgorde van string concatenatie waarbij het comment teken verstoring geeft?

		container SectorAllocRegios := 
			for_each_ne(
				SectorAllocRegio/name
				,'SectorAllocRegioT(
					SectorAllocRegio
					,'+string(id(SectorAllocRegio))+'[SectorAllocRegio]
					//,'+MakeDefined((SectorAllocRegio/name+'/StateNaAllocatie')[ID(SectorAllocRegio)-1b], 'StateVoorAllocatie')+'
					,'+MakeDefined((SectorAllocRegio/name+'/StateNaAllocatie')[ID(SectorAllocRegio) - min_elem( id(SectorAllocRegio),1b)], 'StateVoorAllocatie')+'
					, Context
					, '+string(SectorAllocRegio/AantalIters)+'[uint8]
				)'
			);

**Comment by eoudejans** [comment]
The behavior in this scenario is working as intended. The attempted comment within the expression is here also interpreted as part of the expression. Below is a similar simpler scenario where the comment will also not work:

`parameter<string> test :== 'string(1) + string(2)  // comment here + string(3)'; `

**Comment by jipclaassens** [comment]
The common solution is to add quotes to each line. Then you can comment lines. See here:

```
container SectorAllocRegios := 
	for_each_ne(
		SectorAllocRegio/name
		,'SectorAllocRegioT('
			'SectorAllocRegio'
			','+string(id(SectorAllocRegio))+'[SectorAllocRegio]'
			// ','+MakeDefined((SectorAllocRegio/name+'/StateNaAllocatie')[ID(SectorAllocRegio)-1b], 'StateVoorAllocatie')+
			','+MakeDefined((SectorAllocRegio/name+'/StateNaAllocatie')[ID(SectorAllocRegio) - min_elem( id(SectorAllocRegio),1b)], 'StateVoorAllocatie')+
			', Context'
			', '+string(SectorAllocRegio/AantalIters)+'[uint8]'
		')'
	);
``
