### ISSUE TITLE
reading attributes from GeoPackage fails with GDAL 3.8.1

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#614]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/876e0175-1c59-4bed-b2e7-3005d3ba4068)

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/bf1f75b3-eaea-4692-bf9a-f76ea2ebae5a)

**Comment by eoudejans** [comment]
Issue reproducible at @jipclaassens ' side.

**Comment by eoudejans** [comment]
Reproducibility confirmed.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0a61eda6-1cfc-4ca1-8a6f-4a03b858f880)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/7b7bac43-bd2d-4064-acb0-37930292cabd)
		DataArray<SharedStr>::reference dataElemRef = data[i];
		gdalVectImpl::FeaturePtr feat = hDS->TestCapability(ODsCRandomLayerRead) ? GetNextFeatureInterleaved(layer, hDS) : layer->GetNextFeature();
		if (feat) // && !feat->IsFieldNull(currFieldIndex) && feat->IsFieldSet(currFieldIndex))
		{
			auto field = (*feat)[currFieldIndex];
			bool isNull = field.IsNull();
			if (!isNull)
			{
				CharPtr fieldAsString = field.GetString();
				dataElemRef.assign(fieldAsString, fieldAsString + StrLen(fieldAsString));
				continue;
			}
		}
		Assign( dataElemRef, Undefined() );
