### ISSUE TITLE
get features from grid patterns

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#616]
Results of grid analyses (interpolation etc.) are useful as polygon features in e.g, web mapping, for visualization purposes and to relate attributes to.

Current implementation:
- union grid cells as small polygon to one polygon for adjacent cells with the same value
- simplify polygon (outside GeoDMS) 

Disadvantages:
- union polygon is not efficient, especially for large areas
- resulting patterns show cartel edges
- simplify the resulting polygon in the GeoDMS does not respect the topology.

A solution with GeoDMS scripting of new GeoDMS functions is  welcome.

**Comment by jipclaassens** [comment]
@mtbeek32 maakt een voorbeeld datasetje met 'gekke' gevallen (e.g. slivers)

**Comment by MaartenHilferink** [comment]
Opzet algoritme:

1. Segments := horizontale raster-randjes met ongelijke boven en onder zones + verticale raster-randjes met ongelijke linker en rechter zones
2. JFN := raster-hoekpunten waarop 2 segments uit komen
3. JFL := Segments die 2 JFN verbinden
4. JFS := serie verbonden JFL
5. JFS/Linestring := d.m.v. impedance_single van alle begin JFS naar eind JFS routes, traceback, flow voor ordinal t.b.v. points2sequence
6. Junction := raster-hoekpunt waarop meer dan 2 segmenten uit komen (1 komt niet voor)
7. Connector := Segment tussen een Junction en een JFN
9. JFS/Linestring := begin connector + result(5) + end connector; eventueel deze simplifyen
10. ZoneJunction := kruistabel met junctions en zones; 
11. ZoneBorder := link tussen 2 junctions bij een zone die door een segment of JFS/Linestring verbonden zijn
12. bepaal per zone de 1e junction en 1 via een zoneborder verbonden 1e junction
13. routeer de andere junctions min of meer conform stap 5.
14. gebruik 13 om resultaten van 9 achter elkaar te plakken per zone.

**Comment by mtbeek32** [comment]
Martin voegt een script toe met vergridde gemeentekaart

**Comment by MaartenHilferink** [comment]
n.b.: bovenstaand stappenplan is tbv vectorisering van rasters met topologie t.b.v. simplify van linestrings tussen junctions. Voor opbouwen van topologie van polygoondata, zoals de CBS buurtkaart, zijn stappen vanaf 5 deels ook te gebruiken, wanneer de resultaten van segement2points eerst ontdubbeld worden. Behoud hergebruik van uit segement2points resulterende ordinals kan de (her)nummering van punten in linestrings wellicht vereenvoudigen.

**Comment by mtbeek32** [comment]
Test project toegevoegd:

Repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration: ../Poly_2_grid_2_poly/cfg/stam.dms

Items: /GridData/m100, /GridData/m25 en /GridData/m10: vergridde gemeentekaarten op 100, 25 en 10 meter gridniveau.

**Comment by MaartenHilferink** [comment]
implemented (Boundary)Segments:
https://github.com/ObjectVision/GeoDMS/issues/616

**Comment by MaartenHilferink** [comment]
ZoneRings now look Oke:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/48e88022-8ca0-40e3-9f1c-5211e4b7f4ec)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/60ed4683-1a9a-4e72-b34b-c6c3b4cd5119)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/1182cd45-c17f-4888-9194-50bf6a05505b)

**Comment by MaartenHilferink** [comment]
After code clean-up: 16 secs.
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/20b0c961-02e8-410f-b540-d118970c0993)

**Comment by MaartenHilferink** [comment]
See [Grid2Polygon](https://github.com/ObjectVision/GeoDMS/wiki/Grid-2-polygon-example) example script, that vectorizes and simplifies rasterized zone data while maintaining topological relations; see also https://geodms.nl/docs/grid-2-polygon-example.html
