### ISSUE TITLE
Qt6GUI.dll error bij opstarten 14.7.1 op Azure

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#617]
Na installatie van 14.7.1 krijg ik bij opstarten op Azure:
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/a2829f5f-dc35-4602-b81f-39674483735d)

**Comment by eoudejans** [comment]
@basvanbemmel zou je kunnen bekijken of Qt6Gui.dll in de installatiefolder staat?

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/91adee78-1999-4b0a-ab85-194db0330db5)

**Comment by MaartenHilferink** [comment]
ter info: in mijn installatiefolder staat ie ook, van dezelfde datum en size:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/699c786e-f463-45ee-80a1-5d0a6a91bd40)

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/15aa5955-d511-4b08-9e81-297f50610885)

**Comment by jipclaassens** [comment]
welke qt library zit in 14.7.0 ? Welke laatste versie deed het wel bij Bas?

**Comment by basvanbemmel** [comment]
14.6.0 werkte nog wel

**Comment by eoudejans** [comment]
Dank @basvanbemmel we gaan het verder onderzoeken.

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/8e2923d2-a316-4682-a876-6aa5bb92c80b)
Wat betreft verschillen tussen versies hierboven: links 14.6.0 en rechts 14.7.0:
- Qt dlls zijn identiek
-  msvcp140**.dlls zijn geupdate
- vc**140**.dlls zijn geupdate
- vcruntime140_threads.dll is erbij gekomen

**Comment by eoudejans** [comment]
Het hoeft hier overigens niet te gaan om de Qt dlls zelf maar om een dll waar Qt van afhankelijk is, output van dependency walker van QtGui tijdens openen GeoDmsGui:
**14.7.0**
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/18e78715-a5d3-4c5e-ab32-fb9869f5070b)

Further error message:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/02227893-6faa-4b1b-8753-d6688ea79f5d)


**14.6.0**
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/67ffe869-ae71-4fb3-9de5-cae7a85b09b0)

**Comment by MaartenHilferink** [comment]
Er is nu 14.8.0: https://github.com/ObjectVision/GeoDMS/releases/tag/v14.8.0 
Doet het probleem zich met deze setup ook nog voor ?

**Comment by MaartenHilferink** [comment]
@Erik: Je vergelijkt 14.6.0 en 14.7.0, dd 4-dec. Had je van Bas gehoord dat deze ook dit issue had ?

**Comment by basvanbemmel** [comment]
Ik zie geen setup.exe bij 14.8.0 staan
en antwoord op je andere vraag, ja was ook een issue in 14.7.0

**Comment by jipclaassens** [comment]
> Ik zie geen setup.exe bij 14.8.0 staan en antwoord op je andere vraag, ja was ook een issue in 14.7.0

De source code staat er wel, dus die kun je wel even compileren ;)

Maarten heeft m er nu bij gezet.

**Comment by basvanbemmel** [comment]
14.8.0 start nu wel goed op, dank
