### ISSUE TITLE
Unreadable multilines in eventlog

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#618]
Cannot open what? There are multilines in the eventlog. 

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8ea589d6-fa1b-41c6-8d89-9506bc60885c)

**Comment by jipclaassens** [comment]
Source of the error: if I uncheck 'use native drive' it does work...

**Comment by eoudejans** [comment]
Noted, likely related with the change made to the native tif driver and stricter checks before reading. However here the scenario is writing, hence it should never have tried to open the to be written file during update metainfo.

**Comment by eoudejans** [comment]
Scenario not reproducible yet, seems to work fine for both native tif- and gdalwrite.grid storage managers.

**Comment by jipclaassens** [comment]
LUS_demo:

`https://github.com/ObjectVision/LandUseModelling.git`
`C:\GeoDMS\ProjDir\LandUseModelling\lus_demo\cfg\demo.dms`

Right-mouse click on  `/Current_Situation/Thematic_maps/NatureLandscape/peat` > Export Primary Data > Export

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/ecd15efd-ab5b-49c8-aa3f-c3b5c1eda86d)

**Comment by jipclaassens** [comment]
@eoudejans: Solved writing using native tif storage manager from Export dialog in latest commit.

**Comment by jipclaassens** [comment]
@eoudejans: I can confirm that the rather vague error messages originate directly from libtiff, see:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8d56ce9f-ac78-405c-a5de-4c305617d7d2)

or more directly in the set error frame for libtif:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/effbdb7e-a713-4e24-aa6c-6e34c18aa343)
