### ISSUE TITLE
Add float64 to allowed value types in the potential operator

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#622]
The documentation already states one can use float64. But you actually can't.

**Comment by MaartenHilferink** [comment]
Reproduction case, just added to the Operator/cfg/operator.dms:



![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/ae541cf9-279b-4f8a-9de5-30d444596949)

**Comment by MaartenHilferink** [comment]
Workaround:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/78047c1f-c305-484c-bd3d-be4364ec348b)

**Comment by MaartenHilferink** [comment]
Fixed in 14.8.1:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/59dd1947-f92f-4284-a3ed-2791338eccff)
