### ISSUE TITLE
Treeview draw crash

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#623]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/bea22cde-db7f-45dc-a3e1-677a47c910f4)

OVSRV6:
C:\ProjDir\Jip\_Github_issues\NetworkModel_World_issue623\cfg\main.dms

/Analyses/Obtain_Settlement_Hierarchies/Australia_Oceania/Hierarchies_ReadOnly

**Comment by eoudejans** [comment]
@eoudejans Likely duplicate?

**Comment by eoudejans** [comment]
Duplicate to issue #591.

**Comment by eoudejans** [comment]
See response on work-around, issue has likely to do with the custom treeview connecting line png files being rendered. Disabling these is now optional and persistent through registry settings in Gui Options. See:

https://github.com/ObjectVision/GeoDMS/issues/591#issuecomment-1840458698

**Comment by eoudejans** [comment]
Nonetheless, a reproducible scenario would still be preferable to further narrow down and investigate on the true cause.
