### ISSUE TITLE
CreateView Error: Cannot create view with style 4 with context '/Desktops/Default/View4'

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#624]
LUS_demo

double-click on /Classifications/LUclasses/BrushColor

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/a50660df-d55d-41ad-8c46-77b02507c11a)

**Comment by eoudejans** [comment]
First observation is that the treeview icon for editpalette viewstyles did not work, now it does:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/c441632d-885b-49f2-9b99-85ec7290692d)

Additionally I temporarily mapped the edit palette viewstyle to tableview, so double-click no longer gives the error it cannot create view with style 4.

**Comment by eoudejans** [comment]
The PaletteEditor will be phased out, hence the treeview EditPalette icon is misleading in that it will not provide the user with a different view compared to a regular table view on default view. This change will be reverted until further notice.

Further improvement: TableView is the new desired method of viewing BrushColor, however the integer color codes are cryptic and can better be represented as colors using the theme/aspects system of geodms views.

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/502b3dab-08ec-4255-b243-be2e98ef5abb)
