### ISSUE TITLE
Unknown identifier 'ExportSettings/Docdata' 14.9.0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#629]
Ik krijg op iitem:

/ExportSettings

de melding Unknown identifier 'ExportSettings/Docdata'

het gaat om:
10468 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/WLO2024

ik zie het in veel  meer cfg's en in 8.8.1 was het bijvoorbeeld nog niet

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/b2785acd-b6ca-4b1f-a773-f7fbef4dd9b9)

**Comment by jipclaassens** [comment]
Fixed!

Even die url docdata weggooien.

**Comment by basvanbemmel** [comment]
ok werkt ja maar wat was de functie van die url dan enkel alleen metadata dus?
waarom die die url dan wel 8.8.1 kan vinden als syntax vind ik dan wel weer vreemd
Maar prima zo verder
