### ISSUE TITLE
Add header row to layer control

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#631]
For example:
- label
- lowerbound
- class count

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/6cc65775-4ff3-47c8-ac63-d651fc6188b1)

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/de7e2c47-f018-43b7-94a8-cf06fc54ff06)

**Comment by MaartenHilferink** [comment]
with 
`	paletteContainer->SetRowSepHeight(0);
`
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/09775acd-f2d0-4f84-ae2f-bb57196ce47c)
