### ISSUE TITLE
union_polygon levert leeg resultaat

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#632]
Ik voer een union_polygon uit op 6281318 items vervolgens krijg ik 1 record maar met:
"geometry_union" {0:}

code:

```
attribute<rdc_meter> geometry_boundingbox (poly) := points2sequence(pointset/point, pointset/sequence, pointset/ordinal);
			
parameter<rdc_meter> geometry_union (polygon) := union_polygon(ipolygon(geometry_boundingbox))[rdc_meter];
```

Er zijn nog twee andere zaken die mij opvallen in 14.8.0:

- Ik moet inzoomen om /SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwUitleglocaties/polydomain/geometry_boundingbox
te zien. Heel NL zie je niets; pas bij enkele zoom-ins zie je wat. Ik kan mij niet herinneren dat dat in vorige versies was.
- de WMS-achergrondlaag wordt vaak niet meer getoond als je een item in mapview sleept. Is dat gedrag gewijzigd in de nieuwste exe's?

cfg gegevens:
GeoDMS 14.8.0 (128 GB intern)
https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024  versie 10491
https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL versie 10492
open Casus.dms in Runs map
ga naar:
/SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwUitleglocaties/polydomain/geometry_boundingbox
en vervolgens naar
/SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwUitleglocaties/polydomain/geometry_union

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/a4494825-1395-44ae-aee4-9963e5579725)

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/22087cc3-df5b-4e8b-b247-52f9e1841263)
en bij map view melding
Transformation Error: illegal singular factor
This error may result from vizualising a geographic layer without bounding box or with a bounding box with zero area.

**Comment by jipclaassens** [comment]
Ha Bas,

Inderdaad je had de xy-coordinaten omgekeerd. Dus visueel ziet het er dan goed uit, maar de windingorder van het polygon is dan verkeerd om. Je kunt dit altijd even controleren door de area() te bepalen. Als die negatief is, is het niet goed.

We hebben je code geupdatet en iets versimpeld. 

Nog een vervolg vraag, wat wil je precies doen? Bouwblokken bepalen? Want dat kun je ook met de district-functie doen, dus hoef je er helemaal geen vectoren van te maken. Daarnaast heb je controle of je de 4-buren of 8-buren wilt meenemen.

**Comment by MaartenHilferink** [comment]
@basvanbemmel : mbt tot je eerste andere zaak:
- ik moet inzoomen om /SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwUitleglocaties/polydomain/geometry_boundingbox
te zien. Heel NL zie je niets; pas bij enkele zoom-ins zie je wat.

Bij het tekenen van een layer was tbv performance al lang (tenminste sinds begin Github dd 13-9-2022) zo dat polygonen worden overgeslagen waarvan de bounding box minder dan 0.5 pixel hoog of breed is (voor afronding na conversie). Dit zie je o.a. ook bij het tekenen van BAG pand geometieen als je heel NL bekijkt.

Bij rasters is dit niet zo, daar wordt uit gesampled op pixel punten.  

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a050904e-74a3-477d-8da4-f092b023979e)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/60c917c2-c1c7-4c9b-917e-032e9ebf129b)

**Comment by jipclaassens** [comment]
Dat wms niet altijd toegeveogd wordt is bekend, erg vervelend, helaas nog niet reproduceerdbaar. Zie issue #564

**Comment by basvanbemmel** [comment]
ok dank voor de onderstening duidelijk allemaal!

aangaande:
"Nog een vervolg vraag, wat wil je precies doen? Bouwblokken bepalen? Want dat kun je ook met de district-functie doen, dus hoef je er helemaal geen vectoren van te maken." 


Dat was ik al inderdaad van plan.

**Comment by jipclaassens** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e3a7405e-96b5-48c1-adde-dbd0124e4ed9)

**Comment by jipclaassens** [comment]
Eventueel ook nog in polygonen



![Image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8cf5ca3d-3281-47ca-8d9c-3419ee9fb890)

**Comment by basvanbemmel** [comment]
ok top dank!

**Comment by basvanbemmel** [comment]
Aangaande:

_Ik moet inzoomen om /SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwUitleglocaties/polydomain/geometry_boundingbox
te zien. Heel NL zie je niets; pas bij enkele zoom-ins zie je wat. Ik kan mij niet herinneren dat dat in vorige versies was._

Nog steeds een issue na overleg met Martin

PD 10501 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024

item
/Vergelijk_Planmonitor2023_2024/NNN2023_2024/impl/PD/Nr1/polydomain/geometry_boundingbox
met 5000 meter 
/Vergelijk_Planmonitor2023_2024/NNN2023_2024/impl/PD/Nr1/polydomain/geometry_boundingbox/PenWorldWidth
geen effect bij uitzoomen, niet zichtbaar op provincie-level zou wel moeten

**Comment by eoudejans** [comment]
@basvanbemmel voor vervolg zie issue #642
