### ISSUE TITLE
Resize legend size if less than 8 classes

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#633]
In this case, int32. 

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/83a44588-0144-4824-a717-141bd852dec2)

**Comment by MaartenHilferink** [comment]
Testcase in MicroTst.dms
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/80679a1a-05a1-4fd4-b087-a4950973505c)

**Comment by jipclaassens** [comment]
possible fix for #509
