### ISSUE TITLE
Discussion: metric conversion bug > syntax design

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#636]
gridsize * gridsize, wordt netjes meter2 en kan geconverteerd worden naar ha
gridsize^2f geeft een error, maar als je dit in een convert stopt geeft ie een verkeerd antwoord.
sqr(gridsize) werkt wel en kan geconverteerd worden naar ha

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/fdd99d62-5dc4-49b0-beb1-2f6b9efe24ce)

Maarten:
reden: $a^b$ wordt herschreven tot $\exp(b*\log(a))$ tenzij $b$ een specifiek getal is, met name 1 of 2 dacht ik, maar niet $float32(uint32(2))$
bug: $\exp(gridsize*\log(float32(uint32(2)))$ heeft geen metriek en wordt dan gecast/geconverteerd naar ha zonder dat er dus een relatie gevonden wordt met meter*meter en er dus niet gedeeld wordt door 10000. Ergens faalt hier de metrische logica; wellicht moest een onderscheid gemaakt worden tussen eenheidsconversie en casting, zodat minder snel het ene bedoeld kan zijn en het andere toegepast.

`...\GeoDMS-Test\Operator\cfg\MicroTst.dms`
`\MetriekConversie`

**Comment by eoudejans** [comment]
Proposal: issue warning if parameter or attribute with metric goes into exp function.

**Comment by eoudejans** [comment]
Version 14 warning, version 15 error.
