### ISSUE TITLE
bg_buffer_point, twee argument (size) ook als attribuut

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#640]
Soms is het handig om de grootte van het buffer at te laten hangen van een attribuut van de pointset, bijvoorbeeld iets als capactiteit.

Nu kan het size argument alleen een parameter zijn, graag ook dit als attribuut mogelijk maken.

Zelfde geldt voor andere buffer functies.,

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/3ac90fb8-f8e3-406c-947f-1c51063f2031)
