### ISSUE TITLE
Groups setting from config.ini incorrectly influences the new GUI toolbox

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#641]
See lus_demo

https://github.com/ObjectVision/LandUseModelling

**Comment by eoudejans** [comment]
The config.ini looks as follows:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/4191773b-a216-451e-84b7-7c6b4acf1434)

The NrGroups setting is used in the GetUserMode function in ShvUtils:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7cf3ab35-2d82-4db6-b681-3719fd835d49)

Which will influences the OnCommandEnable functions for specifically the selection mode buttons:
GraphicObject.cpp:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6c3c117d-4577-4975-b540-e68e6a7929e9)

And in ViewPort.cpp:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/66ed1ef0-d1d4-4875-8e78-cfce64470d88)


Suggested change would be to remove these conditionals al together as the toolbuttons are no longer conditionally shown.

**Comment by eoudejans** [comment]
From commit 581ed21 the NrGroups Tools setting in config.ini is no longer picked up by GeoDMS. In extension of this, UserMode() no longer is used by GeoDMS internally.
