### ISSUE TITLE
polygon features not visible, although the feature is large enough to show due to the PenWorldWidth

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#642]

**Comment by mtbeek32** [comment]
At this zoom level still visible:
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/9d60e190-2692-47a2-b3be-daab0acd4ee2)

One zoom level zoomed uit:
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/4c29aa34-0e23-4192-8a10-6ea0b35bd9fd)

see added configuration, request item: Square/geometry in MapView and zoom to the levels as in the images.

[issue_642.zip](https://github.com/ObjectVision/GeoDMS/files/14081904/issue_642.zip)

**Comment by eoudejans** [comment]
Suggestion: always draw all geometries within viewport.

**Comment by eoudejans** [comment]
Suggestion 2: Take into account PenWorldWidth and PenWidth for drawing decision.
And additionally in gui options for instance the minimum size of pixels to draw.

**Comment by MaartenHilferink** [comment]
First fix #649

**Comment by MaartenHilferink** [comment]
@erikthehero & @mtbeek32 Kunnen jullie in Settings->GUI options iets toevoegen om s_DrawingSizeThresholdInPixels in te stellen. De waarde was 0.5, nu (default) 0.0.

**Comment by eoudejans** [comment]
Implemented now also for GUI options, and stored in registry as DrawingSizeInPixels:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/91e3e81e-26b6-418e-a1a6-6a24054cd595)
