### ISSUE TITLE
Mismatch in projection when reading tiff results in crash

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#643]
OVSRV6
`C:\ProjDir\Jip\_Github_issues\geodms_africa_cusa2_issue643\cfg\Africa.dms`

`/SourceData/ReadSpatialData/floodMapGL_rp100y/inFile/ReadData`

**Comment by eoudejans** [comment]
The projection check using gdal.grid should have been informative about the mismatch between projections if the crash had not occurred:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/a074040b-87ff-4670-8340-95b83396b361)

**Comment by eoudejans** [comment]
Requesting item /SourceData/ReadSpatialData/floodMapGL_rp100y/inFile/ReadData results in crash, issue is reproducible on OVSRV07.

**Comment by eoudejans** [comment]
The grid domain was configured using Africa Albers Conic Equal Area, ESRI:102022 in item /Geometries/BaseProjection:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/a401700d-09fa-4bad-ba97-eb46cbb987ee)

Whereas the dataset of item /SourceData/ReadSpatialData/floodMapGL_rp100y/inFile/GridData has projection WGS84 or EPSG:4326:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/94c950e0-e9c8-4a15-9fce-0386ad3adf7b)

This lead to incorrect input raster to domain mapping resulting in a crash.

This is now properly detected at metainfo level and an error is thrown if for both the domain vu and dataset projections authority:code ie EPSG:4326 are available and do not match:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/d19329d3-21e6-4749-bff0-62420f3cb87d)
