### ISSUE TITLE
Invalid result when constructing a point-unit using gridset and the lower and upper bounds are minimum and maximum values of point datatype 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#644]
Below a unit with spatial reference is defined along with a grid domain unit that invalidly uses the lower- and upper bound of WGS84. Which is the lower- and upper bound of dpoint and not of the SpatialReference attribute:

```cpp
unit<dpoint> WGS84  : SpatialReference = "EPSG:4326", DialogData = "wms_layer_latlong", Label = "WGS84";

unit<wpoint> WGS84_grid :=
gridset(
	range(WGS84, LowerBound(WGS84),UpperBound(WGS84))
	, point_yx(-SourceRasterFactor, SourceRasterFactor, WGS84) 
	, point_yx(90d, -180d, WGS84) //top left
	, wpoint
)
{
}
```

This consequently is used when reading a grid dataset using:

```
unit<wpoint> Floods
: StorageName = "%ProjDir%/data/floodMapGL_rp100y.tif"
, StorageType = "gdal.grid"
, StorageReadOnly = "True"
, DialogData = "WGS84"
{
	attribute<float32> ReadData(WGS84_grid);
	attribute<bool> IsFlood(WGS84_grid) := ReadData > 0f;
}
```

Which results in invalid tile offsets and thus invalid reading of the grid dataset.

**Comment by jipclaassens** [comment]
Config: c:/**/geodms_africa_cusa2/cfg/africa.dms
Item: /SourceData/Floods/ReadData
Data: c:/**/floodMapGL_rp100y.tif

**Comment by jipclaassens** [comment]
Note that when debugging this issue, it is benefitial to uncheck Parallel Processing mode 1:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/487b70d6-e987-4428-9789-594a2de1a1b8)

**Comment by eoudejans** [comment]
range(t,lb(t), ub(t)) --> warning
