### ISSUE TITLE
unit met 1.0 float in range wordt vanzelf onwenselijk gecast naar integer

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#646]
Ik heb een lijst met getallen:
`	attribute<float32> fraction    :[0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2]; (N.B. in edit mode zie ik wel float32)
`
enkel het getal 1.0 wordt geïnterpreteerd als 1

Dit is een probleem als ik een template ga loopen, ik moet aparte code maken voor de 1.0 fraction

Het wordt duidelijk met een te open cfg het gaat om:

PD: 10515 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_cal21 --> deze werkt met 1.0
PD: 10514 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_cal21 --> deze werkt met de overige getallen

zie items:
/Classifications/BuiltupareaRuralFraction
/Scenarios/SSPs/SSP2/Export/Modelled/Fractions/F10

screendump PD 10515

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/9ccee134-d761-4296-8f9b-6592cf9abef5)

screendump PD 10514

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/d467fc53-7f81-4e50-8086-dbe3c8e415d0)

**Comment by eoudejans** [comment]
De string reprensentatie van 1.0f is inderdaad 1, zoals te zien in de TableView op item /Classifications/BuiltupareaRuralFraction/fraction:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6b9c6a15-00e8-4f6a-a380-9575ccbae207)

In de for_each_ne op regel ~250 van Modelled.dms wordt er een string gemaakt van Classifications/BuildupareaRuralFraction/fraction: 

```cpp
container Fractions := 
for_each_ne(Classifications/BuiltupareaRuralFraction/fractionstr, 
	'FractionT('
		+string(Classifications/BuiltupareaRuralFraction/fraction)+
		','+quote(Classifications/BuiltupareaRuralFraction/fractionstr)+
	')'
);
```
Wat zal resulteren in 1 voor 1.0 en x.x voor de overige floating point getallen. En 1.0 wordt default als float32 geinterpreteerd maar 1 als uint32, waar de foutmelding ook over gaat. De generieke oplossing hiervoor is om expliciet in de for_each_ne expression hard te maken dat de waarde van fraction als float32 in FractionT gaat:

```cpp
container Fractions := 
for_each_ne(Classifications/BuiltupareaRuralFraction/fractionstr, 
	'FractionT(float32('
		+string(Classifications/BuiltupareaRuralFraction/fraction)+
		'),'+quote(Classifications/BuiltupareaRuralFraction/fractionstr)+
	')'
);
```

En natuurlijk ook de template aanpassen naar float32:

```cpp
Template FractionT
{
parameter<float32> fraction;

  [....]
}
```

**Comment by basvanbemmel** [comment]
ok dank voor de hulp gelukt
