### ISSUE TITLE
group by count null foutieve output

### ISSUE THREAD

**Issue by IsmayPBL** [ObjectVision/GeoDMS#647]
GeoDMS 14.10.1
PD 10519 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024 
SD 10518 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL

Group by /PrivData/impl/Plancapaciteit_2024/NoordHolland/Read_NoordHolland_gpkg/typePlan 

Levert voor null values niet de goede count. Statistics window geeft wel aan 1035 null values. 

![image](https://github.com/ObjectVision/GeoDMS/assets/152558920/dbae1b5a-878e-431a-b4dd-dd7ac33069e8)
![image](https://github.com/ObjectVision/GeoDMS/assets/152558920/d117e1ee-845c-4195-ada4-89ecc49b6f96)

**Comment by eoudejans** [comment]
Issue is reproduceerbaar aan onze kant.

**Comment by eoudejans** [comment]
Goeie vondst, de huidige implementatie hinkt een beetje op twee gedachten: 
1. null waarden worden niet geteld in de unieke voorkomens en daarmee weggelaten uit de GroupBy functionaliteit
2. null waarden tellen wel mee in de unieke voorkomens en moeten van de juiste count worden voorzien.

Optie twee lijkt ons het juiste gedrag, onder meer omdat dit in lijn is met hoe je als gebruiker een dergelijke groepering zou opzetten in GeoDMS script taal.

**Comment by eoudejans** [comment]
Item /PrivData/impl/Plancapaciteit_2024/NoordHolland/Read_NoordHolland_gpkg/WTYPGGB heeft ook null-waarden:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/2417fd8e-16d4-46b3-af08-c7b5b714a583)

Echter komt hier wel uit wat we verachten na de GroupBy, namelijk optie 2 van hierboven:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/61b3861f-4cad-4b1a-a450-e1426ac29065)

**Comment by eoudejans** [comment]
Ook item: /PrivData/impl/Plancapaciteit_2024/NoordHolland/Read_NoordHolland_gpkg/Naamplan heeft 1 null waarde, wat wederom resulteert in een count voor null velden:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/fe0f5176-c1a9-426d-a174-3429c1c3f322)

De count(id) lijkt hier alleen foutief null waarden mee te tellen in de unique bij string attributen.

**Comment by MaartenHilferink** [comment]
in TableControl.cpp zorgt de volgende code voor uitvoering van een Group By:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/c8bb4e99-b1ec-4910-8b87-cdd0761a85d1)
Dus o.b.v. unique en rlookup, waarin <null> values niet mee doen. Optie 1 zou dus verwacht gedrag zijn.
In de operator.dms bij group by op null bevattende numerieke kolom A zien we: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/4394e781-a8b7-4727-a67a-b9c368afd35f)

Waarbij middenin was gegroepeerd op alleen de A kolom, en onderin op de id EN de A kolom

**Comment by MaartenHilferink** [comment]
De Unique operator negeert alleen *null* waarden voor numerieke en point attributen, voor strings en sequences worden deze niet ook genegeerd. Ik pas dit in branch v15 aan, hetgeen beschikbaar zal komen in GeoDms 15.0.0, want dit is mogelijk een breaking change, zodat alle unique varianten geen *null* resultaat geven.
