### ISSUE TITLE
PenWorldWidth wordt niet herkend

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#649]
14.10.1

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/8fc5becc-0de6-45e4-b5ed-93f4ee174fad)

En in built van 1 feb, 14.10.2

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5c46fbfc-b927-4c1c-aa2b-e0a130e631f0)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/66433885-1a4c-47dc-a836-d4a219e318bd)

**Comment by eoudejans** [comment]
world width uit configuratie halen en niet in base projection opslaan

**Comment by jipclaassens** [comment]
I can confirm this is indeed fixed
