### ISSUE TITLE
Wrong NrElements  in detail page

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#652]
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/9c23b86f-3c6a-47f9-94d2-4a641b08867a)

**Comment by MaartenHilferink** [comment]
Fixed in v14.11.1
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/3d19aa8a-2396-4acd-941b-3390d301f1c8)
