### ISSUE TITLE
warnings op gebruik van verdachte operaties in meta-scripting

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#653]
Meta Scripting, dwz rekenregel compositie en selectie en invoer voor for_each toepassingen, worden geacht simpel te zijn en het is onwenselijk voor de scheduling en GUI performance als complexe bewerkingen in meta-scripting gebruikt worden.

Voorstel:
- warning op alle vector, netwerk en raster operaties die vanuit UpdateMetaInfo worden aageroepen
- warning op alle attributen met meer dan 1 tile aan data (default 2^16 elementen) die bepaald of gebruikt worden tijdens UpdateMetaInfo -> #663

**Comment by MaartenHilferink** [comment]
Warnings come too frequent, also from primary processing.

**Comment by MaartenHilferink** [comment]
AddLayer->ZoomAll blockt ook de main thread en kan wachten op een geometry bepaling. Aanpassingen:
- geef de reden van blocking in de warning
- onderzoek het bepalen van extents o.b.v. range of SpatialReference -> EPSG -> Proj4

**Comment by eoudejans** [comment]
In context of SpatialReference and its bounding box, **area of use** is the right name and can be obtained using: `OGRSpatialReference->GetAreaOfUse(...);` 

For detailed usage information see:
https://gdal.org/doxygen/classOGRSpatialReference.html#a712698009e2f46bdb6bfae74269bc085
