### ISSUE TITLE
Second layer to mapview incompatible 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#655]
Opening a second item, double-clicking or dragging, into existing mapview is not allowed.

In 14.10.1:
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b54e16d3-1a5b-48ec-9c98-1d074670e023)

In 14.11.0
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e584cda0-db44-4f75-9817-fbbfc2608bff)

**Comment by jipclaassens** [comment]
Still an issue in 15.1.0

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/efde9d6a-a66b-4dd0-81f4-87b3d0630d5a)

ovsrv6:
C:\ProjDir\Jip\_Github_issues\Geodms_Africa_CUSA2_issue655\cfg\Africa.dms

Mapview on 
/Geometries/Corridor_BoundingBoxes/Libreville_Kribi_Douala_NDjamena/Corridor/BoundingBox
Adding:
/Geometries/Corridor_BoundingBoxes/Libreville_Kribi_Douala_NDjamena/Corridor/BoundingBox_Extended

Always opens a new mapview, and dragging gives the error message in eventlog.

**Comment by MaartenHilferink** [comment]
Fixed:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/2469133b-0375-4c08-85c1-07a1dcc7769d)

**Comment by jipclaassens** [comment]
It's back in 15.6.0

![image](https://github.com/user-attachments/assets/a5885c84-d9b3-4fdb-9785-df258bfe1d8a)

**Comment by jipclaassens** [comment]
Hmm, alt+r fixes the problem. Now it works as it should...
