### ISSUE TITLE
Container /Planmonitor2024/KwetsbareWaarden klapt langzaam open

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#657]
Voorbeeld van containeritem wat langzaam openklapt.

kloktijd: 48 seconden op 128GB systeem
GeoDMS 14.11.2
PD 10560: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024
SD: 10562: https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL
item:
/Planmonitor2024/KwetsbareWaarden

in 8.8.0 duurt het 3 seconden

**Comment by MaartenHilferink** [comment]
We vermoeden dat 8.8.0 met weggegooide CalcCache ook meer dan 3 seconden nodig heeft. @basvanbemmel Kun je tijd vermelden na weggooien calccache en dan eerste keer opnieuw opvragen ?

**Comment by basvanbemmel** [comment]
prima ik check het zo

**Comment by MaartenHilferink** [comment]
in overleg met Bas is vastgesteld dat 88.0 in casu niet een calc-cache gebruikt.

**Comment by eoudejans** [comment]
In GeoDMS 14.11.2 is de uitklaptijd aan mijn kant ~3 seconden. Ik zie wel dat er veel bestanden worden geraadpleegd:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/57070976-bac6-48fc-8fe3-1ef5ecb353d6)

Verder op te merken dat de voorbewerkingsstappen in fss bestanden ontbreken, dit bericht bijvoorbeeld:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/b6424e4c-38db-4e9d-a8c8-d4ae858d5940)

**Comment by basvanbemmel** [comment]
"Helaas" heb ik geconstateerd dat het gedrag niet altijd hetzelfde is.  Soms snel soms langzaam. Ik kan het nog niet verklaren. Ik houd het in de gaten.

Je moet eerst een enorme batch draaien, mocht je echt willen dan kan ik het resultaat opsturen.

**Comment by eoudejans** [comment]
Dat is interessante informatie, mogelijk heeft het te maken met de volgorde van operaties tijdens uitvoeren van metainfo. Ik zie op niveau van /Planmonitor2024/KwetsbareWaarden in de configuratie geen verdachte rekenregels staan.

**Comment by eoudejans** [comment]
Het wordt interessant als dit vaker voorkomt, ik heb item /Planmonitor2024/KwetsbareWaarden ~50 keer uitgeklapt en de configuratie opnieuw geladen en het is telkens 3 seconden rekentijd. Mocht je een reproduceerbaar scenario hebben of met de fss bestanden er bij af en toe tegen de lange uitklaptijd aan lopen dan kijk ik er graag naar. In het laatste geval zou ik er nu al naar willen kijken en dan met de fss bestanden er bij.

**Comment by basvanbemmel** [comment]
Ik stuur het voor de zekerheid op, wellicht toch iets te maken met ontwikkelwerk wat je dan weer met ALT-R opent ipv geheel afsluiten GUI.

**Comment by eoudejans** [comment]
Ik zal het scenario nogmaals bekijken met de fss bestanden.

**Comment by basvanbemmel** [comment]
IB heeft ook het idee dat het langzamer openklapt bij alt-R (dus nadat er code is gewijzgd)

**Comment by eoudejans** [comment]
Ik het langzame openklappen inmiddels een keer kunnen reproduceren.

**Comment by basvanbemmel** [comment]
ok mooi, ik had het vanochtend ook weer maar geen duidelijk recept helaas.

**Comment by eoudejans** [comment]
Vervolgstap is om het nogmaals te laten voordoen en dan vanuit de debug omgeving te bekijken wat er aan de hand is, krijgt vervolg.

**Comment by eoudejans** [comment]
See also: https://github.com/ObjectVision/GeoDMS/issues/653

**Comment by MaartenHilferink** [comment]
Block reason: checken of dit nog een issue is.

**Comment by MaartenHilferink** [comment]
TODO: bijhouden bij welke versies dit issue zich (nog?) voor doet.

**Comment by basvanbemmel** [comment]
Eerste maal openen in 15.7.0 deed bijna een minuut. 2emaal ging het heel snel.
Ook na afloggen op Azure en opnieuw het item op starten was snel.

Onduidelijke oorzaak in LD wordt niks weggeschreven

**Comment by eoudejans** [comment]
@basvanbemmel Zou het kunnen zijn dat Azure processen verhuist tijdens het opstarten van grote rekenprocessen die ineens meer geheugen claimt? Dat zou een mogelijke verklaring zijn voor het sporadische karakter van dit issue.
