### ISSUE TITLE
SourceData details O Dataset information isn't selectable when StorageReadOnly = "True" isn't specified.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#661]
OK: 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/74b1c411-579e-42a8-93ba-c48c71d394e3)

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/65ae5859-0059-447e-aaae-5be5528d5a90)

Not ok:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a9986457-8b80-4114-b2d1-0b95d256797c)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/a7cdf6e5-2e26-49e3-8fb4-24e7f791840a)

**Comment by MaartenHilferink** [comment]
Reproduction info:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d750dcd5-e2ad-4b3c-9ca8-ed362bfc87ce)

**Comment by eoudejans** [comment]
Adjustment behavior: button will be always available for storage managers, read and write.
Catch file does not exist errors and notify in detail page.

**Comment by eoudejans** [comment]
> Adjustment behavior: button will be always available for storage managers, read and write. Catch file does not exist errors and notify in detail page.

Implemented, closing issue.
