### ISSUE TITLE
2UP: export van boolean tif lukt niet

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#662]
Het lukt mij niet meer om een boolean item te exporteren in 14.11.2 Er wordt geen bestand gexporteerd hoewel in de log staat er wel een bestand is aangemaakt (voor de code native optie). 

ik heb vier smaken geprobeerd:
1) native in code (alleen de xml wordt aangemaakt): attribute<bool>    IsUrban   (Input/CompactedDomain)   := rank <= cuttingline[Scenarios/SSPs/SSP2/CompactedDomain/Country_rel], StorageName = "%LocalDataProjDir%/Urban/2020/M_1/IsUrban.tif";
2) gdal in code: 
attribute<bool>    IsUrban   (Input/CompactedDomain)   := rank <= cuttingline[Scenarios/SSPs/SSP2/CompactedDomain/Country_rel], StorageType     = "gdalwrite.grid", StorageName = "%LocalDataProjDir%/Urban/2020/M_1/IsUrban.tif";

3) export primary data: item native
4) export primary data: gdal

https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_2024
item: /Preprocessing/UrbanM1/IsUrban

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/02f4ad16-9808-4875-88b2-5b814321b284)

**Comment by eoudejans** [comment]
Issue is reproduceerbaar. 

Opmerkelijk dat via het export menu exporteren naar het native tif bestands formaat wel werkt:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/8b59138c-0b37-429b-a57a-7deddb79cf81)

**Comment by basvanbemmel** [comment]
"Opmerkelijk dat via het export menu exporteren naar het native tif bestands formaat wel werkt"
Maar dat werkt bij mij dus niet. Gebruik je wel dezelfde exe 14.11.2?

**Comment by basvanbemmel** [comment]
optie 1 blijkt wel te werken.
optie 3 zou moeten werken maar werkt niet
2 en 4 vereisen uint8 voor bool maar is niet wenselij (voor het inlezen wil ik de code niet wijzigen)

**Comment by eoudejans** [comment]
Wat betreft GDAL: de gdal-dms value type check voor schrijven faalt waardoor het bestand nooit wordt weggeschreven:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/018f271c-7cd2-460e-819b-d0a7288bfbaa)

**Comment by basvanbemmel** [comment]
GDAL ondersteund gewoon gewoon bool value type, niets aan te doen voor nu.

**Comment by eoudejans** [comment]
Het wegschrijven te schrijven item Preprocessing/UrbanM1/IsUrban heeft als domain nog het compacted domain. Dit is 1D en wordt niet weggeschreven. Het volgende stukje code werkt wel, en maakt van het compacte domain eerst het volledige domain en schrijft deze vervolgens weg:

```
attribute<bool> IsUrban_write_native_full(input/gtopo) := recollect_by_cond(Input/GridData/FreeLand, IsUrban)
    , StorageName = "%LocalDataProjDir%/Urban/2020/M_1/IsUrban_test.tif"
    , StorageType       = "tif"
    , StorageReadOnly = "False";
```

Dit laat onverlet dat:
- De eventlog wel aan geeft dat het item is weggeschreven, wat onjuist is 
- En het gebrek aan diagnostiek, wat de gebruiker in dit geval had kunnen melden dat het 1D domain niet met de native tif sm weggeschreven kan worden. 

Dat laatste is een punt van heroverweging, wanneer het mogelijk is het attribute in de mapview te tonen is het intern mogelijk de relatie op te zoeken en het compacted domain weg te schrijven naar tif; maar op dit moment werkt geodms nog niet zo.

**Comment by basvanbemmel** [comment]
ah ok dank voor het uitzoeken. Ik ga het checken. Misschien ook om iets begin maart even over te hebben.

**Comment by eoudejans** [comment]
Ik ben bezig met een verbetering van de diagnostiek bij het voorkomen van een dergelijke mismatch in domain dimensies.

**Comment by eoudejans** [comment]
Ook het log bericht: dataitem IS STORED IN .. wordt nu alleen weergegeven wanneer het item daadwerkelijk is weggeschreven:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/b4bf4a36-a685-40ed-89f6-f5e1dd07497c)
