### ISSUE TITLE
textbox for measurements too small, text is partly visible

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#665]
see e.g.:
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/c81053e7-3252-4671-b120-56ea5084a7ba)

possible solutions:
- increase size of textbox
- use a maximum size of the contents of the text box

**Comment by eoudejans** [comment]
Suggestion: change to float32, to limit rounding. 
Coordinates: limit rounding also in float32.

**Comment by eoudejans** [comment]
Using boost.format statusbar coordinate numericals for coordinates and measurements are formatted with 10 digits and precision of 2 digits:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/3ee013fb-b100-4775-b238-243ed8f5baab)

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/9b04a0cc-2e11-4f65-a3f4-0b07a51d2fe0)
