### ISSUE TITLE
toevoegen composition type leidt tot crash 14.12.0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#668]
Ik heb al een paar keer gemerkt dat het toevoegen van de composition type kan leiden tot een crash.

voorbeeld:
uitklappen van item /StraatjeErbij/Buffer/B200

attribute<bool> BebouwdeKomRand (poly,split_dissolve_HasBebouwdeKom) := IsDefined(invert(bebouwde_kom_rel_rand));

14.12.0
cfg **10645** https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/StraatjeErbij (let op gaat echt om deze versie!)
10636 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/b311a8fb-939e-4531-bded-60721778ce26)

**Comment by eoudejans** [comment]
Ik kan de crash herproduceren aan mijn kant.

**Comment by eoudejans** [comment]
Het betrof hier een access violation die we inmiddels hebben verholpen en zal in het vervolg uitkomen op een betere foutmelding en geen crash:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/e6e41e8d-fcb4-4213-bb53-4f0985293457)

Dit stukje code was de boosdoener, waar een poly value composition opgelegd werd aan een attribute met boolean values unit:

```cpp
attribute<bool> BebouwdeKomRand (poly,split_dissolve_HasBebouwdeKom) := IsDefined(invert(bebouwde_kom_rel_rand));
```

**Comment by eoudejans** [comment]
Naar verwachting deze week nog een prerelease GeoDMS versie met de fix.

**Comment by basvanbemmel** [comment]
ok top dank!
