### ISSUE TITLE
argmax certain/known (en anderen) naam aanpassen 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#67]
certain_arg[min|max][|_uint8|_uint16] -> arg[min|max]_alldefined[|_uint8|_uint16]

known_arg[min|max][|_uint8|_uint16] -> arg[min|max]_ifdefined[|_uint8|_uint16]

**Comment by basvanbemmel** [comment]
test

**Comment by MaartenHilferink** [comment]
also: 
- certain_[min|max]_elem -> [min|max]_elem_alldefined
- known_[min|max]_elem -> [min|max]_elem_ifdefined

**Comment by MaartenHilferink** [comment]
Background infor: https://trello.com/c/5RKbegkG/97-argmax-met-null-waarden

**Comment by mtbeek32** [comment]
replacements also executed in test project

**Comment by MaartenHilferink** [comment]
This (8.6.0 breaking) change will be released as 8.6.4 as the certain and known prefixes were introduced in this 8.6 version.
