### ISSUE TITLE
CalculationRule & ParseResult back in Generic Properties

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#671]
Since 14.13.0 the CalculationRule & ParseResult are back in the Generic properties.

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/4bd279d1-022c-4a98-8545-70974f7fe9f3)

It would be nice to use the summary/details HTML 5 tags to make this expandable. The Current QTTextBrowser does not support these HTML tags. Reconsider using the QTWebEngine instead.

**Comment by eoudejans** [comment]
Initial swap of QTextBrowser to QtWebEngineView in QWebEngine branch:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/2c7bc0aa-359c-4424-b9dd-14643818d949)

**Comment by MaartenHilferink** [comment]
Modular builds of QTWebEngine? b.v. zonder JavaScript en WebGL ?
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/225b2c25-91df-434f-bb17-f09fddc5894b)

**Comment by MaartenHilferink** [comment]
https://chat.openai.com/share/d6925725-16be-4b57-9303-1857e4508e46

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/fa97145f-6984-4883-981c-ee8f22f90f9b)

Ctrl-F now also works for detail pages using QWebEngineView.

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/33459d7b-ad01-4918-91f4-93019887d3e6)
Implemented view page source to detail pages.
