### ISSUE TITLE
Layer show/hide status in LayerControl beter zichtbaar maken

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#676]
Uit verslag overleg:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/676507a7-f865-4460-88fb-fbc98c4e86a6)

**Comment by mtbeek32** [comment]
Suggesties: 

1. Maak layers die niet zichtbaar zijn 'sunken', zie voorbeeld:

![Image](https://github.com/ObjectVision/GeoDMS/assets/24246911/d33a5c3f-334d-4bd1-96b4-8e2f6f724df2)

2. Layers die niet zichtbaar zijn kunnen geen actieve layer meer zijn.

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e45b3947-9ca4-47ee-a289-2e910be9d41d)

**Comment by mtbeek32** [comment]
After make a later invisible, it is no longer the active layer, which is fine.

The title of the map view still indicates it is the active later:
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/dac698d0-deeb-4bac-aadb-980ec58782d7)
