### ISSUE TITLE
CC BY-SA 4.0 ref in GeoDms wiki footer

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#682]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/8f94f6e1-3886-446d-918e-5e189a2e40e3)

See also #677

**Comment by mtbeek32** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/8fbc0f68-3e8f-4acf-94a2-eb9bb18e0e44)
