### ISSUE TITLE
CC BY-SA 4.0 toepassen in geodms.nl footer

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#683]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/277291ea-976a-438f-b854-8dd977464b73)
See also #677 

En links naar sections op de main index page ?

**Comment by eoudejans** [comment]
Now listing both source code- and documentation licenses:
![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/a97d8cc4-5ece-4d03-aad1-f22c1e138334)
