### ISSUE TITLE
unify code of GetCounts and Modus functions, and Unique

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#684]
Places where frequency tables are made and used

1. GetCounts (in CalcClassBreaks.h) results contain a ValueCountPairContainer, used in class-break functions and in the MapView for creating a suitable palette for a range of values.
2. ModusTotBySet, ModusTotByTable, ModusPartBySet and ModusPartByTable (in Modus.cpp) and Weighted variants, and formerly: [Weighed]Modus[xxx]ByIndex, used for the modus and similar aggregation functions: 
3. GetUniqueValues (in Unique.cpp), very similar to 1, but without counting
4. rlookup -> MakeIndex, also similar, but with keeping first index as a way of 'counting'.

See also #556 

Advantages of options 1 and 3 are: very Multithreaded by bottom-up sort and aggregate by merge method
Advantage of 2. is: bucket count when appropiate (when pCount * vCount < nCount), but bucket count is much less suitable for multithreading.

**Comment by MaartenHilferink** [comment]
Improvements at merge
- GetCounts converts all values to Float64, this is better done after completing the count.
- Modus and similar aggregation functions become parallel
- unique would use bucket count when vCount <= nCount

Further options:
- make the count type dependent on the domain or nCount and provide specific function overloads with safe increments for expected smaller counts
- revitalize ModusByIndex for strings (now not supported), and share indexing code with rlookup, there use bucket-index (as in invert) and table lookup when vCount <= nCount
Issues:
Making bucked count multi threaded increases it's memory and time with T * pCount * vCount *sizeof(Counter) where T is the number of concurrent threads and s = sizeof(Counter)

**Comment by MaartenHilferink** [comment]
ref the first issue: https://chat.openai.com/share/5518acdd-4f17-4811-bb39-df953efa5a64

**Comment by jipclaassens** [comment]
Use case:

2BURP, to calculate degree of urbanisation it uses 20 iterations per time step:
`/Analysis/Future/Indicators/Prep/DegreesOfUrbanisation/Y2030/Urban_Centre/Apply_smoothing/smoothing_loop/iter0/NextValue/MedianFiltering`

**Comment by MaartenHilferink** [comment]
/Analysis/Future/indicators/Prep/Population/Y2030

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/9b9b51e8-6c14-4130-a01c-47f90053e137)
01:36 instead of 05:28 = 232 of the 328 seconds faster, i.e. 70% speed-up.

**Comment by MaartenHilferink** [comment]
Todo's:
[ ] use GetWallCounts in Modus
[ ] use GetWallCounts in WeightedModus
[ ] use ByTable for GetCounts in Classify
[ ] move existing GetUniqueWallValues  to ValuesTable.h
[ ] use ByTable for GetCounts in JenksFisherClassBreaks
[ ] use ByTable for GetCounts in Unique
[ ] use GetWallCounts and GetTable for rlookup and ApplyClassification

**Comment by jipclaassens** [comment]
Test Modus tijd:

`/Preprocessing/DegreesOfUrbanisation/y2020/StoreTypology`
Africa

15.3.0 (2024-06-26 10.00)
2.43 min

**Comment by MaartenHilferink** [comment]
Met parallelle sums: 01:13 i.p.v. 01:36.

**Comment by MaartenHilferink** [comment]
TODO: ValueGetter en WeightGetter aanpassen aan los te laten LazyTiles, conform IndexGetters, en m_Adi helemaal uit valuegetter verwijderen.
