### ISSUE TITLE
assign_polygon Error in 14.3.2 niet in 14.3.1

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#685]
Ik krijg een error op:
/Analysis/Wind_restricties/Dynamisch/kwestbare_gebouwen/Woningen/geometry_buffer

assign_polygon Error: second ring with same orientation detected as first ring; consider using an operation that supports multi_polygons (bg_buffer_multi_polygon or outer_multi_polygon)

GeoDMS 14.3.2
PD 10720: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024
SD 10718: https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL

Error is niet in 14.3.1, is dat conform zoals het bedoeld is (https://github.com/ObjectVision/GeoDMS/releases/tag/v14.13.2)?

**Comment by jipclaassens** [comment]
Ha Bas, de bg_buffer_polygon operator wordt uitgefaseerd. Deze is vervangen door bg_buffer_single_polygon en bg_buffer_multi_polygon. In deze situatie heb je de multi polygon variant nodig. Dit heb ik aangepast en dan werkt het wel.

**Comment by basvanbemmel** [comment]
Ok top dank

**Comment by jipclaassens** [comment]
Rij: 1053676 van /Analysis/Wind_restricties/Dynamisch/kwestbare_gebouwen/Woningen/geometry

{12: {430,451; 180,160} {430,452; 180,166} {430,449; 180,166} {430,450; 180,170} {430,445; 180,171} {430,443; 180,163} {430,448; 180,161} {430,448; 180,160} {430,451; 180,160} {430,450; 180,157} {430,450; 180,157} {430,451; 180,160}} 

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5556a7f9-48bb-4782-ae37-4efbb2e9bf57)
