### ISSUE TITLE
MapView Toolbar active tool style disappears after activating Table MdiSubWindow and then MapView again

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#688]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/27b7cd13-72bc-4b9f-90a3-90aa3726a861)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0d2f5b7c-49f3-4d8c-9f49-91c17903909a)

**Comment by MaartenHilferink** [comment]
Additional GUI issues
- [ ] Alt-D should attribute key focus to the address bar
- [ ] When Address-Bar has key focus, Tab should attribute key focus to the TreeView (for scrolling through the items with arrow keys and first characters)
- [ ] When TreeView has key focus, Tab should attribute key focus to the EventLog (for scrolling)
- [ ] Changing selection of the districts in the MapView are only reflected in the table view when MouseMove over the TableControl area.

**Comment by eoudejans** [comment]
Clicking on the header of the map- or tableview does update the toolbar to the correct state:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/9a901fab-bd89-4504-8e30-0b37cfd18f67)

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7a8cd2ad-1c9c-48fd-a0b9-63c154b5decb)

However indeed clicking on the geodms view does not update the toolbar properly.

**Comment by MaartenHilferink** [comment]
TableView Toolbar: when group-by is selected, and a new TableView is opened, the group-by depression continues

**Comment by MaartenHilferink** [comment]
oops, last commit was to close #658

**Comment by eoudejans** [comment]
There is unconnectedness between activating a dms hwnd (ie table- or mapview) and activating the Qt mdi subwindow.

**Comment by MaartenHilferink** [comment]
Fixed with the recent changes to updateDmstoolbarButtonVisualStates
