### ISSUE TITLE
Teveel updatemetainfo warnings

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#691]
PD: 2BURP
`/SourceData/Physical/Water/Inland_Water/Write_per_subgrid`

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/3633b5fd-dd66-4dc1-9e40-d270f417a8d2)

Rekenregel:
```
attribute<bool>              Write_per_subgrid (domain_sub) := IsDefined(poly2grid(Inland_Water/geometry, domain_sub)), StorageName = "%ToBURPDataDir%/physical/Water/IsInlandWater_subdomain.tif";
```

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/e6286dfd-2d26-4aee-9350-2b48e1aa2f2f)
