### ISSUE TITLE
range function with two arguments

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#695]
The range function needs 3 arguments. The first argument is in use to configure a base unit or projection.

In some cases there is no need to configure a base unit or projection for the range. In these cases configuring a first argument is confusing, as it has no function. For these cases a range function with 2 arguments would be more intuitive.

**Comment by eoudejans** [comment]
Try to implement this change in line with point_xy.. etc functionality.

**Comment by MaartenHilferink** [comment]
Dit kan nu vanaf 14.17.0 geconfigureerd worden:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/fd28cdd3-a508-43d8-a0ef-48b6616a4037)
