### ISSUE TITLE
Show statistics of disabled mapview layer allowed but does nothing

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#698]
If you select 'show statistics' from context menu of a disabled layer, nothing happens.
Activating the layer and ask to show statistics again does work.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/879ac1ff-b6c0-4eec-ad73-b5cae8cd3947)

**Comment by MaartenHilferink** [comment]
Relevant code (and similar in DataItemColumn): 

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/25723905-cabf-4619-8e0c-0cf2a0f939f5)

The execution of a RequiestClientDms only forwards the command to active layer controls; I'll register a related member function that doesn't have that restriction.
