### ISSUE TITLE
gpkg bestand extra lijnen tov QGIS-ARCGIS

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#701]
Er worden extra lijnen getekend in dit gpkg bestand o.a. tussen Muiden en Lelystad. Onduidelijk waarom het is niet het geval in ArcMAP en QGIS

[vw_nl_netlijnen_2023_v4_5_december.zip](https://github.com/ObjectVision/GeoDMS/files/14854130/vw_nl_netlijnen_2023_v4_5_december.zip)

GeoDMS 14.14.0
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/4b79f60f-da18-4302-8611-73fc8a4cbe35)

QGIS 3.34.2
![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/4e457647-2736-48e8-b718-1baa60282d99)

**Comment by basvanbemmel** [comment]
Heeft op zich niet heel prio, maar wel handig als toch duidelijk wordt waarom dit zo is

**Comment by eoudejans** [comment]
Goeie observatie, het gaat hier om een multilinestring bestand, met een structuur die we op dit moment als een ring interpreteren, wat vervolgens de hulplijn van het eindpunt naar het beginpunt laat tekenen:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/a095f70f-2034-4751-b877-2ec8a7d5ff79)

Het interpreteren van een multilinestring gdal type als sequence of points (aka arc) hebben we onlangs experimenteel door laten gaan en werkt nog niet goed voor linestrings met werkelijke multilinestring structuren zoals bijvoorbeeld rotondes in een wegennetwerk en het geval wat jij terecht hebt geobserveerd. Voorheen interpreteerden we multilinestrings als WKT string geometrie.

**Comment by eoudejans** [comment]
Daarmee kan het gebruik van multilinestring bestanden op dit moment nog leiden tot ongewenste geometrie resultaten. 
We hebben naar aanleiding van dit issue maar ook naar aanleiding van discussies over multilinestrings eerder dit jaar een implementatie route uitgedacht waarmee geodms multilinestrings volledig zal ondersteunen:

In lijn met (multi)polygons willen we multilinestrings encoderen als een sequentie van punten. Een van de redenen om dit zo te doen is performance, maar daarnaast ook het gebruik van een simpel datamodel: sequentie van punten ten opzichte van een hierarchische structuur van afhankelijke geometrieen.

Technisch zal een multilinestring als een serie linestrings geencodeerd worden met quoteren om verschillende linestrings aan te geven, waar het quoterings symbool het eerste punt is. Dit onder de aanname dat er geen twee opeenvolgende punten in (multi)linestrings voor komen.

De implementatie zal beslaan:
- [ ] encodering van multilinestrings als sequentie van punten
- [ ] decodering van multilinestrings als sequentie van punten

En daarnaast het implementeren en/decodering multilinestrings in:
- [ ] inlezen met gdal.vect
- [ ] wegschrijven met gdal.vect
- [ ] visualisatie mapview
- [ ] impedance functies
- [ ] overige geometrische functies waar van toepassing

**Comment by eoudejans** [comment]
Tot we hier aan toe zijn gekomen geven we vanaf nu een warning uit wanneer gebruikers toch een multilinestring bestand willen inlezen:

```cpp
if (layer_geometry_type == OGRwkbGeometryType::wkbMultiLineString)
	reportF(SeverityTypeID::ST_Warning, "gdal.vect", "storage [[%s]] has geometry type wkbMultiLineString, which is reinterpreted to plain linestring, possibly resulting in incorrect geometries.", storageHolder->GetFullName());
```

**Comment by eoudejans** [comment]
@basvanbemmel na @MaartenHilferink zijn laatste commit leest je bestand goed in:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/e1f38d06-6708-4103-a4a0-467e05a1894e)

Daarmee hebben we een grote stap gezet om in GeoDMS multilinestrings volledig te ondersteunen. Zie lijst in bovenstaande comment welke delen van GeoDMS nog geen multilinestrings ondersteunen.

**Comment by eoudejans** [comment]
Zie geselecteerde kruizing:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6abf4f79-baaa-46f8-821c-32d2be83dbcb)

**Comment by eoudejans** [comment]
Extra verbindingslijnstuk komt niet meer voor na laatste commit:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/005ba55a-ff98-48e8-996e-56bc84bf6684)

**Comment by eoudejans** [comment]
Dump of manually labelled encoded (undefined separated) multi linestring in GeoDMS:

```
B {509191.388, 165254.648
 
 {null, null
 
B {509191.388, 165254.648
 {509241.121, 165299.823
 {509354.452, 165405.457
A {509429.009, 165419.062
 
 {null, null
 
B {509191.388, 165254.648
 {509269.796, 165269.13
 {509383.148, 165374.752
A {509429.009, 165419.062
 
 {null, null} 
 
A {509429.009, 165419.062} 
  {509818.334, 165320.043}
 
 }

```

**Comment by eoudejans** [comment]
See implementation of simplify multi linestring:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/0f7cfb53-c5de-4717-baf2-096314068d14)

Implemented as simplification per linestring.

**Comment by jipclaassens** [comment]
Extra warning for dyna_point:

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/28dfbb53-2b16-4acb-b111-4faf478fd142)
