### ISSUE TITLE
gpkg met storagename in code werkt niet

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#702]
Als ik een gpkg configureer in code lijkt de gpkg niet in orde, maar handmatig exporteren (export primary data) werkt wel.

code:
```
unit<uint32>  Gemeente2023 := RegioIndelingen/Gemeente2023
, StorageType = "gdalwrite.vect"
, StorageReadOnly = "False"
, StorageName  = '%LocalDataProjDir%/Planmonitor/Woondeals/Woondeals_versus_BAU_Y2030.gpkg'//gpkg werkt niet
```

GeoDMS 14.4.0
PD 10810: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024
/SourceData/Beleid2024/Plancapaciteit/Wonen/Woondeals/Verschil_Model_Woondeals/Gemeente2023

[Woondeals_versus_BAU_Y2030_gpkg.zip](https://github.com/ObjectVision/GeoDMS/files/14854799/Woondeals_versus_BAU_Y2030_gpkg.zip)
[Woondeals_versus_BAU_Y2030_hand_not_native.zip](https://github.com/ObjectVision/GeoDMS/files/14854800/Woondeals_versus_BAU_Y2030_hand_not_native.zip)

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/e285bf56-96f9-42ca-a103-05c6c87d7fd2)

**Comment by eoudejans** [comment]
Related to #713

**Comment by eoudejans** [comment]
Om dit issue te reproduceren mis ik deze file uit vermoedelijk een voorbewerkingsstap: 
C:/LocalData/planmonitor2024/Allocatie/WLO_hoog_BAU/StandY2030/Wonen/Eengezins_VrijeSector.tif
Ingelezen met item: /CaseIndicatoren/Y2030/impl/Stand_with_path/Wonen/eengezins_VrijeSector

We hebben vorige week een soortgelijke bug opgelost in #713, deze komt mee in de eerst volgende prerelease. Deze prerelease verwacht ik in de loop van deze week online.

**Comment by eoudejans** [comment]
Item doorgerekend en de geopackage lijkt nu in orde, zie side-by-side:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/6eee0b20-1723-4f10-91b8-238a22a071d0)

**Comment by eoudejans** [comment]
Naar verwachting komen we uiterlijk woensdag met een nieuwe dms versie, daar zou dit probleem in opgelost moeten zijn.
