### ISSUE TITLE
GeoDmsImGui Font compatible with tableview, windows and Linux.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#71]
![image](https://user-images.githubusercontent.com/2284361/211852429-ad5998df-4548-4c60-a78d-6fd56b7a01b2.png)

**Comment by MaartenHilferink** [comment]
Is using Tahoma in ImGUI an option? See also: https://wiki.debian.org/tahoma

**Comment by eoudejans** [comment]
GeoDMSImGui now uses the open source font noto sans: https://fonts.google.com/noto/specimen/Noto+Sans
Which supports both modern and ancient languages as well as a math font.

For weight the medium style is used.

**Comment by MaartenHilferink** [comment]
Implemented now is the loading of %exeDir%\misc\fonts\NotoSans-Medium.ttf
and "Noto Sans Medium" is now the default font in TableView and MapView.

**Comment by MaartenHilferink** [comment]
See also #169

**Comment by jipclaassens** [comment]
Font size is now much smaller, especially in the table header.

in 7414:
![image](https://user-images.githubusercontent.com/48675272/225028002-a6e331a4-bb7b-4861-a7a3-0088d3e6a364.png)

in 8.7.2:
![image](https://user-images.githubusercontent.com/48675272/225028058-cacea357-6c43-4318-b0ae-d5855b11c3de.png)

**Comment by mtbeek32** [comment]
I checked this at a pixel level and noticed a 40% smaller size in pixels.

**Comment by eoudejans** [comment]
![font_size_table_header_difference](https://user-images.githubusercontent.com/96182097/225060292-fd741b47-9b85-4c8e-848a-2151c223544c.png)
In TextControl.cpp line 177, DrawText( is called with font NULL for the table header, and called from DrawEditText for table elements.

**Comment by MaartenHilferink** [comment]
Font was set to Noro Sans Medium in DataView.cpp (line 316) and FontRole.h (line 50) and is temp. reverted to "Tahoma" and "" in 8.8.0. Universal font with fitting sizes is now targeted at 8.8.1.
