### ISSUE TITLE
'proj Error: error(2049): Invalid coordinate' in griddist_maximp_untiled_latitude_specific

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#718]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/1797e42c-b2ab-45e1-accf-e337c6f51ec0)

/Preprocessing/GridDists/AccessGrids_grid/cities/costsgrid_untiled_maximp_latitude_specific

**Comment by MaartenHilferink** [comment]
See also #673 comment over latitude specific variants, lower right: is precies dit, maar dan voor Villages i.p.v. Cities.

**Comment by MaartenHilferink** [comment]
Fixed in: https://github.com/ObjectVision/GeoDMS/commit/2cbf65afb50100501929b4d60ec5b88ca4419029
