### ISSUE TITLE
GeoDMS 8.6.2 crasht bij opvragen geometry

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#72]
GeoDMS 8.6.2
9448 https://xxxxxxx/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3
9442 https://xxxxxxx/ruimtescanner/PBL/SourceData/Trunk/RSL

open casus.dms
Variant_name BAUZP
Casus_name WLO_hoog_BAUZP 

oproepen: 
/Analysis/Allocatie/Zichtjaren/Y2050/Impl/ReadStandWind/WindPolygoon/polydomain2/een
GeoDMS klapt eruit zonder enige melding bij opvragen in MapView

Let op: Allocatie dient te zijn uitgerekend voor de betreffende variant

**Comment by basvanbemmel** [comment]
Werkt dus wel in 7414

**Comment by MaartenHilferink** [comment]
Ter reproductie prepare ik nu een productierun voor BAUZP

**Comment by MaartenHilferink** [comment]
In 8.6.3. lijkt dit opgelost

**Comment by basvanbemmel** [comment]
ok mooi!

**Comment by MaartenHilferink** [comment]
Zie https://github.com/ObjectVision/GeoDMS/releases/tag/v8.6.3
