### ISSUE TITLE
SelCount column presents Domain mismatch when selecting features

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#722]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/8582e2ef-fcbc-4a74-8fb1-8824e074eb55)

Steps to reproduce:
test: Microtst
request item: buffering/Outer/geometry in MapView
activate tool: Select all elements

In layer control error occurs

**Comment by MaartenHilferink** [comment]
reproduced
