### ISSUE TITLE
Illegal Abstract GetRangeAsIRect called.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#731]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\2BURP_issue731\cfg\main.dms`

Mapview of:
`/Preprocessing/DegreeOfUrbanisation/Urban_Centre/FindContiguousCells_CD/GroupCellSize`

From the debugger, the following errors, in a release, it crashes.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/57d65b28-42a9-40e8-ad0c-475fe142203a)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/35bdff6b-6b5b-4773-8856-9d30dbaf8536)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/e7f90d79-497f-4d1f-a981-23ab580834c5)

**Comment by MaartenHilferink** [comment]
Note that the domain of the district argument seems to be an unit<uint32> compacted domain and not a raster. However, the diagnostics must improve.

**Comment by MaartenHilferink** [comment]
Debug result now is:

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d598076c-156c-4214-9dc3-b1d6105d5d2b)

**Comment by MaartenHilferink** [comment]
After adding another check, the diagnostic now is:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/c93449ad-3818-4405-aa09-1bb0eb79f989)
