### ISSUE TITLE
Operator strongly_connected_components not merged from v14 into v15

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#732]
Needed for NetworkModel_EU @cjacobscrisioni

**Comment by MaartenHilferink** [comment]
Het lijkt gewoon aanwezig: ConnectedParts.cpp lines 38 en 328...426 en 436. 
@jipclaassens : Kun je een screenshot o.i.d. toevoegen waaruit je afleidde dat strongly_connected_compontents niet meer werkt in v15 ?

**Comment by cjacobscrisioni** [comment]
@MaartenHilferink , I think this is my doing... I checked and rechecked before mentioning this to @jipclaassens , but cannot reproduce the issue right now as 15.0.1 seems perfectly comfortable with the strongly_connected_components syntax

So either I confused 14.15.x with 15.0.1 or I made a syntax error with 15.0.1, then fixed it after reverting to 14.16.0, and forgot to check. 

In any case, my bad, sorry!!!!! can be closed.
