### ISSUE TITLE
multi_linestring ook supporten bij inlezen via native shp storage manager

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#741]
Conform zoals al opgelost in gdal.vect

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/46f349fd-ceda-4fa3-8968-b7648c1349b4)

zie /Invoer/RuimtelijkeData/WarmteBronnen/Lijnbronnen/LijnenSet/geometry

**Comment by poorthuis-w** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/106243975/f7b810e7-03df-4f09-b032-851ab027145e)

De before visualisatie van de lijnenset

**Comment by MaartenHilferink** [comment]
Fixed voor .shp"
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/70e2ee4b-04db-4a54-ba86-616627fd5112)
