### ISSUE TITLE
Add value composition to for_each

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#742]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/dbeafc14-0853-4b2f-abff-70ac50972172)

```
unit<uint8> Continents := Classifications/Continents
, storagename = "= propvalue(store_Continents, 'storagename')", storagereadonly = "True"
{
	attribute<LatLong>  geometry       (poly);
	attribute<string>   name                  := Classifications/Continents/name;
	attribute<.>        per_grid     (domain) := poly2grid(geometry , domain);
	attribute<World>    World_rel             := const(0[WOrld],.);
	
	container V := for_each_nedv(AsItemName(name), String(ID(.))+'[..]', void, .);
	
	container perContinent := 
		for_each_nedv(
			name
			, 'geometry[V/'+name+']'
			, void
			, LatLong
		);
}
```

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/93c1d11e-b98c-420b-9e1a-10dfd8953786)

**Comment by jipclaassens** [comment]
@MaartenHilferink could you also add this to the documentation?

https://github.com/ObjectVision/GeoDMS/wiki/For_each

**Comment by MaartenHilferink** [comment]
TODO: documentatie aanpassen op vcp en vcs

**Comment by MaartenHilferink** [comment]
see additions in 
- https://github.com/ObjectVision/GeoDMS/wiki/For_each
- https://github.com/ObjectVision/GeoDMS/wiki/For_each_ind
