### ISSUE TITLE
Recursive of 'using' causes hang

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#744]
2burp

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/33643aea-165d-47a6-854f-fc0e38531923)

Adding `SourceData/RegionalUnits` to the using property causes the hang.

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/083b05e5-183f-4aea-aa64-e4d57979ee38)
