### ISSUE TITLE
Click floppy icon results in hang

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#746]
LUS_demo
get result
click floppy icon

**Comment by eoudejans** [comment]
Reproducibility confirmed. Hang is related to drawing of wms background layer:

In function MovableObject::GetAsDDBitmap:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/0894a6f6-84aa-4579-9d08-a946523ae172)

And in drawer.Visit(this) the background layer is visited, which seems to request a lot more tiles than necessary.

**Comment by eoudejans** [comment]
Turning off the wms background layer acts as a temporary workaround.

**Comment by eoudejans** [comment]
Temporarily removed export to BMP functionality in dms mapview:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/7421a3d6-8af4-4cd6-a213-98f75fc069b6)

**Comment by jipclaassens** [comment]
related to #630
