### ISSUE TITLE
IntegrityCheck fail of one item, also result in error in other unrelated item

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#748]
`C:\ProjDir\Jip\_Github_issues\2BURP_issue748\cfg\main.dms`

Table-view of both these items:
```
/Analysis/Future/Indicators/Prep/Generate_Population
/Analysis/Future/Indicators/Prep/Generate_BuiltUp_Total_Shares
```

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/408858ef-a2e7-408c-b0a8-cb6c22252ab5)
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/3b597e13-feda-4029-be18-30490a3d90b3)

**Comment by MaartenHilferink** [comment]
Is Y2060/BuiltUp niet afhankelijk van Y21050/Population via de DoU berekening, dus Not A Defect ?

**Comment by jipclaassens** [comment]
Klopt, sorry deze had al gesloten kunnen worden.
