### ISSUE TITLE
GroupBy button does not work anymore in 15.3.0

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#749]

**Comment by MaartenHilferink** [comment]
Suspected code change:
https://github.com/ObjectVision/GeoDMS/commit/f50a2905c33faacf0d38813714bbfafc57b1502f
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/c9460f63-254c-4fda-b2da-b5ab1d882954)

**Comment by MaartenHilferink** [comment]
Steps to reproduce in 2Burp:
goto /SourceData/RegionalUnits/Countries
Ctrl-D
Press Group-by button.

**Comment by MaartenHilferink** [comment]
Cannot reproduce with latest built of 15.3.0

**Comment by jipclaassens** [comment]
Fixed
