### ISSUE TITLE
alt_imp in impedance_matrix_od64 results in 0

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#751]
OVSRV6:
`C:\ProjDir\Jip\_Github_issues\NetworkModel_PBL_issue751\cfg\main.dms`

De alt_imp die de impedance_matrix uitspuugt is 0.
Maar uit de afleiding van de LinkSet volgt dat alt_imp (length) 0.200887 km is. 

`/NetworkSetup/ConfigurationPerRegio/all/PublicTransport/At_07h00m00s/CreateODs/OD_traveltime_W_OV_W/OD_wPrijzen`
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/b70e439c-9a9b-49fb-88b1-1d93de33c398)

`/NetworkSetup/ConfigurationPerRegio/all/PublicTransport/At_07h00m00s/CreateODs/OD_traveltime_W_OV_W/OD_wPrijzen/AfgelegdeReis`
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/179033b6-bec0-4d6d-a1dc-b64f367fae03)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/5939a72d-77bb-44d7-92f9-0eac68f440ac)

**Comment by jipclaassens** [comment]
update nodeALW[node] info
node: 24526075
currLink: 32372596

node: 245377187
currLink:32418630

node: 24538299
currLink: 26890395
 nodeALW[prevNode]=333.846130
altLinkWeights[currLink] = 15.9215994
nodeALW[node] = 349.767731

**Comment by jipclaassens** [comment]
node = 4628680, startPoint 0
▶ | Node_rel | 0x000001b7a6876ac0 {4628680}
▶ | Impedances | 0x000001b7a3ad2eb0 {357.000000} 
▶ | Zone_rel | 0x000001b790e99ba0 {0}


first child:
node = 4552312
currLink = 878300
nodeALW[node]  = 0.623415709


node = 4552973
currLink = 878301
nodeALW[node]  = 0.620706320

-> node = 4552974; currLink = 4246450; nodeALW[node] = 0.620706320
->-> node = 4552975; currLink = 4246451; nodeALW[node] = 0.620706320

**Comment by jipclaassens** [comment]
tr.InitRootNode(startNode);
startNode = 4612637
startNode = 4552971
startNode = 4628680

	tr.InitChildNode(currNode, parentNode);
parentNode = 4612637
currNode = 4618076

parentNode = 4612637
currNode = 4628680

parentNode = 4628680
currNode = 4628898
currNode = 4647745

parentNode = 4647745
currNode = 4646986
currNode = 4647746
currNode = 4637075

parentNode = 4646986
currNode = 4646987

parentNode = 4628680
currNode = 4628681

....

**Comment by jipclaassens** [comment]
Kortste route van Org naar dest = 129 + 60 + 47 = 236 seconden
Dit is gelijk aan de uitkomst van W_OV_W impedance.

**Comment by MaartenHilferink** [comment]
od_LS calculation: 

NodeType node = nzc.Res2EndNode(j);    node = 4628680

LinkType currLink = dh.m_TraceBackDataPtr[node];  currLink = 47259

node = graph.linkF1Data[currLink]; node = 4612637


LinkType currLink = dh.m_TraceBackDataPtr[node];  currLink = UNDEFINED.

**Comment by MaartenHilferink** [comment]
ALW berekening:
starpoint
node = 4612637

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/0f317be5-3820-4188-a6e3-27f07623f715)
