### ISSUE TITLE
Aggregatie op aantal undefined van dat attribuut per groep

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#754]

**Comment by eoudejans** [comment]
Count(Not(IsDefined(x)), per_regio);

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/874fc650-ec06-43c1-99b6-b116760dbf0a)

->

![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/58d17410-e5a8-4403-91bb-4af13b028e44)
