### ISSUE TITLE
Request: add information if the error is from a property definition

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#755]
Here a path given in de IntegrityCheck property cannot be found. It would be informative if in the error message something could be mentioned that the error occurs in a property definition.

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/3821e53b-d90b-4993-a456-4b368cfdb98f)

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/233ca48f-4e3a-4518-a5e4-29c8dfd2909d)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/fd12fae0-220a-4c49-b9f5-308b3f51a508)
