### ISSUE TITLE
pages not found on geodms.nl

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#764]
According to search.google.com, that just bumped-up the number of indexed pages; there are now also an increased number of not-found urls. Can we fix and fix those in the github wiki ?

![image](https://github.com/user-attachments/assets/49c321da-da2e-43dc-bdf2-70af8d55ec45)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/637b9a40-b2a1-460c-a27e-51ee6582b139)
![image](https://github.com/user-attachments/assets/319e6730-c9f2-49f5-b594-79f3bda2b942)
![image](https://github.com/user-attachments/assets/d048154f-93b8-457c-9ac2-b19c63c4584b)
![image](https://github.com/user-attachments/assets/875dcfd1-2d09-466e-80d9-b88ea0a8fdbc)
![image](https://github.com/user-attachments/assets/fb8cdd53-a64d-4e47-bfa3-689c422b277a)
![image](https://github.com/user-attachments/assets/7191cc2b-0424-4c65-a6d4-c113e58d21d5)
![image](https://github.com/user-attachments/assets/42598fc9-a2b2-447a-a3a8-9319015d270f)
![image](https://github.com/user-attachments/assets/af7d8cae-425b-4a6c-9a32-8af0310406e8)
![image](https://github.com/user-attachments/assets/2d0bc039-2c21-43f1-9481-f806ad4672e8)
![image](https://github.com/user-attachments/assets/2d1a7637-cbe3-420d-8e3c-c35e48247e48)

**Comment by MaartenHilferink** [comment]
Note that this age exists: https://github.com/ObjectVision/GeoDMS/wiki/Values-unit
but not this page: https://geodms.nl/docs/Values-unit  nor https://geodms.nl/docs/Values_unit

**Comment by MaartenHilferink** [comment]
The Not found links are half of the grey graph bump. The other half is "Crawled - currently not indexed".
![image](https://github.com/user-attachments/assets/ee5c7cd2-2746-423a-85fc-a304b76d22ab)

Examples seem generic normal pages; maybe a bit short and lacking specific keywords.

**Comment by eoudejans** [comment]
Internal wiki link for page:
https://github.com/ObjectVision/GeoDMS/wiki/Older-versions

Had some weird syntax, which will certainly not match to found pages ("wikilink"):
![image](https://github.com/user-attachments/assets/ae0030b7-df97-4fac-9f13-79d2401ecf9c)

Furthermore, at the moment only Mediawiki type links are properly converted to the right link, whereas the other variant can be added to the supported set that properly converts using this syntax: [Link Text](full-URL-of-wiki-page)

See:
https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-links

Fixed the potential link:
![image](https://github.com/user-attachments/assets/d450d4ab-0a92-47e7-b84d-651331a5fa29)

**Comment by eoudejans** [comment]
Cleaned up links that need attention:
- XY Order: still up to date?
- Kaartlinks zoals http://maps.objectvision.nl/martin/?layers=OPENBASISKAART,MARGRATEN_GLOOING_WEGSEGMENT_50CM,&zoom=12&lat=313340.1&lon=179191.76&language=nl in https://github.com/ObjectVision/GeoDMS/wiki/AHN
- https://github.com/ObjectVision/GeoDMS/wiki/Delete-CalcCaches-that-are-not-recently-used

**Comment by eoudejans** [comment]
It turns out "wikilink" is put in markdown links throughout the wiki codebase. Apart from currently not supporting the internal markdown link syntax: [link text](link), but only the mediawiki syntax: [[link text|link]]

![image](https://github.com/user-attachments/assets/fc0b5b54-9fc0-4ecb-a697-441015c59d90)

Changing these links to mediawiki syntax will most likely resolve this issue.

**Comment by eoudejans** [comment]
@MaartenHilferink I have fixed many incorrect links originating from translation of mediawiki to github wiki, details can be seen by cloning the [wiki repository](https://github.com/ObjectVision/GeoDMS.wiki.git):
![image](https://github.com/user-attachments/assets/7e3fb2b2-d70a-4956-856c-e2b185611180)

**Comment by MaartenHilferink** [comment]
Another complaint:

![image](https://github.com/user-attachments/assets/a5b9bcd0-41c1-4b3f-aa42-d806f9a5e7d0)
![image](https://github.com/user-attachments/assets/6e393235-ffca-41d0-9e22-e0e876475151)
https://geodms.nl/rtrim.html
https://github.com/ObjectVision/GeoDMS/wiki/Rtrim
