### ISSUE TITLE
Tests for geometry operator correctness and performance

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#775]
![image](https://github.com/user-attachments/assets/9b9f009f-c17a-4110-b08a-6fc29fd26eb0)

**Comment by jipclaassens** [comment]
bg_split_union_polygon()

![image](https://github.com/user-attachments/assets/6ea7c876-1bba-4957-bd1c-60c1213ad5b4)

**Comment by jipclaassens** [comment]
En waar zijn deze 4 lakes ?

![image](https://github.com/user-attachments/assets/b57a4b99-a4a2-437b-b379-b4d4359a38b1)

**Comment by jipclaassens** [comment]
Met bp_union_polygon()

![image](https://github.com/user-attachments/assets/6d14e7c0-8f2a-42d7-8e14-91d6b898bf5f)

**Comment by jipclaassens** [comment]
LargeSetWithSmallPolygons == 2455 gesloopte panden in Amsterdam, dus vaak niet aangrenzend
SmallSetWithLargePolygons == 345 gemeente (y2022), dus meestal aangrenzend.

----

###LargeSetWithSmallPolygons 

- bg_inflate_ratio_correctness = 1
- bg_deflate_ratio_correctness = 1
- bg_split_count_islands = 2455
- bp_split_count_islands = 2455
- bg_split_union_count_islands = 785
- bp_split_union_count_islands = 785
- bg_split_union_area_islands = 244009 ha
- bp_split_union_area_islands = 244008 ha

###SmallSetWithLargePolygons 

- bg_inflate_ratio_correctness = 1
- bg_deflate_ratio_correctness = 1
- bg_split_count_islands = 705
- bp_split_count_islands = 705
- bg_split_union_count_islands = 290
- bp_split_union_count_islands = 200
- bg_split_union_area_islands = 33005.8 km2
- bp_split_union_area_islands = 35137.4 km2

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/a58629f4-0f08-470d-a724-a146777d13c8)

**Comment by basvanbemmel** [comment]
Gaat dit nu om een nieuwe operator of om de (niet juiste) werking van een bestaande operator (operator correctness and performance?).

**Comment by jipclaassens** [comment]
> Gaat dit nu om een nieuwe operator of om de (niet juiste) werking van een bestaande operator (operator correctness and performance?).

@basvanbemmel beide. De cgal_ en cmos_ varianten zijn nieuw. Daarnaast een aantal bg_nieuwe operatoren en hernoeming van de bp_ varianten. Daarnaast blijkt op dit moment de bg_union operatoren niet helemaal juist te zijn. 

Oftewel, cgal/cmos/bg is allemaal experimenteel.

de bp_ (oftewel de oude polygoon operatoren) zijn nog steeds juist. Maarten heeft de naamgeving veranderd en de performance verbeterd

**Comment by MaartenHilferink** [comment]
Results for the 4 overlay_polygon functions:
![image](https://github.com/user-attachments/assets/80045797-97db-4963-bf1b-c5b59b9b9729)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/02892392-2f36-4e22-856e-1d43ae688b86)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/6fe214f3-eba4-49a7-b280-df6048e133bd)

**Comment by MaartenHilferink** [comment]
Issue met bg_inflate in Amsterdamse Zeeburg-meren

![image](https://github.com/user-attachments/assets/15898370-e703-4571-9f9a-4c432255da0f)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/faa85487-f837-414e-83e7-d9396cd90f17)

**Comment by MaartenHilferink** [comment]
Results voor alle gemeentes:
![image](https://github.com/user-attachments/assets/873f5372-a8f2-4551-8dad-70509fc00039)

**Comment by MaartenHilferink** [comment]
Resultaat met DPoint i.p.v. FPoint:
![image](https://github.com/user-attachments/assets/3913c8b5-487d-40ac-b2c5-24e8dccbacbb)

**Comment by MaartenHilferink** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MAARTE~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MAARTE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


functie | resultaat
-- | --
avg_overlay_count_islands | 43009
bg_overlay_count_islands | 43010
bp_overlay_count_islands | 43007
cgal_overlay_count_islands | 43010
geos_overlay_count_islands | 43011
bg_inflate_and_deflate_ratio_correctness | '345...345 of 345'
avg_connectivity_count_islands | 2
bg_connectivity_count_islands | 2
bp_connectivity_count_islands | 2
cgal_connectivity_count_islands | 2
geos_connectivity_count_islands | 2
avg_polygon_count_islands | 345
bg_polygon_count_islands | 345
bp_polygon_count_islands | 345
cgal_polygon_count_islands | 345
geos_polygon_count_islands | 345
avg_polygon_area | 3,53E+18
bg_polygon_area | 3,53E+18
bp_polygon_area | 3,53E+18
cgal_polygon_area | 3,53E+18
geos_polygon_area | 3,53E+18
avg_union_area | 3,51E+18
bg_union_area | 3,51E+18
bp_union_area | 3,51E+18
cgal_union_area | 3,51E+18
geos_union_area | 3,51E+17
avg_split_count_islands | 706
bg_split_count_islands | 706
bp_split_count_islands | 706
cgal_split_count_islands | 706
geos_split_count_islands | 706
avg_split_area | 3,53E+18
bg_split_area | 3,53E+18
bp_split_area | 3,53E+18
cgal_split_area | 3,53E+18
geos_split_area | 3,53E+18
avg_split_union_count_islands | 200
bg_split_union_count_islands | 200
bp_split_union_count_islands | 200
cgal_split_union_count_islands | 200
geos_split_union_count_islands | 200
avg_split_union_area | 3,51E+18
bg_split_union_area | 3,51E+18
bp_split_union_area | 3,51E+18
cgal_split_union_area | 3,51E+18
geos_split_union_area | 3,51E+18



</body>

</html>

**Comment by MaartenHilferink** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MAARTE~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MAARTE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


  |  
-- | --
functie | resultaat
avg_overlay_count_islands | 134808
bg_overlay_count_islands | 135339
bp_overlay_count_islands | 135338
cgal_overlay_count_islands | 135339
geos_overlay_count_islands | 133217
bg_inflate_and_deflate_ratio_correctness | '132041...132199 of 132199'
avg_connectivity_count_islands | 4292
bg_connectivity_count_islands | 4292
bp_connectivity_count_islands | 4294
cgal_connectivity_count_islands | 4292
geos_connectivity_count_islands | 4292
avg_polygon_count_islands | 132199
bg_polygon_count_islands | 132199
bp_polygon_count_islands | 132199
cgal_polygon_count_islands | 132199
geos_polygon_count_islands | 132199
avg_polygon_area | 1,32E+08
bg_polygon_area | 1,32E+08
bp_polygon_area | 1,32E+08
cgal_polygon_area | 1,32E+08
geos_polygon_area | 1,32E+08
avg_union_area | 11711261.6
bg_union_area | 11704527.9
bp_union_area | 11713424.9
cgal_union_area | 11713546.9
geos_union_area | 11713546.9
avg_split_count_islands | 132192
bg_split_count_islands | 132192
bp_split_count_islands | 132192
cgal_split_count_islands | 132192
geos_split_count_islands | 132192
avg_split_area | 1,32E+08
bg_split_area | 1,32E+08
bp_split_area | 1,32E+08
cgal_split_area | 1,32E+08
geos_split_area | 1,32E+08
avg_split_union_count_islands | 4293
bg_split_union_count_islands | 4293
bp_split_union_count_islands | 4293
cgal_split_union_count_islands | 4293
geos_split_union_count_islands | 4293
avg_split_union_area | 26364639.2
bg_split_union_area | 26364376.1
bp_split_union_area | 26364667.9
cgal_split_union_area | 26364756.5
geos_split_union_area | 26364756.5



</body>

</html>

**Comment by jipclaassens** [comment]
From Visual study, 15.8.0

Geos calc times:

/Tests/Results/LargeSetWithSmallPolygons/geos_union_area
35 sec

Quit and restart

/Tests/Results/LargeSetWithSmallPolygons/bp_union_area
12 sec

**Comment by jipclaassens** [comment]
Middels bp_union_polygon, maar met 'nieuwe' difference operator:

`/BRT/Read_Relevant_Tiles_x_WegSpoor_src_bp`

area of TiledNonWegSpoor = 32,187.847664241035

**Comment by jipclaassens** [comment]
v17.2.5 (niet vanuit debugger)

Middels bp_union_polygon, en dus met 'oude' difference operator:

/BRT/Read_Relevant_Tiles_x_WegSpoor_src_bp
area of TiledNonWegSpoor = 33,165.9149, #34433 in =1.16min

**Comment by jipclaassens** [comment]
Hij lijkt alsof alle meren wegvallen in bg. Maar bij nader inzien is het niet altijd zo.

![Image](https://github.com/user-attachments/assets/c9ee273d-8fbc-4253-b50c-c43426b1c2e2)

**Comment by jipclaassens** [comment]
bp v17.2.5 tov bg v17.3.0
bp heeft vrijwel alles er wel in zitten. 

![Image](https://github.com/user-attachments/assets/36e453d7-8818-47de-8ff7-a463c18a9c40)

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/user-attachments/assets/9616649f-2e3a-44ef-bb70-8f4a4a908fb3)
