### ISSUE TITLE
WGS84 penwidth te dik

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#78]
Wanneer je WGS84 arcs wilt visualiseren worden alle lijnen zeer dik.
Een work-around is om een PenWorldWidth in te stellen op:

attribute<WGS84> Geometry (arc)
{
	parameter<float64> PenWorldWidth := 0.0001d    , DialogType = "PenWorldWidth";
}

OVSRV6:
C:\ProjDir\Jip\geodms_africa_cusa2_issueGH78\trunk\cfg\Africa.dms

/SourceData/Roads/OSM/Algeria/inFile/Geometry

**Comment by MaartenHilferink** [comment]
How could a good PenWorldWidth be derived? Via EPGS -> 1m as default and 1 if nog EPSG is known ?

**Comment by MaartenHilferink** [comment]
Finally:

![image](https://user-images.githubusercontent.com/2284361/213513771-6c069dcf-e99d-41af-9bcc-e053f1831358.png)

Now, for each geometric attribute who's related baseProjection, gdal layer or datastore has a SpatialReference with units larger than 1 meter, the baseProjection's ViewPortMinSize will be set to (10 / size of unit in meters) and the geometry's PenWorldWidth will be set to 1 / unitsize in meters, such that zooming in stops at a ROI of less than 10 meter wide or tall and PenWorldWidth corresponds by default with 1meter.
