### ISSUE TITLE
collect_attr_by_cond does not generate subitems in this case

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#782]
OVSRV09:
`C:\ProjDir_Jip\_Issues\RSopen_issue782\cfg\main.dms`

`/SourceData/Vastgoed/BAG/PerJaar/Y2022/pand/met_vbo/Counts/vbos_inPand_per_vbo_functie`

![image](https://github.com/user-attachments/assets/b232ee7f-dd26-40f4-8556-a7bfa3682340)

**Comment by jipclaassens** [comment]
The selection_condition specified is the one from the select_with_att and thus wrong.

I've added this scenario to the operator test

`/Relational/UnTiled2UnTiled/results/Tests`

**Comment by MaartenHilferink** [comment]
unable to reproduce

![image](https://github.com/user-attachments/assets/7a645b2d-ddc6-4d73-a2a5-ed058501270c)

**Comment by jipclaassens** [comment]
This test commit was probably undone in some merge. I've committed it to the GeoDMS-test_Jip branch:


/Relational/UnTiled2UnTiled/collect_attr_by_cond_Jip/test_wrongCondition

**Comment by jipclaassens** [comment]
De sub attributen hebben DomainUnit = "/SourceData/Vastgoed/BAG/PerJaar/Y2022/pand"

sourceDomain = 0x0000027d4c5d2a60 "/SourceData/Vastgoed/BAG/PerJaar/Y2022/pand/met_vbo"

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/6e91a919-1cd8-4484-839f-e467dede8696)
