### ISSUE TITLE
Debug cast failure

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#783]
![image](https://github.com/user-attachments/assets/9b3e03ac-9ad2-4dbf-86f8-a298aebc2f8c)

Door activatie van:

`/Allocatie/Zichtjaren/Y2050/Impl/Generate`

Fout komt door container := string attr

```
container LastSequence := ='last(Sequence_later/Name)'
{
	container StateNaAllocatie := =last(Sequence_later/name)+'/StateNaAllocatie'; 
}
```

**Comment by MaartenHilferink** [comment]
Zo dan ?
![image](https://github.com/user-attachments/assets/75cc5f5a-5f2d-4de5-bec0-81b230c04ebb)

**Comment by mtbeek32** [comment]
After this commit, 2UP and Hestia in the full test now result in errors:

ItemType TreeItem is incompatible with the result of the calculation which is of type Unit ..

e.g., 

![image](https://github.com/user-attachments/assets/10365e88-0530-427b-bf7f-fa14d93055c6)
