### ISSUE TITLE
Dynamic definition of valuesunit

### ISSUE THREAD

**Issue by poorthuis-w** [ObjectVision/GeoDMS#784]
For storing a large number of variables in a csv, it would be useful to be able to define a set of parameters in a for_each_ind or similar.

In the example below is the current state I came up with, where the result is a container with the two parameters with string valuesunits. To be able to set de valuesunits provided in the .csv would save explicitly writing a line for every (non-string) variable.

As an extra difficulty, variables might have different valuesunits within the same .csv, as in the example.

[minimal_workingexample_dynamic_valuesunits.csv](https://github.com/user-attachments/files/16561844/minimal_workingexample_dynamic_valuesunits.csv)

	unit<uint32> src: StorageName = "minimal_workingexample_dynamic_valuesunits.csv", StorageType = "gdal.vect", StorageReadOnly = "True";

	container cities := for_each_ind(
	'nedv'
	,src/naam_variabele
	,'rjoin("'+src/naam_variabele+'",src/naam_variabele, src/waarde)'
	,void
	,string
	);

**Comment by jipclaassens** [comment]
Would this solve your problem? Here I defined a list with variables (StandVar), in that unit is also an attribute called unit_name which has for each element the values unit, e.g. Ha, meter2, MW. 

```
container ReadStand :=
	for_each_ndvna(
		 Standvar/path
		, AdminDomain
		, StandVar
		, StandVar/unit_name
		, '%LocalDataDir%/RSopen/Allocatie/'+Casus_name +'/Stand'+name+'/'+Standvar/path+'.tif'
	), StorageReadOnly = "True";
```

**Comment by poorthuis-w** [comment]
This works with some modifications. Thanks.
