### ISSUE TITLE
Zoomniveau in WGS84 onvoldoende

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#79]
Wanneer je iets in WGS84 wilt visualiseren, bijvoorbeeld een wegnetwerk uit OSM, dan kun je niet verder inzoomen dan het hele land. Van bijvoorbeeld Algerije, zie hier:

OVSRV6:
C:\ProjDir\Jip\geodms_africa_cusa2_issueGH79\trunk\cfg\Africa.dms
/SourceData/Roads/OSM/Algeria/inFile/Geometry

**Comment by MaartenHilferink** [comment]
See also #78. A maximum scale schould be specifyable for a base-projection, with as default 1m = 1pixel based on EPSG, or 1 = 1 pixel if no EPSG is present.

**Comment by MaartenHilferink** [comment]
See the last recent comment before closing of #79.
