### ISSUE TITLE
csv alleen laatste veld weggeschreven 

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#799]
Bij aanmaken van een csv wordt alleen het laatste veld weggeschreven, dfb werkt wel gewoon.
Ik meen dat dit wel eerder ter sprake is gekomen maar dacht eigenlijk dat het al opgelost was.
Eigenlijk wil ik van dat dbf-formaat af (binair)

GeoDMS 15.7.1
PD11177 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/TowardsAnUrbanPreview_2024_HYDE_csv_issue
SD 11020 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/2UP

item
/Scenarios/SSPs/SSP2/Export/Modelled/Builtupareakm2_5min_SUM_CSV
werkende dbf staat onder:
/Scenarios/SSPs/SSP2/Export/Modelled/Builtupareakm2_5min_SUM

	//werkt niet alleen laatste jaartal weggeschreven	
	container Builtupareakm2_5min_SUM_CSV := 
		for_each_nedvat(ProjectionDate/name,
			'sum(Builtupareakm2_5min/' + ProjectionDate/name + ')'
			, Void
			,km2
			,'%LocalDataProjDir%/results/'+GridName+'/'+InputMethod+Variant+InPresentUrban+'_'+Scenario+'_buakm2_5min_SUM.csv'
			, 'gdalwrite.vect'
		);
		
	container Builtupareakm2_5min_SUM := 
		for_each_nedva(ProjectionDate/name,
			'sum(Builtupareakm2_5min/' + ProjectionDate/name + ')'
			, Void
			,km2
			,'%LocalDataProjDir%/results/'+GridName+'/'+InputMethod+Variant+InPresentUrban+'_'+Scenario+'_buakm2_5min_SUM.dbf'
		);

![image](https://github.com/user-attachments/assets/17c6967a-e129-4c96-a94b-81898815090a)

**Comment by eoudejans** [comment]
Reproduceerbaar met:

```cpp
unit<uint32> data : nrofrows = 3
{
attribute<string> name : ["field_a","field_b","field_c"];
attribute<float32> content : [10.2,3.2,8.6];
}

container write_csv := 
for_each_nedvat(data/name,
'sum(data/content)'
, Void
, float32
,'%LocalDataProjDir%/test_issue_799.csv'
, 'gdalwrite.vect'
);
```

**Comment by eoudejans** [comment]
@basvanbemmel zo werkt het wel:

```cpp
container write_csv := 
for_each_nedv(
			data/name,
'sum(data/content)'
, Void
, float32
)
, StorageName = '%LocalDataProjDir%/test_issue_799.csv'
, StorageType = 'gdalwrite.vect'
, StorageReadOnly = 'False';
```

**Comment by eoudejans** [comment]
De storage dus over de gehele container definiëren, in plaats van per item, in dat laatste geval zal er voor elk item data worden weggeschreven en zal dus alleen het laatste item in de csv terecht komen.

**Comment by basvanbemmel** [comment]
werkt inderdaad:

	container Builtupareakm2_5min_SUM := 
		for_each_nedv(
			ProjectionDate/name
			, 'sum(Builtupareakm2_5min/' + ProjectionDate/name + ')'
			, Void
			, km2
			)
	, StorageName     = "='%LocalDataProjDir%/results/'+GridName+'/'+InputMethod+Variant+InPresentUrban+'_'+Scenario+'_buakm2_5min_SUM.csv'"
	, StorageType     = 'gdalwrite.vect'
	, StorageReadOnly = 'False';

Wel gek dat het bij dbf wegschrijven anders werkt, zal wel door gdal storage manger komen bij csv. Iets andere wijze van appenden of zo
