### ISSUE TITLE
coordinaat conversie geeft crash

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#80]
attribute<BaseProjection> Geometry_BP (arc) := Geometry[BaseProjection];

resulteert in crash

OVSRV6:
C:\ProjDir\Jip\geodms_africa_cusa2_issueGH80\trunk\cfg\Africa.dms

map view of table view op:
/SourceData/Roads/OSM/Algeria/inFile/geometry_bp

in 8.6.3

**Comment by MaartenHilferink** [comment]
Cannot Reproduce !
GDAL Error: cannot open dataset 
C:/ProjDir/Jip/geodms_africa_cusa2_issueGH80/trunk/data/src/landuse/copernicus_GLC_v2_0_1_discr_class_Africa_EPSG_102022_clipped.tif

**Comment by MaartenHilferink** [comment]
Internal exception: osgeo::proj::io::NoSuchAuthorityCodeException

**Comment by eoudejans** [comment]
Reproducibility of original crash on item /SourceData/Roads/OSM/Algeria/inFile/geometry_bp confirmed in 8.6.2 release.

**Comment by eoudejans** [comment]
EPSG:102022 did not occur in our proj.db file. The reason being that EPSG:102022 does not exist. This projection is defined by ESRI and thus to be read from another database. Geodms also ships the ESRI projection definitions via proj.db ESRI:102022 is for instance mentioned in crs_view layer when opened using qgis, layer crs_view.

**Comment by eoudejans** [comment]
This insight brings the geodms code back to a working state. However this does not resolve the crash, which is unwanted behavior. Proposed fix to be implemented: when defining a unit with format that has one of the crs authorities: EPSG, ESRI, IAU_2015, IGNF, NKG, OGC or PROJ -> then proj should be asked if it can find the projection in the proj.db. If yes, great, if not throw an error for the unit. This will also cause F2 to properly work, and will likely resolve the crash.

**Comment by MaartenHilferink** [comment]
Err msg now is: 
Cannot make a SpatialRefBlock from EPSG:102022. OGRCheck code 6: Failure
