### ISSUE TITLE
Table_Dump geeft verkeerde warning

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#802]
![image](https://github.com/user-attachments/assets/9f248d4e-672a-44aa-bf1c-84102738c8fd)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/83502166-a6d2-4e10-85f6-f4cbec9c9dad)

![image](https://github.com/user-attachments/assets/502f1932-ff1d-4201-912b-5b5545cdb7e5)
