### ISSUE TITLE
Hanging GUI since Qt 6.7.3

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#809]
GUI loops with this stack fixed:

![image](https://github.com/user-attachments/assets/1bc0ee2e-56c4-4814-a3c4-9f8de7563340)

And these sampled toppings:

Keywords: UIAutomationCode, GetPropertyValue 30010 (UIA_IsEnabledPropertyId), 

![image](https://github.com/user-attachments/assets/ffa03d39-072d-424c-8300-09a19e8c83a6)

![image](https://github.com/user-attachments/assets/35058d4e-b3fb-4d9d-8379-db43679a5472)

![image](https://github.com/user-attachments/assets/01d37c7c-923c-44a6-a459-5eaec2027ba6)

![image](https://github.com/user-attachments/assets/fad37ce0-6b50-4111-be46-ad131198532d)

![image](https://github.com/user-attachments/assets/da6a8b27-41e4-4a42-b013-02bfa1773eab)

![image](https://github.com/user-attachments/assets/cc3b3d0f-b15c-4d07-8cb7-fc05f737a7ba)

![image](https://github.com/user-attachments/assets/812f5d75-8c5b-4b9c-a9d6-559215a81e2c)

**Comment by jipclaassens** [comment]
possible linked to #591

**Comment by MaartenHilferink** [comment]
Kan dit ook worden waargenomen met Qt 6.8.0, vanaf 15.10.1 ?
