### ISSUE TITLE
rood item, terwijl de rode items ogenschijnlijk niet gebruikt worden

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#82]
table view op:
/Analysis/Ref_Abidjan_Ouagadougou/Indicators/TransportPerformance/Limit_90min_120kmEucl/TP_g

geeft na enkele seconden rode tabel met: Link_impedance: undefined values not allowed

Maar niet via F2 of detailpages te tracen naar probleem.

Door klikken naar: 
/Analysis/Ref_Abidjan_Ouagadougou/Network/Combine_OrgDest/Imp_Original
Laat zien dat de not-flood (=Original) impedence wel rood is. Mogelijk vindt GeoDMS het leuk dat dat item rood is, terwijl deze ogenschijnlijk niet gebruikt wordt.

ovsrv6:
C:\ProjDir\Jip\geodms_africa_cusa2_issueGH82\trunk\cfg\africa.dms
/Analysis/Ref_Abidjan_Ouagadougou/Indicators/TransportPerformance/Limit_90min_120kmEucl/TP_g

geodms 8.6.3

**Comment by MaartenHilferink** [comment]
Issue is caused by that supplying items, such as /Analysis/Ref_Abidjan_Ouagadougou/Indicators/TransportPerformance/Limit_90min_120kmEucl/TP_i
didn't fail with FR_Data yet. Only after requesting it, the FR_Data of the related Cache Item bubbles up.
