### ISSUE TITLE
Right Mouse button on LayerControl doesn't result in a context menu, in RVF.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#824]
![image](https://github.com/user-attachments/assets/a5ebb45e-d081-4bd9-9ba4-f4af4bf0ec2b)

Reproduce:
mapview of:
`/Indicatoren/Y2050/ClaimRealisatie/Per_AllocRegio/Provincie/Claim_realisatie/Verblijfsrecreatie/Verblijfsrecreatie`

then right-mouse on layer

Direct cause: too many menu-sub-items as a result of many classification candidates for this layer

**Comment by MaartenHilferink** [comment]
These fixes will be available in v16.0.0
