### ISSUE TITLE
Access violoation 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#829]
OVSRV6:
C:\ProjDir\Jip\_Github_issues\2BURP_issue829\cfg\main.dms
mapview of:
/Geography/CompactedDomain/org_rel

![image](https://github.com/user-attachments/assets/d9eadffd-74f6-46c0-a26d-c88c0013ff6c)

**Comment by jipclaassens** [comment]
@MaartenHilferink blocking mollweide impl van 2BURP

**Comment by jipclaassens** [comment]
Two issues:
- (easy) why was stripBuffer allocation size truncated?
- (moderate) why a strip size of 110 759 995? What was the tile size? Avoid reading stuff outside study areas and make a square tiling effective and not striping as the data probably (observedly!) is tiles are 128*128.
![image](https://github.com/user-attachments/assets/fd25b531-7389-49fe-9965-d3c1b9d2dcf3)

**Comment by MaartenHilferink** [comment]
@jipclaassens What is the resolution and tiling of IceSnowPhysical layer / domain  ? It seems that it has very large raster cells, covering about 120.000 x the (compacted) domain grid cell size.

**Comment by jipclaassens** [comment]
D:/SourceData/2BURP/physical/SnowIceCover/Modis2001_SnowIce_unint2_2_54009.tif

**Comment by jipclaassens** [comment]
SnowIce raster size zijn 1 / 120 meter ? Dan dus inderdaad 120.000 per domain_grid, want dat zijn 1000x1000 meter rasters in Mollweide.

![image](https://github.com/user-attachments/assets/5036580a-f2c2-4959-ab32-d2561fb27699)

**Comment by jipclaassens** [comment]
Sub-issue 2 is caused by referring to the lat-long tiff and corresponding .twf. GeoDms (when DialogData="Mollweide") has no reasons not to interpret the data as a 1/120 m Mollweide raster data.

![image](https://github.com/user-attachments/assets/254e036a-cdeb-4d57-b6c4-3cd24e521901)

**Comment by jipclaassens** [comment]
Implemented:

![image](https://github.com/user-attachments/assets/d8ef17c2-f9d1-4506-8ce2-19ec696d3c26)
