### ISSUE TITLE
Read uint32 tif as float32, -1 is interpreted as 4.29e+09

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#832]
And add a warning when converting between value types

**Comment by MaartenHilferink** [comment]
Warning is added. Auto conversion makes it impossible to dissect 0xFFFFFFFF and 0xFFFFFFFE.

![image](https://github.com/user-attachments/assets/9fc55d8d-6e06-4652-bdab-9405505e09d5)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/5a6dc9cb-a9da-4a39-8105-e6a291a99488)
