### ISSUE TITLE
Statistics for irregular tiled domain aanpassen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#833]
`const(1, tiledDomain) `

![image](https://github.com/user-attachments/assets/f28ef758-9bd9-4d84-8973-e53b4155bb1d)

Suggestion:
- #Nulls in tiled domain
- #values 
- #tiles 70 (container zoveel cellen)
- what if tiles overlappen?

**Comment by MaartenHilferink** [comment]
![image](https://github.com/user-attachments/assets/8b290057-ceea-4e25-a825-a1c40440bc5b)
