### ISSUE TITLE
Failure: Error: value(s) of operator exp have metric s but are expected to be without metric 16.0.1

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#837]
Ik krijg de melding:
Failure: Error: value(s) of operator exp have metric s but are expected to be without metric
in 16.0.1 (en niet in 15.10.2)

Het heeft te maken met:
https://github.com/ObjectVision/GeoDMS/releases/tag/v16.0.0
exp and log now trigger a diagnostic error when its argument have a non-unitary metric. Arguments must be dimensionless.

![image](https://github.com/user-attachments/assets/13eec473-6dde-452a-a021-b2c5d9a6f860)

![image](https://github.com/user-attachments/assets/cfbe0510-5836-49c7-8edc-0557c947d24a)

**Comment by basvanbemmel** [comment]
geldt vermoedelijk ook voor RSOpen (werkt dus niet meer in 16.0.1) na bekijken van de code

**Comment by jipclaassens** [comment]
Klopt, hier wordt vanaf een paar versies terug een warning op gegeven en sinds 16 geeft dit echt een error.

Ik had dit in RSo al verholpen, en nu ook in WLO. Even updaten dus.
