### ISSUE TITLE
verschil in uitkomst /Analysis/Allocatie/StartState_metBAGnieuwbouw/Subsector_rel tussen Azure geodms-p0 en geodms-d

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#838]
GeoDMS 15.10.2
PD: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/WLO2024    rev11310
SD: https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL  rev11303
BaseData, VariantData en Allocatie uitgerekend met RunAll.cmd

item: /Analysis/Allocatie/StartState_metBAGnieuwbouw/Subsector_rel
/BaseData/BAG_nieuwbouw/Result/Read_UNCHECKED/Werken/Overheid_kw_diensten 
/Analysis/Allocatie/StartState_metBAGnieuwbouw/CompactedBBB/Werken/Overheid_kw_diensten

Er is een verschil te zien tussen bijvoorbeeld WLO_hoog_BAU/Zichtjaren/Y2030/Sector_rel_Verstedelijking

Zwart beide computers verstedelijking in 2030, groen niet verstedelijkt op geodms-d tov p0, rood verstedelijkt op geodms-d maar niet op geodms-p0
![image](https://github.com/user-attachments/assets/2d6bff76-1897-4acb-82d9-0d2879d7f226)

screendump in gesprek linkerscherm de geodms-d
![image](https://github.com/user-attachments/assets/7db904c0-8b4e-452e-aba1-df0838577a33)

screendump in gesprek rechterscherm de p-0
![image](https://github.com/user-attachments/assets/774f06a3-dbab-4d82-a276-256b9caeeaf2)

De aangemaakte tifs in LD (PD en SD zijn dus hetzelfde)
[Overheid_kw_diensten.zip](https://github.com/user-attachments/files/17869580/Overheid_kw_diensten.zip)

Het writen van de bestanden gebeurd in:
BaseData/BAG_nieuwbouw/Result/Write/Werken/Overheid_kw_diensten

in ArcGIS zien bestanden hetzelfde uit, bestandsgrootte is wel anders:
![image](https://github.com/user-attachments/assets/0d76dc72-3c7d-4226-af65-bbfb4328a3d0)

BAG_nieuwbouw.dms
		container Write := 
			for_each_nedvna(
				Classifications/StandVar_Prep/path
				, 'BAG_nieuwbouw/'+Classifications/StandVar_Prep/Path
				, AdminDomain
				, Classifications/StandVar_Prep
				, Classifications/StandVar_Prep/unit_name
				, '%LocalDataProjDir%/BaseData/BAG_Nieuwbouw/'+Classifications/StandVar_Prep/Path+'.tif'
			)//, using = "CaseClassifications/Vastgoed/OP"
		{
			parameter<string> Generate := 'Ready', ExplicitSuppliers = "=AsList(Classifications/Standvar_Prep/path, ';')";
		}

specs p0: 
Windows Server 2019 Datacenter
AMD EPYC 7763 64-Core Processor 2.44 GHz
256GB
64 bits

specs d: 
Windows Server 2019 Datacenter
AMD EPYC 7763 64-Core Processor 2.44 GHz
512 GB
64 bits

debug code in ..\WLO2024\cfg\main\Analysis\Allocatie,dms (vanaf regel 20)

debug code in ..\WLO2024\cfg\main\Analysis\Allocatie,dms (vanaf regel 20)

		container NotZero :=  for_each_nedv(Sector/XSubsector/name,
			'value(BaseData/BAG_nieuwbouw/Result/read/'+Sector/XSubsector/name+',float32) != 0f',
			AdminDomain, bool
		);
		container CompactedBBB :=  for_each_nedv(Sector/XSubsector/name,
			'NotZero/'+Sector/XSubsector/name+' ? value(BaseData/BAG_nieuwbouw/Result/read/'+Sector/XSubsector/name+',float32) : 0f/0f',
			AdminDomain, float32
		);
		container CompactedXXX :=  for_each_nedv(Sector/XSubsector/name,
			'collect_by_cond(CompactedAdminDomain, AdminDomain/IsCompactedDomain, CompactedBBB/'+Sector/XSubsector/name+')',
			CompactedAdminDomain, float32
		);
			
		attribute<Sector/XSubsector> Subsector_rel (CompactedAdminDomain) := ='argmax_ifdefined('+AsList('CompactedXXX/'+Sector/XSubsector/name, ',')+')';

org:

attribute<Sector/XSubsector> Subsector_rel (CompactedAdminDomain) :=
			 =	'argmax_ifdefined(
					 '+AsList('collect_by_cond(CompactedAdminDomain, AdminDomain/IsCompactedDomain, value(BaseData/BAG_nieuwbouw/Result/read/'+Sector/XSubsector/name+',float32) != 0f ? value(BaseData/BAG_nieuwbouw/Result/read/'+Sector/XSubsector/name+',float32) : 0f/0f)', ',')+'
				)';

**Comment by basvanbemmel** [comment]
geodms-d:
![image](https://github.com/user-attachments/assets/91639789-1143-42b9-90cb-6e93483dc751)

geodms-p0
![image](https://github.com/user-attachments/assets/954b6a77-31b1-4b81-8bba-6c0edde45d62)

**Comment by MaartenHilferink** [comment]
Ik zal met Jip naar de generatie van deze TIFS kijken. De 1.45E-41 waarde blijft heel verdacht.

**Comment by basvanbemmel** [comment]
In GUI runnen van BaseData/BAG_nieuwbouw/Result/Write/Werken/Overheid_kw_diensten op de geodms-p0  geeft wel hetzelfde bestand als op de geodms-d, zei screendump. Probleem moet dan in de batch zitten?

![image](https://github.com/user-attachments/assets/bd320b2f-e748-450e-9d51-2d9c08fdcf90)

**Comment by MaartenHilferink** [comment]
Of in het (niet) opschonen van eerdere resultaten. Welke batch file had je gestart ?

**Comment by basvanbemmel** [comment]
RunAll.cmd

maar ik zie nu iets vreemds op /BaseData/BAG_nieuwbouw/Result/read/Werken/Overheid_kw_diensten
geodms-p0:
![image](https://github.com/user-attachments/assets/3d4e6b38-fffb-4367-972f-5d1ac976b045)
![image](https://github.com/user-attachments/assets/1d4dc31d-5173-45b8-87db-b2164ffcab39)

geodms-d
![image](https://github.com/user-attachments/assets/c4530963-c724-4962-9d4e-6d85d8135444)
![image](https://github.com/user-attachments/assets/faf84a27-290d-4435-a10b-629cf8079723)

**Comment by basvanbemmel** [comment]
RunAll.cmd er lijkt dus een verschil tussen beide computers bij het draaien van de batch wat zich niet uit in de GUI als je daat het items uitrekent.
dus test is:
reken in GUI uit:
/BaseData/BAG_nieuwbouw/Result/Write/Werken/Overheid_kw_diensten
reken in batch uit:
RunAll.bat dan gaat het eigenlijk om
/MaakBasedata/Generate_Run1

op de p0 zie ik dan dus een verschil in de bestanden wat niet het geval is op de geodms-d

**Comment by MaartenHilferink** [comment]
Jip heeft net een wellicht vergelijkbare situatie gezien, waarin schrijven via native tiff (dus niet gdalwrite.grid) steeds volgende pagina's schrijft en bij inlezen steeds de 1e pagina gelezen wordt. Wellicht was voor het runnen op de gemankeerde machine niet alle tussenresultaten weggegooid en daar door TIF groter geworden in plaats van overschreven.

**Comment by MaartenHilferink** [comment]
Had je voorafgaande aan vanuit GUI schrijven eerst de file weggegooid in explorer/commander ? Wellicht moeten we dat voortaan ook in batch files beter opnemen. Dit hangt mede samen met niet meer naar .tmp schrijven van wijzigingen, zie #582, #820

**Comment by basvanbemmel** [comment]
Het is allemaal uitgevoerd op gehele lege LD's voor de betreffende cfg in 15.10.2. SD en PD ook dezelfde versie. Ik heb het ook nog op de geodms-p2 getest (machine conform p0). Het probleem lijkt dus te focussen op verschil in het bestand Overheid_kw_diensten.tif in ..\LD\wlo2024\BaseData_GUI\BAG_Nieuwbouw\Werken

Alleen dit bestand is afwijkend of je het in de GUI berekend of in de batch
GUI activeren item: /MaakBasedata/Generate_Run1 (het probleemitem is dus eigenlijk /BaseData/BAG_nieuwbouw/Result/Write/Werken/Overheid_kw_diensten die in Generate_Run1 wordt aangeroepen )

Batch: RunAll.cmd

links GUI resultaat, rechts batch-resultaat in totalcommander

![image](https://github.com/user-attachments/assets/b5e2104a-3c2f-43b0-9851-84fb1b25f661)

Ik denk niet dat het met de tmp-bestanden te maken heeft eigenlijk. Toch meer iets van afronding van 0 waarden die niet exact hetzelfde gaat voor de GUI en de batch specifiek voor dit item/bestand en op deze computers

Als je een verschilgrid maakt (door de 2 bestanden weer in te lezen) van de 2 bestanden krijg je

		attribute<float32> Overheid_kw_diensten (AdminDomain)
		:	StorageName     = "K:/20241122/Overheid_kw_diensten.tif"
		,	StorageType     = "gdal.grid"
		,	StorageReadOnly = "True";

		attribute<float32> Overheid_kw_diensten_GUI (AdminDomain)
		:	StorageName     = "K:/20241122/Overheid_kw_diensten_GUI.tif"
		,	StorageType     = "gdal.grid"
		,	StorageReadOnly = "True";

		attribute<float32> verschil (AdminDomain):=Overheid_kw_diensten - Overheid_kw_diensten_GUI;

![image](https://github.com/user-attachments/assets/62b0d583-3a81-4cd5-b0f5-c0a2ca14a299)
![image](https://github.com/user-attachments/assets/592ca279-2656-4b82-a30a-d8a3425840a3)

**Comment by basvanbemmel** [comment]
Ook op mijn lokale laptop verschil

![image](https://github.com/user-attachments/assets/7ab6761e-7c07-41a6-bd43-86aae612bc41)

**Comment by basvanbemmel** [comment]
En hebben jullie hier al naar kunnen kijken?

**Comment by basvanbemmel** [comment]
ok succes ermee. mocht je hulp nodig hebben dan hoor ik het graag

**Comment by MaartenHilferink** [comment]
1e reproductiepoging:

Met GUI en RunAll.bat geproduceerde files op OVSRV08 zijn wel even groot:

![image](https://github.com/user-attachments/assets/81ac45bf-805a-410b-877e-e5fa003558d9)

**Comment by MaartenHilferink** [comment]
Met GUI geproduceerde file, nadat deze al met RunAll.bat geproduceerd was:
![image](https://github.com/user-attachments/assets/84a9e7cb-47e0-469e-96e2-69a0c3901325)

**Comment by basvanbemmel** [comment]
nog voor de duidelijkheid ik had dus 3 systemen waarbij het resultaat verschillend was tussen GUI aanmaak en batch aanmaak:
- mijn desktop computer
- mijn laptop
-Azure p0
Ik rename nadat ik gerund heb de gehele map (lokale cfg map)
Opvallend is dat het bestand Overheid_kw_diensten.tif op de verschillende systemen ook nog eens niet dezelfde bestandsgrootte hebben.

Allleen de geodms-d liet dus hetzelfde resultaat zien tussen GUI en batch

Je tweede opmerking lijkt erop dat de stream niet goed afgesloten wordt immers bestandsgroote is exact tweemaal zo groot. Dat lijkt wellicht weer een ander probleem?

**Comment by MaartenHilferink** [comment]
Ik heb nu met 3 versies van de TIF getest op OVSVR08: met GUI gemaak, met batch gemaakt, met batch en daarna met GUI gemaakt. Alledrie geven dit resultaat:

![image](https://github.com/user-attachments/assets/a023100b-e1db-4208-8957-30e276d47447)

**Comment by MaartenHilferink** [comment]
Het herhaald schrijven (zonder tussentijds file weg te halen) resulterend tot 2x de bestandsgrootte is inderdaad waarschijnlijk een ander issue, gerelateerd aan het niet meer naar een .tmp schrijven.

**Comment by basvanbemmel** [comment]
Wat bedoel je eigenlijk met "3 versies van de TIF", is het niet veel interessanter om het ook op een geheel ander systeem te proberen (lokale laptop bijvoorbeeld). Dat is wel te runnen overigens (aanmaak zit helemaal aan de voorkant van de batch)

**Comment by MaartenHilferink** [comment]
Het lukt mij hier niet om zo'n 4MB tif te maken. Kun je me er 1 mailen ? Dan ga ik het eens binair en met GeoDMS / q-gis vergelijken. Ik neem aan dat de 3.5 MB versies van de $MB versies verschillen in dat de 4MB die kleine waarden bevatten die in de 3.5 MB versies 0 zijn, maar wil beter kijken naar welke kleine waarden. M.b.t. de overige verschillen in file-sizes acht ik de volgende suggesties waarschijnlijk:
![image](https://github.com/user-attachments/assets/f0306128-ebc7-4984-98b6-e6f5504bc7b3)
![image](https://github.com/user-attachments/assets/0b5fe0ef-d58f-4e43-aecb-d82493274b9d)
![image](https://github.com/user-attachments/assets/5d1a9b27-f4c8-426c-9099-e8f18b8990b1)
![image](https://github.com/user-attachments/assets/927545b4-33e7-46a1-ba46-a6640b339bbc)

**Comment by basvanbemmel** [comment]
ik check eerst wat oplossing #841 oplevert

**Comment by basvanbemmel** [comment]
in 16.0.2 opgelost op computer geodms-p0

Links in batch berekend, rechts in GUI berekend
![image](https://github.com/user-attachments/assets/53b5e7f6-e516-46c7-bbbe-e07ebd448a0d)
