### ISSUE TITLE
DetailPage: Explicit suppliers dropdown box

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#84]

**Comment by MaartenHilferink** [comment]
And let all detail-page text in table or line be somehow visible, by work wrapping or hoover-tooltip or horizontal scroll.
More specifically: FailReason should be word wrapped to easily read the full text.

**Comment by MaartenHilferink** [comment]
Now (v15 with WebEngine) we can use summary and details elementss.

**Comment by MaartenHilferink** [comment]
Example (in v15): 
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/56930f6d-ec97-45c4-9ef3-1040e3df3603)
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/63e8e487-fec3-4a45-8d69-ca6600b6fc23)

**Comment by MaartenHilferink** [comment]
Inmplemented in v15:
![image](https://github.com/ObjectVision/GeoDMS/assets/2284361/108968e9-ff33-4d24-ba6b-dbd37eb221ef)
