### ISSUE TITLE
Too many rows in Irregular tiled domain in table view (and sorting does not work as intented)

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#840]
86 miljoen in totale domain, maar slecht 37 miljoen inside tiles. Maar table view geeft alle 86 miljoen. 
Als je sorteert zie je Null, ..., ergens wat waardes, ..., Null

![image](https://github.com/user-attachments/assets/697c7943-89fd-4555-a8be-b8a11b564b55)

**Comment by MaartenHilferink** [comment]
Statistic is now:
![image](https://github.com/user-attachments/assets/67fbb9bd-441a-4d10-9dd1-7270ce3093c1)
