### ISSUE TITLE
verschil in uitkomst tussen 15.10.2, 16.0.0 en 16.0.1

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#841]
Ik zie op onze geodms-p5 verschil in uitkomsten voor 3 verschillende exe's 15.10.2, 16.0.0 en 16.0.1 voor het item:
/Analysis/Allocatie/Zichtjaren/Y2060/impl/ReadStand/Subsector_rel

PD 11313: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/WLO2024
SD 11303: https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL

Ik heb de github logs bekeken van de verschillende exe's maar zie geen echte aanknopingspunten  (ook de about boxen zijn hetzelde)

15.10.2
![subsector_rel_Y2060_HOOGBAU_WLO2024_V11313_geodms_15102](https://github.com/user-attachments/assets/7edc0816-cd8e-4f21-8050-8c45908db48d)

16.0.0
![subsector_rel_Y2060_HOOGBAU_WLO2024_V11313_geodms_1600](https://github.com/user-attachments/assets/47f4f98d-6709-4932-98d6-2f49f02f296b)

16.0.1
![subsector_rel_Y2060_HOOGBAU_WLO2024_V11313_geodms_1601](https://github.com/user-attachments/assets/2b1ef6dd-4299-4716-9d4d-d0a24d6d1d09)

Ik zie dat de python3.dll nieuw is vanaf 16.0.0

Verdere verschillen voor (zowel 15.10.2 - 16.0.0 als 16.0.0 -16.0.1)
Clc.dll
Geo.dll
python3.dll (nieuw dus)
Rtc.dll
Shv.dll
Stg.dll
Stx.dll
Sym.dll
Tic.dll
GeoDmsGuiQt.exe
GeoDmsRun.exe
geodms.pyd

Kun je advies geven welke exe nu te gebruiken, ik neig naar 15.10.2 overigens

**Comment by MaartenHilferink** [comment]
mogelijke gerelateerd aan #838

**Comment by MaartenHilferink** [comment]
Mogelijk het probleem gevonden, ik maak een prerelease voor je om dat te testen, zie commit die hier zo bij staat.

**Comment by basvanbemmel** [comment]
ok dank voor de pre-release, ik kan er vanavond naar kijken (deze middag vrij)

**Comment by MaartenHilferink** [comment]
Bijvoorbeeld in de berekening van

**Comment by basvanbemmel** [comment]
Ik heb in 16.0.2. kunnen runnen. Wel weer een andere uitkomst. De vraag is nu wel welke exe nu inhoudelijk het juiste resultaat oplevert. Nog niet zo makkelijk te beantwoorden mijn inziens.

resultaat 16.0.2
![image](https://github.com/user-attachments/assets/759494dc-5cdd-4eb5-8149-18e7f2dd22c2)

Verschil 15.10.2 en 16.0.2 (gaat om Wonen 2060, groen wel wonen in 15102 en niet in 16.0.2, rood geen wonen in 15102 en wel in 16.0.2)
![image](https://github.com/user-attachments/assets/67a99a59-d17a-495d-b61f-e5b2ff66a438)

**Comment by MaartenHilferink** [comment]
Ik heb wijzigingen in WLO2024_v15.4.0 gecommit maar (nog) niet resultaten voor 2060 kunnen opvragen. Jij wel? 
N.b.: ik had wel al PlanCapaciteit_filedate in ModelParameters.dms aangepast, om naar hier beschikbare data te wijzen.

**Comment by basvanbemmel** [comment]
Ik ga het checken

**Comment by basvanbemmel** [comment]
ik krijg

![image](https://github.com/user-attachments/assets/0e6e769b-7e4c-4b52-bfd5-43064651f6d4)
