### ISSUE TITLE
Rare lookup van 2d domain

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#845]
In mapview druk je op water, maar layercontrol geeft andere value.
![image](https://github.com/user-attachments/assets/fbc8eeb6-fb49-4e58-ab98-c017c51ea37a)

In 15.10.2 werkte het zoals het hoort.

**Comment by jipclaassens** [comment]
Ik heb jouw laatste commit binnengehaald en gebuild, maar helaas nog niet opgelost...

**Comment by MaartenHilferink** [comment]
Fixed in 16.0.5
