### ISSUE TITLE
Foutmelding door missende fss'en. ExprParser Error: DataItem expected as left operand of arrow

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#9]
OVSRV6
C:\ProjDir\Jip\Verdichting_issueGH9\cfg\verdichting.dms

Rood en error op:
/Analyse/RedevelopmentPaper/Export

**Comment by MaartenHilferink** [comment]
Unable to reproduce; what is the issue ?

ShiftF2 -> /Analyse/RedevelopmentPaper/Prep/Panden/Read_uq_identificatie/Correctie/WoningTotalenCheck/PerRedevType/Sloop_Woon/pand_selectie
"Error: cannot find uq_identificatie/Correctie/IsSloop_Woon"

Correct, as uq_identificatie does not exist, should this be Read_uq_identificatie or Make_uq_identificatie ?

**Comment by jipclaassens** [comment]
de foutmelding omschrijft niet het probleem.

**Comment by MaartenHilferink** [comment]
Diagnostic is produced for:

/Analyse/RedevelopmentPaper/AdditionalOperations/SN/woon/intersect/nieuwbouw_perceel_metSloop/second_rel
 and has been updated to 
"DataItem expected as left operand of arrow; reference 'org_rel' not found"
