### ISSUE TITLE
New feature: create bookmarks in gui

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#91]
The used should be able to create bookmarks on a specific configuration. These bookmarks could be implemented as buttons. When clicked, geodms state is changed to the state of the bookmark. The state encompasses:
- open views and their position
- for every view, the cursor position (tableview) or zoom and extent (mapview)
- DetailPages: active page

**Comment by eoudejans** [comment]
Part of this functionality is already present: see usage of ctrl-G and MapView

**Comment by MaartenHilferink** [comment]
duplicate with #163
