### ISSUE TITLE
Menu hotkeys in new gui

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#92]
ie. Alt-F, ALT-E as open

**Comment by MaartenHilferink** [comment]
And, 
- when pull-down menu active (and therefore having key-focus): underline first non pre-occuring char in  each item, and let that char be a selector
- when TreeView having key-focus: idem. ; use '+' and Right to expand, '-' and left to collapse.
- when pressing Alt-R, reactivate the same item by storing full-path

**Comment by MaartenHilferink** [comment]
implemented in Qt
