### ISSUE TITLE
DetailPages: add metadata

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/GeoDMS#97]

**Comment by eoudejans** [comment]
The Delphi metadata functionality is more sophisticated than at first sight. The GeoDMS Delphi Gui DetailPages make use of the [TWebBrowser](https://docwiki.embarcadero.com/Libraries/Sydney/en/FMX.WebBrowser.TWebBrowser) component. This component makes it possible to render html code. 

One of the uses for this html code rendering was the export settings functionality, which allowed for dynamically editing a predefined custom html page with placeholder values of for instance the document DPI. This feature is currently not build in to the new ImGui GeoDMS application, and will require a thorough design and rethinking what we want to do with it.

**Comment by eoudejans** [comment]
Another use of the Metadata DetailPages tab was the visualization of a webpage or pdf document for a given TreeItem. This functionality has been moved to the right-click popup window in the TreeView, where users can navigate to the url if available using the system's default browser:
![treeitem_url_nav](https://user-images.githubusercontent.com/96182097/213417628-439bd96c-14e9-4cad-82a9-9ba338c9de6b.png)

**Comment by eoudejans** [comment]
Closing issue, the full working of the metadata tab needs rethinking, opening dedicated discussion.

**Comment by MaartenHilferink** [comment]
Or have an icon in the TreeView, see #106

**Comment by MaartenHilferink** [comment]
I want to see that actually configured URL's work and are clickable.
